[1단계 - 지하철 노선도 미션] 신세한탄(신세희) 미션 제출합니다.
woowacourse/react-subway-map pull request #14
Opened 2021-05-30 04:29 UTC by shinsehantan

안녕하세요. 제이비님 🐝
리액트 쇼핑카트에 이어서 지하철 노선도로 인사드리게 된 신세한탄입니다.🧚🏼‍♀️🧚

이번 지하철 노선도 미션은 동동(@bigsaigon333)과 함께 진행했습니다.

[데모페이지 ](https://shinsehantan.github.io/react-subway-map/)
[VSCODE in web](https://github1s.com/shinsehantan/react-subway-map/tree/shinsehantan-step1)

아직 리액트 쇼핑카트 2단계도 제출하지 못했지만..ㅎㅎㅎㅎ
지하철 노선도 미션도 잘 부탁드립니다!

2021-05-30 14:03 UTC, JaeYeopHan requested changes
고생많으셨습니다! 👍

2021-05-30 14:03 UTC, jbee37142 commented on src/components/@shared/Button/index.jsx
> +    type={type === "submit" ? "submit" : "button"}
1. button의 type에는 reset도 있습니다 ㅎㅎ
2. type의 default parameter를 전달하는 방식으로 진행하고 그대로 type을 넘겨줘도 될 것 같아요! (default는 이미 있구요)

2021-05-30 14:03 UTC, jbee37142 commented on src/components/@shared/Button/index.jsx
> +  value,
button Element의 attributes는 전부 넘길 수 있도록 처리하고 그대로 넘겨주는 것이 좋을 것 같아요!

2021-05-30 14:03 UTC, jbee37142 commented on src/components/@shared/Button/index.jsx
> +    value={value}
button에 value는 뭔가요?

2021-05-30 14:03 UTC, jbee37142 commented on src/components/@shared/Button/index.jsx
> +    type={type === "submit" ? "submit" : "button"}
2번은 다른 component 에도 마찬가지 입니다~

2021-05-30 14:03 UTC, jbee37142 commented on src/components/@shared/Modal/hooks.js
> +export const useModal = (initialValue) => {
이 hooks는 useModal이라는 이름이 무색하게... 해주는 역할은 boolean state를 true/false로 toggle하는 것 뿐입니다!
modal과 관련된 내용을 전혀 담고 있지 않아요!

2021-05-30 14:03 UTC, jbee37142 commented on src/components/@shared/Modal/index.jsx
> +const Modal = ({ isOpen, children, close }) => {
props로 받는다면 onClose라는 네이밍 어떨까요?

2021-05-30 14:03 UTC, jbee37142 commented on src/components/@shared/Modal/index.jsx
> +        <div
적용된 스타일을 보니 dimmer 역할인 것 같은데 네이밍에서부터 dimmer임을 좀 더 드러내면 어떨까요?

2021-05-30 14:03 UTC, jbee37142 commented on src/pages/Lines/index.jsx
> +  const linesList = useSelector(selectLinesList);
온갖 값을 전부 이 `Lines`에서 가져오는데 그럴 필요있을까요?
컴포넌트를 상태별로 나누고 그 컴포넌트에서 필요한 상태만 가져다가 쓰면 어떨까요?

(linesList <- 이름만 보면 2x2배열같은데 맞나요...?)

2021-05-30 14:03 UTC, jbee37142 commented on src/pages/Lines/index.jsx
> +  const handleSubmit = (event) => {
handleSubmit이라는 함수는
```
        <form
          className="flex flex-col items-center px-4 py-12 w-144 bg-white rounded-lg shadow-2xl"
          onSubmit={handleSubmit}
        >
```

여기에서만 사용되는 걸로 보여요 👀

2021-05-30 14:03 UTC, jbee37142 commented on src/components/@shared/PublicRoute/index.jsx
> +    // eslint-disable-next-line react/jsx-props-no-spreading
이런 룰이 있는지 몰랐는데 아예 꺼버리는게 좋을 것 같네요 ㅎㅎ

2021-05-30 14:03 UTC, jbee37142 commented on src/components/@shared/FloatingLabelInput/index.jsx
> +        onFocus={handleInputFocus}
`FloatingLabelInput`을 사용하는 쪽에서 onFocus handler를 전달하고 싶을 수도 있지 않을까요?

2021-05-30 14:03 UTC, JaeYeopHan commented on src/pages/Logout/index.jsx
> +const Logout = () => {
요게 컴포넌트로 존재해야 하는 이유가 있나요? 👀

2021-05-30 14:03 UTC, JaeYeopHan commented on src/components/@shared/Input/hooks.js
> +export const useInput = (validator, replacement = "") => {
`replacement` 대신에
`setValueAs: (value: string) => string`라는 함수를 받으면 좀 더 확장가능하고 재사용성이 높아지지 않을까요?
함수를 받으면 Number로 type을 캐스팅할 때도 이 useInput을 사용할 수 있을 것 같네요 ㅎㅎ

2021-05-30 14:11 UTC, bigsaigon333 commented
신세한탄 귀여웡 💓

2021-05-31 14:46 UTC, shinsehantan commented on src/components/@shared/Button/index.jsx
> +    value={value}
역, 노선, 구간 삭제 시 삭제하려는 타겟의 이름을 받아오기 위해
`value={name}`을 주어 사용했는데 `button`에 `value`를 넣는 게 좋지 않은 사용법인가요..?

2021-05-31 14:53 UTC, shinsehantan commented on src/components/@shared/Button/index.jsx
> +    type={type === "submit" ? "submit" : "button"}
버튼 타입에 reset도 추가했습니다 😂
삼항연산자를 쓰지 않고, type을 온전히 넘기도록 했습니다!
버튼은 정말 여러 형태가 될 수 있는만큼 이 방식이 맞는 것 같네요!

2021-05-31 14:54 UTC, shinsehantan commented on src/components/@shared/Button/index.jsx
> +  value,
버튼은 정말 여러 형태가 될 수 있는만큼 이 방식이 맞는 것 같네요! 감사합니다!

2021-05-31 16:45 UTC, shinsehantan commented on src/components/@shared/FloatingLabelInput/index.jsx
> +        onFocus={handleInputFocus}
아..! 해당 프로젝트 내에서는 아직 그런 경우가 없어서 고려하지 못했던 것 같습니다!
앞으로의 경우에 대비해서 `onFocus`를 넘길 수 있게 처리해두는 것이
조금 더 유연한 컴포넌트를 만드는 방법인가요? 
나중에 사용하게 될 때 넘기도록 수정하는 것은 너무 늦나요?ㅠㅠ
기준을 잡기가 쉽지 않네요ㅠㅠ

2021-06-01 15:33 UTC, shinsehantan commented on src/pages/Lines/index.jsx
> +  const linesList = useSelector(selectLinesList);
`Lines` 페이지에서 컴포넌트를 추출하여 분리하고, 상태도 각 컴포넌트에서 필요한 상태만 직접 불러 사용할 수 있게 변경했습니다 :)
단순히 파일 분리만 하면 된다고 생각했는데, 컴포넌트가 분리되니 부모 상태가 변할 때마다 자식 컴포넌트가 계속 `mount`되는 일이 생겨 생각보다 어려웠습니다...ㅠㅠ

`Lines`와 관련된 모든 곳에 노선 페이지와 관련되었다는 의미로 `lines`를 붙여 사용했었는데, 지금보니 `list`와 `items`는 그 자체로 복수의 의미를 가져 앞이 `lines`가 되면 의미상 맞지 않는 것 같다는 생각이 들어 `linesList`, `linesItems` 네이밍은 `lineList`, `lineItems` 등으로 수정했습니다.

2021-06-01 15:48 UTC, shinsehantan commented on src/pages/Lines/index.jsx
> +  const handleSubmit = (event) => {
`LinesModalInner` 컴포넌트를 `Lines` 페이지에서 분리하면서, 이 함수도 함께 가져왔습니다 : )

2021-06-01 16:03 UTC, shinsehantan commented on src/components/@shared/Modal/index.jsx
> +const Modal = ({ isOpen, children, close }) => {
버튼에 직접 연결된 함수가 아니라서 on을 생략했었는데 props로 넘길 때에도 `on`을 많이 붙이는군요! 감사합니다 :)

2021-06-01 16:42 UTC, shinsehantan commented on src/components/@shared/Modal/index.jsx
> +        <div
오! 이 아이는 다른 곳에서도 충분히 쓰일 수 있는 아이인 것 같아서 `Dimmer`로 네이밍해서 분리해보았습니다~!

2021-06-02 05:40 UTC, shinsehantan commented on src/components/@shared/Modal/hooks.js
> +export const useModal = (initialValue) => {
`useModal`에서 `useToggle`로 네이밍을 변경하고, `hooks` 파일 위치도 `Modal` 폴더 하위에서 `shared`로 이동시켰습니다 : )

2021-06-02 13:37 UTC, shinsehantan commented on src/pages/Logout/index.jsx
> +const Logout = () => {
로그아웃 로직만 들어있어서 사실 컴포넌트로 존재할 이유가 전혀 없었네요..! `Header` 내에서 `NavLink`에 `onClick` 이벤트로 로그아웃 시키는 것으로 변경하였습니다 : )

2021-06-02 15:49 UTC, shinsehantan commented on src/components/@shared/Input/hooks.js
> +export const useInput = (validator, replacement = "") => {
`replacement` 대신에 `setValueAs`라는 함수를 받기.... 흑흑... 이해해보려고 노력했지만... 실패했습니다... 힌트를 좀 더 주시면 좋겠습니다 ㅠㅠㅠㅠ

2021-06-02 16:15 UTC, shinsehantan commented on src/components/@shared/PublicRoute/index.jsx
> +    // eslint-disable-next-line react/jsx-props-no-spreading
저는 해당 룰을 이미 파일 여기저기서 `off`하고 사용했기 때문에,
끄고 사용하는 게 맞을 것 같아 전체 파일에서 꺼버렸지만,

`props`를 명시적으로 넘기고, 의도치 않은 `props` 전달을 방지하기 위해서 쓰는 룰이라는 점에서
제이비님은 왜 꺼버리는 것을 추천하셨는지 제이비님의 의견?이 궁금합니다!!🙂🙂

2021-06-03 02:22 UTC, JaeYeopHan commented on src/components/@shared/Button/index.jsx
> +    value={value}
그 의도라면 children으로 받으면 어떨까요? value는 input 또는 select 처럼 form element에서 사용하곤 해서요!

2021-06-03 02:27 UTC, JaeYeopHan commented on src/components/@shared/PublicRoute/index.jsx
> +    // eslint-disable-next-line react/jsx-props-no-spreading
> 의도치 않은 props 전달을 방지하기 위해서 쓰는 룰이라는 점

이건 eslint의 역할이라기 보다는 typescript나 flow가는 정적 타이핑을 통해 해결해야 하는 부분이라고 생각해요~

2021-06-03 02:27 UTC, JaeYeopHan commented on src/components/@shared/FloatingLabelInput/index.jsx
> +        onFocus={handleInputFocus}
추상화레벨에 따라 props를 다르게 디자인 할 수 있겠지만, @shared 라는 directory에 위치한 컴포넌트들은 최대한 확장 가능하도록 설계하는 것이 좋다고 생각해요 ㅎㅎ

2021-06-03 02:29 UTC, JaeYeopHan commented on src/components/@shared/Input/hooks.js
> +export const useInput = (validator, replacement = "") => {
```ts
useInput(validator, value => value.replace(''))
```

useInput을 이렇게 디자인해볼 수 있지 않을까 해서 드린 코멘트였어요~

2021-06-03 02:29 UTC, JaeYeopHan approved these changes
수고하셨습니다!
질문 주신 부분은 코멘트로 달아뒀어요!! 👍

2021-06-03 02:30 UTC, merged