[1단계 - 지하철 노선 미션] 브콜(오태은) 미션 제출합니다.
woowacourse/react-subway-map pull request #17
Opened 2021-05-31 09:43 UTC by Tanney-102

안녕하세요 권현아님! 브콜입니다 🥦🥦🥦🥦

우테코에 와서 첫 리뷰를 권현아님께 받았었는데 마지막도 함께하게 되었네요! (미션하면서 무려 3번이나 받게 되었네요 ㅎㅎ)
그동안 리뷰로 수고해주셔서 정말 감사했습니다!!
이번에도 잘 부탁드리겠습니다.

## [데모페이지](https://beuccol-react-subway.netlify.app/)

## 기능 목록
- 회원가입, 로그인 기능
- 역 관리, 노선 관리, 구간 관리
  - 조회, 추가 및 삭제 기능
  - 로그인한 사용자에 한해서만 추가 삭제 가능

<img width="1675" alt="스크린샷 2021-05-31 오후 6 39 29" src="https://user-images.githubusercontent.com/57767891/120174228-d360d980-c23f-11eb-80d2-b4d3f47d1a86.png">

2021-06-06 11:31 UTC, HyeonaKwon requested changes
브콜님 안녕하세요! 리뷰 늦게 달아서 정말 죄송합니다😭
세부적인 내용은 코멘트를 확인해주세요!

2021-06-06 11:31 UTC, HyeonaKwon commented on package.json
> +    "@types/react-router-dom": "^5.1.7",
types 는 dev 로 옮겨주세요~!

2021-06-06 11:31 UTC, HyeonaKwon commented on package.json
> +  "eslintConfig": {
eslintrc 로 옮기는게 좋을 것 같네요!

2021-06-06 11:31 UTC, HyeonaKwon commented on src/components/Header/Header.styles.ts
> +  z-index: 50;
z-index 는 관리도 하면 좋을 것 같아요!  
컴포넌트가 많아지면 나중에는 다른 컴포넌트의 z-index 때문에 고생하는 상황이 발생할 수 있어요!

2021-06-06 11:31 UTC, HyeonaKwon commented on src/components/Header/Header.tsx
> +      }
`setIsAppear(deltaY < 0)`

2021-06-06 11:31 UTC, HyeonaKwon commented on src/components/shared/Box/Box.style.ts
> +  `
```javascript
${({ hatColor }) =>
  hatColor && css``;
```
styled-component 에서 제공하는 css 를 사용하면 삼항연산자를 사용하지 않아도 됩니당 :)

2021-06-06 11:31 UTC, HyeonaKwon commented on src/components/shared/Spinner/Spinner.style.ts
> +    z-index: 19;
z-index 에 이런 애매한(?) 숫자는 동료를 힘들게 합니다..!

2021-06-06 11:31 UTC, HyeonaKwon commented on src/hooks/useSections.ts
> +};
`API` 요 친구는 각 hooks 가 들고 있는게 아니고 공통된 객체를 사용하는게 좋겠네요! 중복이 많습니당

2021-06-06 11:31 UTC, HyeonaKwon commented on src/hooks/useSections.ts
> +    const accessToken = localStorage.getItem('accessToken');
accessToken 꺼내는것도 공통화되었으면 좋겠네요! localStorage 에 저장하는 키 값이 바뀌면 전체를 다 찾아가면서 바꿔줘야겠죠??

2021-06-06 11:31 UTC, HyeonaKwon commented on src/pages/LinePage/LinePage.tsx
> +  }
함수 선언들 사이에 useEffect 와 if 이 있어서 다른 동료들 입장에서는 요 리턴이 어디서 오는지 찾기 어려울 것 같아요!

2021-06-06 11:31 UTC, HyeonaKwon commented on src/pages/LoginPage/LoginPage.tsx
> +      localStorage.setItem('accessToken', accessToken);
요런거는 api 에서 끝내고 넘어올 수 있지 않을까요?? 컴포넌트가 해야하는 일인지 궁금합니다!

2021-06-06 11:31 UTC, HyeonaKwon commented on src/pages/SectionPage/SectionPage.tsx
> +  );
음.. 뭔가 너무 어렵게 생각한 것 같다는 느낌이 듭니당! stations 의 length 가 1 인지 확인하는 것과는 다른 이유가 있나요??

2021-06-06 11:31 UTC, HyeonaKwon commented on src/pages/SectionPage/SectionPage.tsx
> +  const isDistanceValid =
요거 LinePage 에서도 본 것 같네요!

2021-06-06 11:31 UTC, HyeonaKwon commented on src/pages/SectionPage/SectionPage.tsx
> +    const timer = setTimeout(() => setIsLoading(true), 500);
로딩 변화를 setTimeout 으로 하는 이유가 있나요??

2021-06-06 11:31 UTC, HyeonaKwon commented on src/pages/SectionPage/SectionPage.tsx
> +  if (lines === LINE_BEFORE_FETCH || stations === STATION_BEFORE_FETCH) {
배열의 주소값을 비교하는 방법으로 api 호출 전인지를 체크하는 것은 이상해보입니다! 예를 들어 api 호출에 관한 status 를 관리한다던지와 같은 방법이 아니구요!

2021-07-03 10:20 UTC, Tanney-102 commented on package.json
> +    "@types/react-router-dom": "^5.1.7",
아아 넵 types는 dev로 가야겠군요ㅠㅠ 다음부턴 더 신경쓰겠습니당 ㅎㅎ

2021-07-03 10:20 UTC, Tanney-102 commented on package.json
> +  "eslintConfig": {
이부분도 신경쓰질 못했네요ㅜㅜ 수정했습니다! ㅎㅎ

2021-07-03 10:21 UTC, Tanney-102 commented on src/components/Header/Header.styles.ts
> +  z-index: 50;
z-index를 관리할 생각은 못했는데 충분히 신경써야할 부분인 것 같습니다 ㅎㅎ 조언 감사해요!

2021-07-03 10:21 UTC, Tanney-102 commented on src/components/Header/Header.tsx
> +      }
계속 이런 부분을 놓치네요ㅜㅜ 잡아주셔서 감사합니당 ㅎㅎ

2021-07-03 10:22 UTC, Tanney-102 commented on src/components/shared/Box/Box.style.ts
> +  `
아아 더 간략히 나타낼 수 있겠네요! 전체적으로 수정했습니당 ㅎㅎ

2021-07-03 10:23 UTC, Tanney-102 commented on src/hooks/useSections.ts
> +};
조언해주신데로 api를 분리하는데 시간을 많이썼는데 생각만큼 잘 되질 않네요ㅜㅜ 여전히 중복도 많고... 계속 연구해보겠습니다ㅜㅜ

2021-07-03 10:24 UTC, Tanney-102 commented on src/hooks/useSections.ts
> +    const accessToken = localStorage.getItem('accessToken');
넵 ㅎㅎ 하나의 모듈에서 관리하도록 수정했습니다!!

2021-07-03 10:24 UTC, Tanney-102 commented on src/pages/LinePage/LinePage.tsx
> +  }
return 문에서 삼항으로 처리하도록 수정했습니다!

2021-07-03 10:25 UTC, Tanney-102 commented on src/pages/LoginPage/LoginPage.tsx
> +      localStorage.setItem('accessToken', accessToken);
우선 관련 로직을 hook으로 분리하긴했는데 해당 코드가 어디에 있는게 적절할지 더 고민해보겠습니당

2021-07-03 10:27 UTC, Tanney-102 commented on src/pages/SectionPage/SectionPage.tsx
> +  );
두 select input에서 선택한 역 중 단 하나(둘 다 없어도 안되고 둘 다 있어도 안됨)만 노선에 포함되어있어야 해서 위와 같이 적었습니다!

2021-07-03 10:27 UTC, Tanney-102 commented on src/pages/SectionPage/SectionPage.tsx
> +  const isDistanceValid =
line에서도 distance라는 state를 들고있어서 중복이 되는 부분이네요! 수정해보도록 하겠습니당

2021-07-03 10:28 UTC, Tanney-102 commented on src/pages/SectionPage/SectionPage.tsx
> +    const timer = setTimeout(() => setIsLoading(true), 500);
로딩 화면이 너무 짧은 시간 나타나는 것을 방지하고자 위와 같이 작성했습니다
해당 부분도 많이 반복되어 함수로 분리했습니다!

2021-07-03 10:30 UTC, Tanney-102 commented on src/pages/SectionPage/SectionPage.tsx
> +  if (lines === LINE_BEFORE_FETCH || stations === STATION_BEFORE_FETCH) {
api 호출에 실패하는 상황도 고려해봤는데 아무래도 좋은 표현은 아닌 것 같네요..ㅠㅠㅠ
더 고민해보겠습니다ㅜㅜ

2021-07-03 10:34 UTC, Tanney-102 commented
현아님 안녕하세요! 브콜입니다 ㅎㅎ
우선 너무 너무 늦어서 죄송합니다ㅜㅜㅜㅜㅜㅜㅜ
어디서부터 꼬인건지 피드백을 반영하면서 이래저래 욕심을 내다보니 대공사를 해버렸습니다ㅜ
잘하고 싶었는데 생각보다 쉽지 않네요..
어쨌거나 진작 코멘트 달고 인사도 드렸어야 했는데 참 민망합니다..
바쁜 중에도 늘 정성스럽게 리뷰해주셔서 감사했습니다! 좋은 개발자되어 현업에서 뵙겠습니당 ㅎㅎ

2021-07-03 10:59 UTC, merged