[1단계 - 지하철 노선도 미션] 디토(천영석) 미션 제출합니다.
woowacourse/react-subway-map pull request #18
Opened 2021-05-31 11:34 UTC by dudtjr913

안녕하세요. 권현아 리뷰어님! 이번 미션은 체프(@Puterism)와 함께 진행했습니다. 피드백 잘 부탁드립니다!

## [데모 페이지](https://ditto-react-subway.netlify.app/)

## 기술 스택
- 언어: `Typescript`
- 대표 라이브러리: `React`
- 스타일: `Styled-components`
- 상태관리; `Redux Toolkit`
- 테스트: `React-testing-library + Jest`, `msw`

## 중점적으로 봐주셨으면 하는 부분
- Typescript를 처음 도입해봤는데, 타이핑이 제대로 되었는지 궁금합니다. 타이핑이 너무 어렵네요...ㅠㅠ
- RTL을 처음 사용해봤는데, 테스트가 제대로 되었는지, 부족한 테스트 케이스가 있다면 알려주세요!

## 🙋‍♂️🙋‍♀️질문
- 비동기 요청에 대한 에러 처리를 어디에서 하는 것이 좋을지 궁금합니다. 페이지에서 하는 방법과 커스텀 훅에서 하는 방법 중에 고민이 되는데, 페이지에서 하면 선언적인 리액트에 맞지 않는다고 생각해서 이런 궁금증을 가지게 되었습니다.

## 기능 구현 목록
### 로그인 페이지
- [x] 사용자는 가입한 계정으로 로그인을 할 수 있다.
- [x] 로그인에 실패한 경우 실패한 이유를 확인할 수 있어야 한다.
- [x] 사용자는 로그인하여 지하철 노선도 관리 페이지에 접근할 수 있다.
### 회원가입 페이지

- [x] 사용자는 회원 가입을 할 수 있다.
  - 회원가입을 할 때 필요한 정보는 다음과 같다.
    - 나이 
      - 나이는 1부터 150 이하의 숫자만 입력할 수 있다.
    - 이메일 
      - 이메일은 이메일 형식을 만족해야 한다.
    - 비밀번호 및 비밀번호 확인
      - 비밀번호는 공백 문자를 입력할 수 없다.
      - 비밀번호 확인은 비밀번호와 동일해야 한다.
- [x] 가입시 이미 가입한 이메일인지 중복 확인
  - 이미 가입한 이메일인 경우에는 에러 메시지가 출력된다.
### 지하철역 관리 페이지
#### 지하철역 추가
- [x] 사용자는 지하철 역을 추가할 수 있다.
  - 역 이름은 2자 이상 20자 이하의 한글 (숫자 포함. 공백 허용 X) 이어야 한다.
- [x] 사용자는 지하철 역을 삭제할 수 있다.
  - 노선에 등록되어 있는 역인 경우 삭제할 수 없어야 한다.
  - 역 목록에서 [삭제] 버튼을 클릭하여 지하철 역을 삭제할 수 있어야 한다.
- [x] 사용자는 등록되어 있는 전체 지하철 역 목록을 조회할 수 있다.

### 지하철 노선 관리 페이지
- [x] 사용자는 지하철 노선을 추가할 수 있다.
  - 지하철 노선을 추가할 때 필요한 정보는 다음과 같다.
    - 이름 
      - 노선의 이름은 2자 이상 10자 이하의 한글 (숫자 포함. 공백 허용 X) 이어야 한다.
    - 상행역 및 하행역
      - 기존에 등록되어 있는 지하철 역 목록 중에서 선택할 수 있어야 한다.
    - (최초 상행역과 하행역 구간의)거리
      - 거리는 자연수여야 한다.
    - 색상
      - 색상은 미리 지정되어 있는 10가지 색상 중 한 색상을 선택할 수 있어야 한다. 
      - 다른 노선에서 사용하는 색은 선택 할 수 없다.
- [x] 사용자는 등록되어 있는 지하철 노선을 삭제할 수 있다.
  - 노선 목록에서 [삭제] 버튼을 클릭하여 지하철 노선을 삭제할 수 있어야 한다.
- [x] 사용자는 등록되어 있는 전체 지하철 노선 목록을 조회할 수 있다.

### 지하철 구간 관리 페이지
- [x] 사용자는 특정 노선을 선택하면 노선의 전체 구간 목록을 조회할 수 있다.
- [x] 사용자는 특정 지하철 노선에 구간을 추가할 수 있다.
  - 지하철 구간을 추가할 때 필요한 정보는 다음과 같다.
    - 노선
      - 기존에 등록된 지하철 노선 목록에서 선택할 수 있어야 한다.
    - 상행역 및 하행역
      - 기존에 등록되어 있는 지하철 역 목록 중에서 선택할 수 있어야 한다.
    - 거리
      - 거리는 자연수로 입력받을 수 있어야 한다.
  - 하나의 역은 여러 개 노선에 중복되어 포함될 수 있다.
  - 역과 역 사이에 새로운 역을 추가할 수 있다.
  - 하나의 노선에서 갈래길은 생길 수 없다.
- [x] 사용자는 노선에 등록되어 있는 구간을 삭제할 수 있다.

2021-06-06 14:56 UTC, HyeonaKwon requested changes
안녕하세요 디토님! 리뷰 늦게 남겨 죄송합니다😭
전반적으로 코드가 깔끔하네요 👍  몇개 안되지만 코멘트 확인해주시면 머지하겠습니다~
(그리고 지금처럼 훅에서 에러처리하는 것 좋아보입니다!)

2021-06-06 14:56 UTC, HyeonaKwon commented on src/hooks/useStation.ts
> +    if (!(name.length > 1 && name.length < 21)) {
1, 21 요런건 상수화하면 좋겠네요! 물론 간단해서 무슨 의미인지는 알겠지만!

2021-06-06 14:56 UTC, HyeonaKwon commented on src/mocks/handlers.js
> +          status: 404,
400 이랑 404 로 다르게 주는 이유가 있나요??

2021-06-06 14:56 UTC, HyeonaKwon commented on src/pages/SignUpPage/SignUpPage.tsx
> +  const { value: age, onChange: onChangeAge, ref: ageRef } = useInput(-1);
요런 경우에 null 을 주고 싶다는 질문인 것 같은데요!  
input 의 value는 string 이니 "" 으로 통일하고 가져다 사용할때만 타입 캐스팅을 하는건 어떨까 싶습니다.  
input 의 값을 null 로 설정하는게 더 어색해보여요!

2021-06-06 14:56 UTC, HyeonaKwon commented on src/pages/SignUpPage/SignUpPage.tsx
> +    if (!isSuccess) return;
`invalidFormRef` 이 존재하면 onSignUp 을 하면 안되지 않을까요??

2021-06-06 16:45 UTC, dudtjr913 commented on src/mocks/handlers.js
> +          status: 404,
앗.. 신경을 쓰지 못한 것 같습니다. 404로 모두 변경했습니다!

2021-06-06 16:49 UTC, dudtjr913 commented on src/pages/SignUpPage/SignUpPage.tsx
> +    if (!isSuccess) return;
onSignUp을 할 때, 모두 검사를 하고 있어서 꼭 필요하지 않다고 생각했습니다! 하지만 방어 코드가 더 있으면 좋을 것 같아서 추가를 했습니다. 감사합니다~
해당 커밋입니다. 2af41a9

2021-06-06 16:49 UTC, dudtjr913 commented on src/hooks/useStation.ts
> +    if (!(name.length > 1 && name.length < 21)) {
상수화를 모두 했습니다! 감사합니다~
해당 커밋입니다. 073a4a7

2021-06-06 16:53 UTC, dudtjr913 commented on src/pages/SignUpPage/SignUpPage.tsx
> +  const { value: age, onChange: onChangeAge, ref: ageRef } = useInput(-1);
처음에는 ""로 두고 사용했었는데, ""로 하다보니 타입 추론이 string으로 되어서 사용하는 곳에서 Number을 사용해야 하는 일이 발생했습니다. Number이 너무 많이 사용되는 것 같아서 방법을 고민하다가 null이나 -1을 사용하면 해결된다는 것을 알게 되었고, 리뷰어님의 말씀대로 null은 값으로 어색하다는 생각이 들어서 null이 아닌 -1로 사용하게 되었습니다. 이 경우에도 모두 ""로 통일하는 것이 더 나은 방법일까요??😭😭

2021-06-06 16:58 UTC, dudtjr913 commented
피드백 주신 내용 모두 반영했습니다! 해당 코멘트에 해당 커밋을 남겨두었습니다! 감사합니다~!!
질문에 대한 답변도 감사합니다. 

https://github.com/woowacourse/react-subway-map/pull/18#discussion_r646142788 에도 남겼지만, input value에 -1을 사용하는 방법은 좋지 않은 방법일까요? 궁금합니다!!😍😍

2021-06-07 14:47 UTC, HyeonaKwon commented on src/pages/SignUpPage/SignUpPage.tsx
> +  const { value: age, onChange: onChangeAge, ref: ageRef } = useInput(-1);
아니요! 보통 -1 이나 "" 을 사용하는데 통일하고 싶다면 "" 으로 모두 통일하는게 어떨까 의견드린거였어요! 지금처럼 유지해도 괜찮습니다 :)

2021-06-07 14:47 UTC, HyeonaKwon approved these changes
금방 수정해주시네요~ 2단계에도 지금처럼 깔끔한 코드 기대하겠습니다 ㅎㅎ

2021-06-07 14:48 UTC, merged