[1단계 - 지하철 노선도 미션] 미키(권세진) 미션 제출합니다.
woowacourse/react-subway-map pull request #21
Opened 2021-06-01 16:53 UTC by 0307kwon

## **1단계 - 지하철 미션 🚋**

안녕하세요 발리스타님! 자동차 경주 미션 이후 처음이네요 😭😭😭😭

마지막 미션으로 발리스팀을 다시 만나게 되어 너무 기쁩니다!

마지막 미션인 만큼 열정을 담아 최선을 다해 배워가겠습니다!! 🔥🔥🔥

### **🙋‍♂️ 집중적으로 피드백 받고 싶은 부분**

#### 💕 커스텀 훅을 분리한 것이 적절할까요? 시도해보았습니다!

처음에는 formInput이라는 state로 모든 input을 하나로 묶어보려고 했는데

이건 너무 훅의 크기가 커지는 것 같아 포기하고

input에 관련된 변수와 로직들을 하나로 묶고 관심 있는 부분만 노출시키고 싶어

useNotificationInput과 useInput, 그리고 useReadyToSubmit 등의 커스텀 훅을 만들어 보았습니다!

이렇게 만들어보았더니 다음과 같은 장단점을 느꼈습니다.

*   장점
    *   어떤 input의 errorMessage가 다른 input에 의존되어 동작할 때, useNotificationInput이 의존성을 인자로 받기 때문에 구현이 편했습니다.
    *   input 상태와 해당 input과 관련된 로직을 한 곳에 묶어두어 가독성이 높아지는 것 같았습니다.
    *   setInput,setErrorMessage 등을 내부적으로 숨기고 필요할 때만 제한적으로 사용하게하여 에러를 줄일 수 있지 않을까 생각합니다.
*   단점
    *   자유도를 너무 빼앗아 가는 느낌이 들었습니다. 다양한 상황에 대처하기 어려웠습니다.
    *   이전에는 input 상태 선언들을 컴포넌트 상단에 모두 위치시켜 한눈에 어떤 input들이 있는지 확인할 수 있었는데 훅을 적용한 후에는 한눈에 보기가 어려워졌습니다.

의미가 있는 커스텀 훅이었을까요?! 더 좋은 방식으로 훅을 빼낼 수도 있을 것 같은데 아직 미흡하여 잘 모르겠습니다 ㅠㅜ

**커스텀 훅에 대한 발리스타님의 의견이 궁금합니다! 😁**

#### 💕 생각보다 편하지 않았던 리덕스 툴킷

물론 리덕스만 사용하는 것보다는 리덕스 툴킷이

액션을 일일이 만들어주지 않아도 된다는 점,

그리고 관련된 액션과 리듀서의 코드가 가까이 있어 파악하기가 쉬웠다는 점이 좋았습니다.

하지만 리덕스 툴킷도 생각보다 불편했습니다.

새로운 요청을 위한 리덕스 썽크 함수를 매번 만들어야하는 등 반복적인 작업을 하는 것은 여전했습니다.

저희가 **리덕스 툴킷을 처음 사용해보아 제대로 툴킷을 적용한 것인지** 중점적으로 봐주시면 좋겠습니다 :)

#### 💕 지하철 앱에 리덕스를 적용하는 것이 괜찮은 방식일까요?

우선 저희가 상태관리로 리덕스 툴킷을 적용한 이유는

*   과도한 prop drilling 방지
*   fetch로 가져온 데이터를 리덕스 상태로 가지고 있으면 불필요한 fetch를 줄일 수 있을 것

이렇게 2가지가 있었습니다.

하지만 실제로는 prop drilling이 그렇게 심하게 일어나는 것 같지는 않았고

fetch도 Get 요청을 최대한 줄여보려 했지만 결국에는 서버 데이터와 동기화를 위해 매번 fetch하는 수 밖에 없어

리덕스 툴킷을 사용하면서 리덕스의 장점을 그렇게 살리지는 못했다는 생각이 듭니다.

(Redux DevTool로 상태 변화를 추적하는 것은 편했던 것 같습니다.)

이번 미션은 정말로 fetch만 사용했어도 되었을지도 모른다는 생각이 듭니다.

아직까지는 redux를 사용하는 이유가 그렇게 와닿지 않아서

**혹시 현업에서는 어떤 이유로 redux를 많이 쓰는지 알고 싶습니다!**

#### 💕 아직 React Testing Library를 제대로 쓰지 못하는 것 같습니다

아직 단위 테스트와 E2E 테스트의 개념이 잘 잡히지 않는 것 같습니다.

이번 미션에서 저는 `<Signup />` 이라는 컴포넌트를 테스트하기 위해

여러 input을 입력하고, submit 버튼을 누르고, request 함수가 제대로 실행되었는지

검증하였습니다.

그런데 이런 방식으로 테스트하니 E2E 테스트라는 생각이 들었습니다.

저는 처음에는 컴포넌트라는 단위를 테스트하는 것이 단위 테스트라는 생각을 하였는데

이런 방식으로 테스트하니 유저 입장에서 처음부터 끝까지 테스트하는 E2E 테스트라는 생각이 들었습니다.

그리고 cypress처럼 input에 입력값을 넣고 버튼을 누르는 동작들이 화면에 보이는 것도 아니라 cypress보다 더 답답했습니다. React Testing Library의 장점을 제대로 활용하지 못하고 있다는 생각이 들었습니다.

이에 대해 다른 크루의 의견도 물어보았는데 테스트할 기능 하나만 빼고 모두 mocking하여 테스트하는 방식으로 하고 있다고 대답을 들었습니다.

**단위 테스트는 어디서부터 어디까지 mocking해야하는 것일까요? 궁금합니다! 🙋‍♂️**

2021-06-06 07:50 UTC, Vallista requested changes
안녕하세요 미키!
오랜만에 뵈어서 반갑네요~~ :) 
코드가 정말 많고,,, 커서,,, 꼼꼼히 리뷰하는데 좀 오래 걸렸습니다.

# UX 피드백

코드 피드백이 많아, 코드 피드백에 집중해주시면 좋겠습니다!

# 전반적인 코드 피드백

1. default props와 prop-types를 쓰셨는데요! 요 것을 사용한 의미가 무엇일까요? 왜 사용해야 하는지 이해가 되지 않은 상황에서 js에서 코딩 하던 방식을 그대로 사용하신 것 같아 보여요! 아니면 특별한 이유라도 있다면 말씀 주시면 감사하겠습니다! (story-book support를 위함일까요?)

2. 전반적으로 안정성이 있는 코드를 지향하는 것 같지 않아보였습니다! 관련하여 코드 라인에 포인트마다 피드백을 남겨두었으니 그러한 부분에 대해서 고민해보시면 좋겠어요!

3. 선언형 프로그래밍에 대해 다시 한 번 고민해보았으면 좋겠습니다. 무엇을 추구하려 하고, 현재 코드에 어떤게 결여되어있는지요! 특히 React에서 Component 단위로 DI를 Props로 보낼때 과연 다른 사람이 내 코드를 본다면, 해당 네이밍이 선언형으로 잘 짜여서 이해가 쉬울까? 를 고민해보면 좋겠어요!

4. FC를 쓰시면서 Children이 optional인 경우에는 사용하지 않으므로, VFC로 붙여주면 좋겠습니다!

5. @shared, @common 두 가지는 어떤 성격이며, 왜 분리하셨을까요? mixins 컴포넌트냐 단일로 쓰일 수 있는 컴포넌트냐.. 정도의 차이일까요? 개인적으로 두 개는 분리할 필요가 없어보이기도 하는데요! 흠,,, 적합하게 쓰고 있는지 한 번 생각해보면 좋겠습니다!

6. 모달 등의 공통적으로 사용할 수 있는 컴포넌트를 쪼개시면서 상태를 외부에서 위탁받아 의존하다보니, onClose 같은 친구를 주입해주기 위해 Drilling 이 진행되었네요. 과연 올바른 걸까요? 모달은 컴포넌트 그 자체로 내부에 상태를 은닉하여 동작할 수 있어보이고, onClose, onAction등은 override를 할 수 있도록 제공하거나 하면 좋겠습니다!

7. custom hooks를 적극적으로 사용하신 걸로 보입니다! 비단 공통되고 기능적인 로직만 빼려고 하지 마시고, 비즈니스 로직도 분리해보세요~ 지금 페이지 상에서 비즈니스 로직을 다 삼켜서 사용하고 있다보니 페이지 상에서 표현되는 부분이 많아보이네요~ 레이어를 커스텀 훅스로 분리할 수도 있답니다.

8. 객체 리터럴을 사용하는 것은 좋지만, 올바르게 사용하지 않는 부분이 다수로 보입니다! enum으로 충분히 대체될 수 있어보이고, enum으로 간단하게 해결할 수 있는 문제를 객체 리터럴 두 개로 매핑해서 사용하는 형태가 많이보여요. 요 부분도 코드리뷰에 남겼으니 한 번 확인해보시고 예시 코드도 작성해두었으니 고민해보세요!

9. 전반적으로 TypeScript Utility Type을 활용하고 있어보이지 않습니다! 활용가능한 부분이 어딘지 한번 고민해보시고, 코드 라인에는 간단하게 남겨두었으니 대체해보세요!

# 질문 답변

## 첫 번째 질문

```
💕 커스텀 훅을 분리한 것이 적절할까요? 시도해보았습니다!
처음에는 formInput이라는 state로 모든 input을 하나로 묶어보려고 했는데
이건 너무 훅의 크기가 커지는 것 같아 포기하고
input에 관련된 변수와 로직들을 하나로 묶고 관심 있는 부분만 노출시키고 싶어
useNotificationInput과 useInput 커스텀 훅을 만들어 보았습니다!
이렇게 만들어보았더니 다음과 같은 장단점을 느꼈습니다.

장점
어떤 input의 errorMessage가 다른 input에 의존되어 동작할 때, useNotificationInput이 의존성을 인자로 받기 때문에 구현이 편했습니다.
input 상태와 해당 input과 관련된 로직을 한 곳에 묶어두어 가독성이 높아지는 것 같았습니다.
setInput,setErrorMessage 등을 내부적으로 숨기고 필요할 때만 제한적으로 사용하게하여 에러를 줄일 수 있지 않을까 생각합니다.
단점
자유도를 너무 빼앗아 가는 느낌이 들었습니다. 다양한 상황에 대처하기 어려웠습니다.
이전에는 input 상태 선언들을 컴포넌트 상단에 모두 위치시켜 한눈에 어떤 input들이 있는지 확인할 수 있었는데 훅을 적용한 후에는 한눈에 보기가 어려워졌습니다.
의미가 있는 커스텀 훅이었을까요?! 더 좋은 방식으로 훅을 빼낼 수도 있을 것 같은데 아직 미흡하여 잘 모르겠습니다 ㅠㅜ

커스텀 훅에 대한 발리스타님의 의견이 궁금합니다! 😁
```

구현에 의미가 있는 커스텀 훅이라고 생각합니다! 지금의 구성을 초석으로 삼으셔서 조금 더 디벨롭을 해보면 좋겠어요. 요 것도 코드 라인에 피드백을 드리긴 했는데요! 어떤 형태로의 디벨롭이 있으면 좋겠냐면, 결국에는 다른 input에 의존되고 하는 스콥은 하나의 Form 일 것입니다. Form 내에서 이리저리 서로 input을 참조하는 흐름이겠죠? 그렇기 때문에 Form을 하나의 Context API로 제작을 해서, 공통 상태 모음을 만들고, 그 상태 모음에 변경된 값을 각 input에서 참조하여 message 로직을 구동시키는 방식으로. 

대략적인 설명은 드렸지만 잘 이야기 하기가 어렵네요 ㅋㅋ 정리하면 Context API로 Form 단위를 하나 맹글어서 그 안에 공통된 상태 만들고 input을 관리해봐라 이 말입니다 ㅋㅋ 물론 이렇게 구현하면서 성능적인 이슈도 겪으실 것이고 다양한 의문이 있겠지만, 한 번 시도 해보시는 걸 추천드려요.

## 두 번째 질문

```
💕 생각보다 편하지 않았던 리덕스 툴킷
물론 리덕스만 사용하는 것보다는 리덕스 툴킷이
액션을 일일이 만들어주지 않아도 된다는 점,
그리고 관련된 액션과 리듀서의 코드가 가까이 있어 파악하기가 쉬웠다는 점이 좋았습니다.
하지만 리덕스 툴킷도 생각보다 불편했습니다.
새로운 요청을 위한 리덕스 썽크 함수를 매번 만들어야하는 등 반복적인 작업을 하는 것은 여전했습니다.
저희가 리덕스 툴킷을 처음 사용해보아 제대로 툴킷을 적용한 것인지 중점적으로 봐주시면 좋겠습니다 :)
```

제가 RTK를 많이 활용해보지 않아서 모르겠는데, RTK는 Reducer, Action 등에 대해서 더 쉽게 도와주는 툴이지, Redux-Middleware를 쉽게 관리해주는 용도도 포함되어있나요? 따로 공식 문서를 봐도 middleware에 대한 처리는 보이지 않네요. 그렇다면 말씀주신 "새로운 요청을 위한 리덕스 썽크 함수를 매번 만들어야하는 등 반복적인 작업을 하는 것은 여전했습니다." 에 대한 부분에 대한 처리로 Redux-toolkit 적용한 것이라면 미스로 보입니다! (잘 몰라서 이 부분은 피드백 주시면 좋겠습니다)

제가 보기에 RTK를 제대로 썻는지에 대한 피드백을 하기에 커다란 어플리케이션이거나, 거대한 상태관리가 필요하다거나 하는 어플리케이션이 아니라서 해당 피드백은 힘들어보입니다! 다만 단순 사용에 대해서는 잘 사용하고 계신걸로 보이며, 더 큰 어플리케이션에 어떻게 사용하시는 지를 봐야겠네요... Prop Drilling을 최적화하기위해 잘게 상태를 쪼개서 useSelector를 컴포넌트 단위로 이용한다던가 뭐 그러한 패턴이 필요없는 규모의 어플리케이션으로 보여서요!

## 세 번째 질문

```
💕 지하철 앱에 리덕스를 적용하는 것이 괜찮은 방식일까요?
우선 저희가 상태관리로 리덕스 툴킷을 적용한 이유는

과도한 prop drilling 방지
fetch로 가져온 데이터를 리덕스 상태로 가지고 있으면 불필요한 fetch를 줄일 수 있을 것
이렇게 2가지가 있었습니다
하지만 실제로는 prop drilling이 그렇게 심하게 일어나는 것 같지는 않았고
fetch도 Get 요청을 최대한 줄여보려 했지만 결국에는 서버 데이터와 동기화를 위해 매번 fetch하는 수 밖에 없어
리덕스 툴킷을 사용하면서 리덕스의 장점을 그렇게 살리지는 못했다는 생각이 듭니다.
(Redux DevTool로 상태 변화를 추적하는 것은 편했던 것 같습니다.)
이번 미션은 정말로 fetch만 사용했어도 되었을지도 모른다는 생각이 듭니다.
아직까지는 redux를 사용하는 이유가 그렇게 와닿지 않아서
혹시 현업에서는 어떤 이유로 redux를 많이 쓰는지 알고 싶습니다!
```

저희 회사에서는 Redux를 많이 사용하는걸로 알고 있습니다. 다만 현업에서 Redux를 많이 사용하는지는 잘 모르겠고, 수치상으로는 제일 많이 사용하고 있는걸로 보이긴 합니다. (npm 트랜드 참고)

그러나 저희는 이번에 Redux를 탈피하려고 해요. Redux thunk, saga 등의 이벤트 핸들링이 너무 고통스러워서 다른 라이브러리를 찾아보고 있습니다. 그래서 내부에서 워크숍 중인게 있구요.

지하철 노선도 미션을 생각해봤을때, 전역 상태 관리가 그리 많이 필요없는 상황에서 부분적 모듈 상태 관리를 위해 Redux를 사용할 필요가 있었나? 는 잘 모르겠긴 하네요. 어플리케이션 상태관리가 크게 필요없는 미션이기도 해서 Context API와 Fetch만 갖고도 구현할 수 있었을 거라는 생각이 들구요. 다만 Redux를 사용하므로써 "상태관리"를 해주어 최적화를 분명히 해주고 있고, 그러한 부분에 대해 인지하지 못하고 사용하고 있어서 필요없나? 라는 고민이 드셨을 수도 있습니다. 오히려 Context API + Fetch를 했다면 상태관리를 위해 다양한 코드가 더 들어갔어야 할 것이라고 생각해요.

개발 시간상으로는 더 현명한 판단일 수 있었겠다는 생각이 듭니다.

## 네 번째 질문

```
💕 아직 React Testing Library를 제대로 쓰지 못하는 것 같습니다
아직 단위 테스트와 E2E 테스트의 개념이 잘 잡히지 않는 것 같습니다.
이번 미션에서 저는 <Signup /> 이라는 컴포넌트를 테스트하기 위해
여러 input을 입력하고, submit 버튼을 누르고, request 함수가 제대로 실행되었는지 검증하였습니다.

그런데 이런 방식으로 테스트하니 E2E 테스트라는 생각이 들었습니다.
저는 처음에는 컴포넌트라는 단위를 테스트하는 것이 단위 테스트라는 생각을 하였는데
이런 방식으로 테스트하니 유저 입장에서 처음부터 끝까지 테스트하는 E2E 테스트라는 생각이 들었습니다.
그리고 cypress처럼 input에 입력값을 넣고 버튼을 누르는 동작들이 화면에 보이는 것도 아니라 cypress보다 더 답답했습니다. React Testing Library의 장점을 제대로 활용하지 못하고 있다는 생각이 들었습니다.

이에 대해 다른 크루의 의견도 물어보았는데 테스트할 기능 하나만 빼고 모두 mocking하여 테스트하는 방식으로 하고 있다고 대답을 들었습니다.
단위 테스트는 어디서부터 어디까지 mocking해야하는 것일까요? 궁금합니다! 🙋‍♂️
```

리액트의 [테스팅 개요 문서](https://ko.reactjs.org/docs/testing.html)를 보시면 아래와 같은 내용이 있습니다.

```
얼마나 다양한 방법을 통해 실제 테스트 환경의 동작을 테스트할 것인가?
- 컴포넌트 안에서는 ‘유닛’테스트와 ‘통합’테스트의 차이는 명확하지 않습니다. 하나의 폼을 테스팅 한다고 할 때 테스트는 또한 버튼의 안의 부분에서 이루어지나요? 또는 버튼 컴포넌트에 알맞은 테스트를 할 수 있나요? 리팩 토링된 버튼이 폼 테스트에 오류를 일으키나요?
```

리액트에서의 컴포넌트 테스트는 아래의 두 단계가 합쳐져있다고 이야기합니다. 그러면 유닛과 통합 테스트는 무엇일까요?

- 유닛 테스트: 모든 함수나 메소드 등이 정확히 동작하는지에 대한 검증
- 통합 테스트: 모듈을 통합하는 과정에서 일어나는 일에 대한 검증

하나의 컴포넌트에는 해당 컴포넌트 내에서의 메소드, 여러 컴포넌트가 합성된 어떠한 결과 등이 존재합니다. 이러한 것들이 은닉되어있고, 이 은닉되어 있는 기능들이 제대로 테스트 되려면 "어떤 값이 어떤 상황에서 어떤 형태로 보여야 한다" 와 같은 테스트 로직이 될 것입니다. 이 것은 말씀하신 사용자 관점에서 "사용자가 어떤 값을 입력했을 때 이런 값이 이렇게 보인다" 와 비슷합니다.

하지만 두 가지의 의도는 다릅니다. E2E 테스트는 어떠한 시나리오를 기준으로 작성합니다. 예를들면 아래와 같죠.

1. 사용자가 로그인을 진행한다.
2. 로그인을 진행하는 과정에서 회원가입이 되어있지 않다.
3. 회원가입 버튼을 누른다
4. 회원가입 폼이 보인다.
5. 회원가입에 성공하면 어떤 모달이 보인다.
6. 회원가입에 실패하면 어떤 모달이 보인다.
7. ... (생략)

이러한 시나리오를 기준으로 정상적으로 출력 되었는지, 로케이션이 제대로 이동 되었는지 결과를 확인합니다. 그 결과 내부에는 API 콜도 있겠고, 다양한 시나리오를 작성하겠죠? 이러한 과정을 거치면서 세부적으로 무엇이 문제인지는 체크하지 않습니다. 철저하게 "사용자 관점에서" 테스트하기 때문이죠. 사용자 관점에서 결과가 제대로 나오는지가 중요합니다.

유닛 + 통합 테스트를 함께 곁들이는 컴포넌트 테스트는 다릅니다.

1. input A에 value 555가 들어왔을 때 Submit 을 눌렀을 때 어떠한 결과가 나와야한다.
2. API mock으로 테스트를 했을 때 결과값이 실패 시
3. props 값이 어떻게 들어왔을때 에러가 나오는지...

컴포넌트 테스트는 해당 기능이 제대로 동작하는지가 중요합니다. 사용자 관점이 아닌, 컴포넌트 내에서의 기능 관점이죠. 그렇기에 보이는 테스트와 달리, "해당 로직을 넣으면 로직이 정상적으로 동작한다" 와 같은 보이지 않아도 결과값이 산출되면 되는겁니다.

테스트란 무엇이고, 테스트를 적재적소에 재대로 사용하고 있고, Cypress로 여태까지 E2E를 가장한 통합 테스트와 유닛 테스트를 진행하지 않았는지 다시 한 번 고민해보시는 걸 추천드립니다 👍  아마, 제대로 활용하고 있는게 아닐 수 있어요!

p.s. 코드 라인 피드백이 좀 많습니다.. 화이팅!

2021-06-06 07:50 UTC, Vallista commented on .storybook/main.js
> +}
eof!

2021-06-06 07:50 UTC, Vallista commented on package.json
> +    "web-vitals": "^1.0.1"
오~~ 웹 바이탈도 쓰시나요?

2021-06-06 07:50 UTC, Vallista commented on src/App.tsx
> +axios.defaults.baseURL = API_INFO[getApiOwner()].endPoint;
axios initialize 를 하는 부분을 axios wrapper 정도로 만들어서 한 도메인에서 관리했으면 좋겠습니다!

2021-06-06 07:50 UTC, Vallista commented on src/App.tsx
> +const App: FC = () => {
children이 없으니까 VFC가 좋겠습니다!

```tsx
const App: VFC = () => {
```

2021-06-06 07:50 UTC, Vallista commented on src/App.tsx
> +    axios.defaults.baseURL = API_INFO[apiOwner].endPoint;
올바르지 않은 값들이 들어올 수도 있으므로

```tsx
axios.defaults.baseURL = API_INFO[apiOwner]?.endPoint;
```

이 낫지 않을까요?

2021-06-06 07:50 UTC, Vallista commented on src/App.tsx
> +      <Header title={APP_TITLE} logo={<Subway color={PALETTE.BLACK[400]} />}>
`PALETTE.BLACK[400]`보다 `PALETTE.BLACK_400`이 나아보입니다. 숫자로 하면 오타될 가능성이 높고, 네비게이팅이 안되니까여!

2021-06-06 07:50 UTC, Vallista commented on src/App.tsx
> +      <Header title={APP_TITLE} logo={<Subway color={PALETTE.BLACK[400]} />}>
그리고 굳이 배열로 접근해서 에러를 야기할 수도 있습니다. (물론 tuple이라 에러는 안날라나..?)

2021-06-06 07:50 UTC, Vallista commented on src/api/lines.ts
> +export const requestGetLines = (): Promise<AxiosResponse<Line[]>> => axios.get(`/lines`);
```tsx
export const requestGetLines = async (): Promise<AxiosResponse<Line[]>> => {
  try {
    return (
      await axios.get(`/lines`)
    )
  } catch (err) {
    new Error(err);
    return []
  }
}
```

요런식으로 해도 괜찮을 것 같네요~

2021-06-06 07:50 UTC, Vallista commented on src/api/lines.ts
> +export const requestGetLines = (): Promise<AxiosResponse<Line[]>> => axios.get(`/lines`);
try - catch에 대한 예외를 API 내에서 처리하고, 

사용처에서는 알 필요가 없이?

조금 더 디벨롭을 하자면 generic으로 에러에대한 상황도 넘길 수 있도록?

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Button/Button.tsx
> +interface Props extends ButtonHTMLAttributes<HTMLButtonElement> {
굿!

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Button/Button.tsx
> +Button.propTypes = {
타입스크립트를 쓰는데 propTypes가 필요있나요..?
필요하다면 어떤이유로 썻는지 궁금해요~

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Button/Button.tsx
> +Button.defaultProps = {
또한 이 구문도 필요없어보입니다~
충분히 Button 컴포넌트 내부에서 처리할 수 있어요~

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/CardTemplate/CardTemplate.styles.ts
> +const TITLE_SIZE = {
이러한 값이 들어간다면,

```tsx
enum TitleSize {
  sm: '1.75rem',
  md: '2.25rem',
  lg: '3rem',
}

interface StyledCardTemplateProps {
  templateColor?: string;
  isColoredTitle?: boolean;
  titleSize: TitleSize
}
```

가 낫지 않을까요?
굳이 매핑테이블을 추가로 만들어서 해줄 필요가 없어보여요!

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/CardTemplate/CardTemplate.styles.ts
> +export const CardTemplateTitle = styled.div``;
`CardTemplateTitle` 이친구는 왜있는걸까유?

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/CardTemplate/CardTemplate.styles.ts
> +export const CardTemplateTitle = styled.div``;
children에서의 체크를 위해 필요한것이면 className 부여해서 해도 괜찮을 것 같은데요!

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/CardTemplate/CardTemplate.tsx
> +  templateColor?: string;
Color도 String으로 받으면 문제가 있으니, Template Literal로 받거나, 아니면 enum 등을 만들어서 타입을 넘겨주는게 더 좋겠습니다.

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/CardTemplate/CardTemplate.tsx
> +CardTemplate.propTypes = {
여기도 propTypes가 필요한가유..?

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/ColorRadio/ColorRadio.tsx
> +ColorRadio.propTypes = {
propTypes가 필요한가유??

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/FlexContainer/FlexContainer.tsx
> +  justifyContent?: 'center' | 'flex-end' | 'space-between' | 'space-around';
'flex-start'는 없군요?

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Icon/Add.tsx
> +Add.propTypes = {
여기도 필요한가용?

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Icon/Arrow.tsx
> +Arrow.propTypes = {
여기도 필요한가용..?

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Icon/Add.tsx
> +  width?: string;
음 밑에서는 사용용도로 width, height에 전부 width를 넣고 있는데, 사전적 정의로는 맞는 말이긴 하지만 레이아웃에서 선언형으로 사용할 때 햇갈리지 않을까요? style propertie로 width가 있으니까요!

size? 정도가 더 낫지 않을지!

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Icon/Arrow.tsx
> +  width?: string;
여기도 동일하게 이름을 변경할 필요가 있어보입니다!

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Icon/Close.tsx
> +  width?: string;
여기도 사이즈가 더 낫지 않을까요?

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Icon/Close.tsx
> +Close.propTypes = {
프롭 타입스가 필요할까욥!?

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/ListItem/ListItem.tsx
> +      {isLogin && onModify && (
```tsx
{ 
  isLogin && (
    <>
     {onModify && <ListItemButton
          type="button"
          aria-label={LABEL_TEXT.MODIFY_BUTTON}
          buttonType="round"
          isColored={false}
          onClick={onModify}
        >
           <Pencil width="70^" />
      </ListItemButton>}
    {onDelete && <ListItemButton
          type="button"
          aria-label={LABEL_TEXT.DELETE_BUTTON}
          buttonType="round"
          isColored={false}
          onClick={onDelete}
        >
          <TrashBin width="70%" />
      </ListItemButton>}
      </>
  )
}
```

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Modal/Modal.tsx
> +  onClose: () => void;
어차피 onClose 이벤트가 없어도, close event가 진행되면 모달이 삭제되어야 하므로, optional 형태로 받고, 내부에서 modal에 대한 상태를 핸들링하여 삭제해주는 건 어떨까요?

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Modal/Modal.tsx
> +  onClose: () => void;
이렇게 되면 외부 이벤트에 의존하게 될 듯 해보여서요~ 모달은 그 자체로 컴포넌트가 될 수 있다고 생각함니다

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/NotificationInput/NotificationInput.styles.ts
> +    content: ${({ isError }) => (isError ? '"🚫 "' : '"✅ "')};
이거 윈도우나 구버전 기기나 브라우저에서도 잘 보이죵?

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/NotificationInput/NotificationInput.styles.ts
> +    content: ${({ isError }) => (isError ? '"🚫 "' : '"✅ "')};
https://www.lambdatest.com/blog/emoji-compatibility-with-browsers/

감안하고 쓰셨다면 상관없습니다~

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Snackbar/Snackbar.styles.ts
> +const fadein = keyframes`
fadein 보다 fadeIn 등이 더 날 듯 싶어요~

fadeEaseInOut 이런게 추가될수도 있으니..

2021-06-06 07:50 UTC, Vallista commented on src/components/@common/Snackbar/Snackbar.tsx
> +  duration = 3000,
요렇게 쓰니 default Props는 필요없으므로 모두 통일해주세용~

2021-06-06 07:50 UTC, Vallista commented on src/components/@shared/ButtonOnLine/ButtonOnLine.stories.js
> +import Add from '../../@common/Icon/Add';
궁금한 것!

@를 붙이므로써 더 의미가 강조되는게 있을까요?
common이나 @common이나 의미가 별 다른게 없어보여서요!

common만 해도 이해되는데, @ 라는 prefix가 더 붙는 친구들이 있나요?
@assets 나 이런것들이 또 있다면 이해가 되기도 한다만... 흠..

2021-06-06 07:50 UTC, Vallista commented on src/components/@shared/Header/Header.tsx
> +    <StyledHeader themeColor={API_INFO[apiOwner].themeColor}>
개인적으로 저는 아무리 안전하고 확정이 되어있다고 해도,

`API_INFO[apiOwner]`와 같은 문법을 굉장히 위험하다고 생각해요.
이 문법은 선언형으로 짜여져있는 코드 사이에, 명령형 코드라고 생각하거든요.

또한 의도치않게 올바른 값이 안들어가서 배열의 값이 달라진다면 undefined가 떨어질 것이며, undefined에는 .themeColor가 없으므로 해당 컴포넌트는 에러가나서 터질꺼에요. 그럼 어플리케이션 자체가 구동이 안될거구요.

그렇기 때문에 이러한 코드는 위에서 한 번 래핑을 해주던, 무언가가 필요해보이구요!
또한, 배열로 접근하는 방식을 전반적으로 사용하지 않았으면 좋겠습니다.

`API_INFO[apiOwner]?.themeColor ?? DefaultColor`

로 표현할 수도 있겠네요!

2021-06-06 07:50 UTC, Vallista commented on src/components/@shared/Header/Header.tsx
> +    <StyledHeader themeColor={API_INFO[apiOwner].themeColor}>
아니면 에러바운더리 같은걸 만들어서, 컴포넌트에 에러가 터졌을 때 대체로 보여줄 수 있는 컴포넌트를 만들면 좋겠습니다!

2021-06-06 07:50 UTC, Vallista commented on src/components/@shared/ButtonOnLine/ButtonOnLine.stories.js
> +import Add from '../../@common/Icon/Add';
@shared와 @common의 차이가 무엇인가용?

2021-06-06 07:50 UTC, Vallista commented on src/components/@shared/Main/Main.tsx
> +  width: 700px;
`width: 700px;` 보다는 `max-width: 700px; width: 100%;`를 주어서 반응형을 주는게 어떨지?

2021-06-06 07:50 UTC, Vallista commented on src/components/@shared/Navigation/Navigation.tsx
> +  navInfoList: Page[];
navInfoList인데 Page 배열... 흠 뭔가 좀 이상하지 않나용?
선언형 프로그래밍 방식에서 

```tsx
<Navigation  navInfoList={?? 페이지를 넣는 것을 생각할 수 있나요?} />
```

조금 더 맞는 이름으로 고민해보면 좋겠습니다!

2021-06-06 07:50 UTC, Vallista commented on src/components/@shared/SectionSelectBox/SectionSelectBox.styles.ts
> +export const SectionHiddenLabel = styled(HiddenLabel)``;
SectionHiddenLabal을 안쓰고 HiddenLabel을 써도 되지 않나용?

2021-06-06 07:50 UTC, Vallista commented on src/components/LinesModal/LineAddModal.tsx
> +  onClose: () => void;
모달 컴포넌트를 사용하는데, 모달 컴포넌트에서 onClose에 대한 상태를 은닉화를 못했다보니 여기까지도 dependency가 걸렸네요!
상태를 캡슐화 시키고, 여기서는 옵셔널 형태로 받던, LineAddModal 내에서 해결을 하던 하면 좋겠어요!

2021-06-06 07:50 UTC, Vallista commented on src/components/LinesModal/LineAddModal.tsx
> +  const usedLineColors = useMemo(() => lines.map((line) => line.color), [lines]);
좋네요!

2021-06-06 07:50 UTC, Vallista commented on src/components/LinesModal/LineAddModal.tsx
> +  const [nameInput, nameErrorMessage, onChangeName] = useNotificationInput(
요 NotificationInput을 Context API로 만들어서 안에 상태를 만든 후, Input 등 Validate Message가 필요한 부분을 해당 컨텍스트 레이어에서 상태 뽑아와서 사용하는 방법도 좋겠네요!

```tsx
<Context.provider>
  <Input ... /> // input 내부에서 Context.provider의 상태를 갖고와서 Input에 대한 예외가 있으면 그 값 트래킹
</Context.provider>
```

물론 지금 방식도 나쁘지 않습니다! (한 번 요렇게 구현 해보는 것도 좋아보여서~ 추천!)

2021-06-06 07:50 UTC, Vallista commented on src/components/LinesModal/LineAddModal.tsx
> +      if (targetValue.length >= 2 && isKoreanAndNumber(targetValue)) {
targetValue.length > 1 가 더 낫지 않을지!

2021-06-06 07:50 UTC, Vallista commented on src/components/LinesModal/LineAddModal.tsx
> +      if (targetValue === '' || downStationIdInput === '') {
```tsx
function isEmpty(...args: string[] = []) {
  return args.every(it => it === '')
}

if (isEmpty(targetValue, downStationIdInput)) {
```

요런 형태는 어떠세요?

2021-06-06 07:50 UTC, Vallista commented on src/components/LinesModal/LineAddModal.tsx
> +  });
여기엔 dependencies array가 없군요!?

2021-06-06 07:50 UTC, Vallista commented on src/components/LinesModal/LineModifyModal.tsx
> +          message={{ text: nameErrorMessage, isError: true }}
선언형으로 볼 때, message가 object라는걸 추측하기가 어렵네요 ㅠ
messageInfo? 뭐 이정도가 더 낫지 않을지!?

2021-06-06 07:50 UTC, Vallista commented on src/constants/api.ts
> +export const API_INFO: { [key: string]: APIInfo } = {
이런 방법을 선호하진 않지만 (선호하지 않는 이유는 위에서 이야기했슴니다!), 한다면

```tsx
type ApiHostType = 'FAFI' | 'JOEL' | 'JOAN' | 'JAYON';

interface APIInfo {
  name: string;
  endPoint: string;
  themeColor: Color;
}

export const API_INFO: Record<ApiHostType,  APIInfo> = {
```

2021-06-06 07:50 UTC, Vallista commented on src/constants/css.ts
> +  HEADER: 9,
조금 더 벌리면 어떨까요?
MODAL: 100 정도로?

2021-06-06 07:50 UTC, Vallista commented on src/constants/palette.ts
> +const PALETTE: { [key: string]: Color } = {
color와 pallete는 분리할 이유가 없으며, 억지로 분리를 했기 때문에 오히려 두 군데 수정이 필요해졌어요. 또한 200,600,700은 없는 케이스도 있기 때문에 optional이 되어버렸구요!

```tsx
enum Color {
  BLACK_300 =  '#444444'
  ...
}
```

이렇게 하면 간단한데 왜 모두 요 Color와 Palette를 분리하는 방식으로 코딩하는걸까요..?

2021-06-06 07:50 UTC, Vallista commented on src/constants/palette.ts
> +const PALETTE: { [key: string]: Color } = {
그리고 만약 이렇게 사용한다 하더라도, 사용처에서는 `Color: string`으로 쓰고 있더라구요... 그럼 의미가 없습니다. 오타나 다른 상황에 의해 좌우되는게 있을 것이며, 명확한 타입 대신으로 사용할만한 무언가가 있어야 해요~

그런데 `type PALETTE`는 제약할 수 있는 타입 형태로 되질 않으니,,, enum을 사용하는걸 추천드립니다.

2021-06-06 07:50 UTC, Vallista commented on src/constants/storage.ts
> +export const SESSION_STORAGE_KEY: { [key: string]: string } = {
`: Record<string, string>`

utility type을 적극적으로 사용합시다아~

2021-06-06 07:50 UTC, Vallista commented on src/hooks/useInput/useInput.ts
> +const useInput = <T extends BaseInputElement = HTMLInputElement>(
굿

2021-06-06 07:50 UTC, Vallista commented on src/hooks/useInput/useInput.ts
> +const useInput = <T extends BaseInputElement = HTMLInputElement>(
default value도 가져오는 로직이 있으면 좋겠네여

2021-06-06 07:50 UTC, Vallista commented on src/hooks/useModal/useModal.ts
> +const useModal = (initModalData?: unknown): UseModal => {
무엇을 표현하고 싶었던 코드일까요??

2021-06-06 07:50 UTC, Vallista commented on src/hooks/useModal/useModal.ts
> +const useModal = (initModalData?: unknown): UseModal => {
아무 타입이나 들어올 수 있는건 위험하지 않을까요? 어떤 제약을 좀 주어야..?
전반적으로 모달에 대해서 처리가 느슨하네요!

또한 중복되는 코드도 많구요 (노선, 수정, 삭제 등 모달들이)

2021-06-06 07:50 UTC, Vallista commented on src/hooks/useModal/useModal.ts
> +const useModal = (initModalData?: unknown): UseModal => {
어떻게하면 hooks로 공통로직을 뺄 수 있을지, Modal에서 레이아웃을 대다수 커버할 수 있을 지 고민해보면 좋겠어요!

2021-06-06 07:50 UTC, Vallista commented on src/hooks/useModal/useModal.ts
> +const useModal = (initModalData?: unknown): UseModal => {
너무 큰 자유도를 주고 있는 걸로 보여요!

2021-06-06 07:50 UTC, Vallista commented on src/hooks/useNotificationInput/useNotificationInput.ts
> +interface OnChangeTool {
OnChangeTool을 interface로 하니 무언가 이상하네요..

ChangeToolParameter ? 이런 느낌이 더 낫지 않을지..?

2021-06-06 07:50 UTC, Vallista commented on src/hooks/useNotificationInput/useNotificationInput.ts
> +const useNotificationInput = <T extends BaseInputElement = HTMLInputElement>(
BaseInputElement에서 Extends HTMLInputElement를 하는것은 별로인가요?

2021-06-06 07:50 UTC, Vallista commented on src/hooks/useNotificationInput/useNotificationInput.ts
> +  onChangeAdditionalDependencyList?: React.DependencyList | undefined
onChangeAdditionalDependencyList?: React.DependencyList 만 해도 괜찮지 않을까요?

[TypeScript 4.4](https://github.com/microsoft/TypeScript/issues/44237) 에 대한 대응일까요?

2021-06-06 07:50 UTC, Vallista commented on src/pages/Login/Login.tsx
> +  const onLogin: FormEventHandler<HTMLFormElement> = async (event) => {
로그인 하는 것도 hooks로 빼보면 어떨까요?

try-catch로 어떤 로직이 일어나는지 레이아웃 코드에서 굳이 안보아도 될 것 같네요!
비즈니스 분리의 차원으로 ㅎㅎ

2021-06-11 14:57 UTC, 0307kwon reviewed
안녕하세요 발리스타님! 미키입니다 ㅎㅎ
어제 발리스타 님을 볼 수 있어서 너무 반가웠습니다 😊
이번 미션에서 모달 부분이 잘 이해가 안가서 어제 여쭤보았었는데요
사실 잘 이해가 안되었습니다...... ㅠㅜ 😭
그래서 **모달 부분에 대한 질문**과 **Form을 context API로 만들어본 것**
두가지가 피드백에 관한 가장 큰 질문입니다!
그 동안 정말 감사했습니다!! 🧡

## 피드백 관련 질문

[모달 관련 질문1](https://github.com/woowacourse/react-subway-map/pull/21#discussion_r646074716)
[모달 관련 질문2](https://github.com/woowacourse/react-subway-map/pull/21#discussion_r646083769)
[@를 붙이므로써 더 의미가 강조되는게 있을까요?](https://github.com/woowacourse/react-subway-map/pull/21#discussion_r646075654)
[Form을 context API로 구현](https://github.com/woowacourse/react-subway-map/pull/21#discussion_r646078280)

## 추가적인 질문

요즘 에러 핸들링을 어디서 해야하는 지 고민이 많습니다!
계속 코드를 짜면서도 에러 핸들링 코드가 너무 분산되는 느낌이 듭니다
고민을 하면서 스스로 생각해보았을 때
보통 fetch와 같은 비동기 요청에서 try catch로 핸들링 하는 경우가 많으므로
API 레이어에서 에러 핸들링을 마치고 추가적인 사이드 이펙트를 막아 최대한 정상 동작 시켜야한다고 생각합니다
그리고 나머지 에러들은 에러바운더리에서 한번에 핸들링하여
화면을 모두 날려버리지 않고, 준비된 화면을 보여주는 것이 맞지 않을까...? 라고 생각합니다!

보통 에러 핸들링은 어디서 처리를 해주는 것이 좋을까요?
발리스타님의 의견이 궁금합니다! 😁

2021-06-11 14:57 UTC, 0307kwon commented on .storybook/main.js
> +}
엇 저장하면 자동으로 마지막에 개행을 넣도록 설정하였는데 어떻게 들어갔을까용 ㅠㅜ 감사합니다!

2021-06-11 14:57 UTC, 0307kwon commented on package.json
> +    "web-vitals": "^1.0.1"
헙...! 모르는 라이브러리인데 언제 들어갔을까용....ㅠㅜ package.json을 잘 확인하도록 하겠습니다! 😭

2021-06-11 14:57 UTC, 0307kwon commented on src/App.tsx
> +axios.defaults.baseURL = API_INFO[getApiOwner()].endPoint;
하나의 도메인에서 관리할 방법을 고민하다가 axios instance를 활용해 유틸로 처리했습니다! 😁

2021-06-11 14:57 UTC, 0307kwon commented on src/App.tsx
> +const App: FC = () => {
이 부분에 대해서 payments 미션에서 제이비님과 토론하시는 것을 본 적이 있습니다!
사실 그 당시에는 깊게 생각하지 않고 판단하기에
VFC는 deprecated 될 것이기 때문에 모두 FC를 사용하되 children이 있는 경우에는
명확하게 children에 대한 타이핑을 오버라이드 하면 되지 않을까? 라고 결론을 내었습니다.

하지만 지금에 와서는 FC와 VFC 모두 의도된 것이 아니라 호환성을 위해 임시로 남겨 둔 것이기 때문에
FC 타입을 쓸 것이라면 VFC도 같이 써주고
FC 타입을 쓰지 않을 것이라면 VFC도 쓰지 않는 것이 더 올바른 사용방법이라는 생각이 드네요! 😁
(찾아보니 코드에서 FC 타입을 지워주는 [라이브러리](https://github.com/gndelia/codemod-replace-react-fc-typescript)도 존재하네요! )
또한 VFC 타입을 쓰지 않으면 의도치 않게 children을 넣는 경우도 있을 것 같습니다.


FC와 VFC, 이 부분은 좀 미묘한 부분이라 판단하기가 쉽지 않은 것 같습니다 ㅠㅠ 😭
우선은 FC를 사용하고 있으니 VFC도 같이 사용해주도록 하겠습니다! 👍

2021-06-11 14:57 UTC, 0307kwon commented on src/App.tsx
> +    axios.defaults.baseURL = API_INFO[apiOwner].endPoint;
감사합니다! 수정하였습니다 👍

2021-06-11 14:57 UTC, 0307kwon commented on src/constants/palette.ts
> +const PALETTE: { [key: string]: Color } = {
typescript에 enum이 있다는 것을 알고만 있었지 지금까지 어떻게 사용하는지는 정확히 모르고 있었습니다.
아직 typescript를 도입한지 얼마 안되어 충분히 학습할 시간이 부족했던 것 같습니다 ㅠㅜ
enum을 도입하는 다른 크루들을 보면서 왜 사용하는지 확실히 감이 잡히지 않았는데
enum member가 모두 리터럴인 경우 타입으로도 활용할 수 있군요! 👍👍

또한 enum의 다른 스펙을 추가적으로 학습하면서
지금까지 해오던 객체 리터럴 상수화의 상위 호환이라는 생각이 듭니다!
방학 기간 동안 조금 숨을 돌리면서 레벨 2 동안 미뤄왔던 공부들을 하니 정리가 되는 느낌입니다 😁

제가 미션 진행하면서 매우 원했던 기능입니다!! 확실히 겪으면서 필요성을 느끼니 굉장히 와닿네요!
감사합니다!!! 🧡

2021-06-11 14:57 UTC, 0307kwon commented on src/App.tsx
> +      <Header title={APP_TITLE} logo={<Subway color={PALETTE.BLACK[400]} />}>
확실히 배열로 접근하는 방식이 키 값으로 너무 많은 자유도를 주기 때문에 실수할 수 있는 여지가 더 많은 것 같습니다!
이번에 배열 방식에 대해 다시 한번 생각해보게 되네요! 감사합니닷!!! 👍👍🧡

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@common/Button/Button.tsx
> +Button.propTypes = {
typescript는 정적 타입 검사, propTypes는 동적 타입 검사를 수행한다는 사실을 이론적으로는 알고 있었지만
실제로는 어떤 상황에서 typescript가 타입 검사를 하지 않는지 잘 모르고 있었습니다.

그런데 얼마 전 쇼핑카트 미션의 피드백을 반영하면서 런타임에서 서버로부터 받아오는 response 같은 값들이 typescript로 타입 검사가 전혀되지 않는 것을 실제로 경험하고, 
정적과 동적 타입 검사의 차이점을 확연히 느꼈습니다😁

여러가지 기술을 사용하면서 내재화가 제대로 되어있지 않았었다는 생각이 드는 요즘입니다 ㅠㅜ
확실히 이 부분 같은 경우에는 컴파일 타임에서 타입 검사가 모두 가능한 부분이네요!
따끔한 피드백 감사합니다! 👍👍👍

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@common/CardTemplate/CardTemplate.tsx
> +CardTemplate.propTypes = {
필요 없는 것 같습니다! 감사합니닷 🧡

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@common/Icon/Add.tsx
> +  width?: string;
헉! 작성하면서는 느끼지 못한 부분이었습니다! 날카로운 피드백 감사합니닷!! 😁👍👍

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@common/CardTemplate/CardTemplate.styles.ts
> +const TITLE_SIZE = {
확실히 그렇네요! enum을 알고나니 시야가 넓어지는 것 같습니다!! 감사합니다!  👍👍

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@common/CardTemplate/CardTemplate.styles.ts
> +export const CardTemplateTitle = styled.div``;
styled component도 기반은 css니 이런 방식이 가능한 것은 어찌보면 당연하네요!
너무 styled component 방식으로만 생각하려고 했던 것 같습니다! 의미없는 component가 하나 사라져서 좋네요!
감사합니다! 🧡

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@common/CardTemplate/CardTemplate.tsx
> +  templateColor?: string;
확실히 명확히 타이핑을 해주는 것이 더 좋은 것 같습니다! 감사합니다 😁

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@common/NotificationInput/NotificationInput.styles.ts
> +    content: ${({ isError }) => (isError ? '"🚫 "' : '"✅ "')};
이모지가 브라우저와 OS에 따라 다르게 보일 수 있고, 호환되지 않을 수도 있다는 것을 은연 중에 알고는 있었지만
크게 염두에 두지는 않았던 것 같습니다! 링크에 설명이 굉장히 잘 되어있네요!
앞으로 이모지를 사용하면서 크로스 브라우징 이슈를 좀 더 고민하겠습니다! 
감사합니다 ㅎㅎ 😊

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@shared/ButtonOnLine/ButtonOnLine.stories.js
> +import Add from '../../@common/Icon/Add';
>@를 붙이므로써 더 의미가 강조되는게 있을까요?
common이나 @common이나 의미가 별 다른게 없어보여서요!

저희가 @를 붙인 이유는 공통적으로 사용되는 컴포넌트들이라 폴더 구조 상에서 가장 위로 끌어올려
폴더를 열었을때 가장 먼저 확인할 수 있도록 하고 싶었습니다!

> @shared와 @common의 차이가 무엇인가용?

shared는 저희 앱에서만 공통적으로 쓰이는 컴포넌트이고
common은 다른 어떤 앱에서든 사용할 수 있는 컴포넌트들을 의미합니다!
저도 처음에는 두 폴더를 나누는 것이 조금 의아했지만
쓰다보니 이전 프로젝트에서 재활용할 수 있는 컴포넌트들을 common폴더에서 확인하고
다음 프로젝트로 가져와 사용하는데에는 조금 더 편리할 수 있겠다는 생각이 들었습니다!
오히려 혼란을 줄 수 있는 폴더 구조일까요?! 🙋‍♂️

2021-06-11 14:57 UTC, 0307kwon commented on src/components/LinesModal/LineAddModal.tsx
> +      if (targetValue === '' || downStationIdInput === '') {
조금 변형하여 사용해보았습니다! 감사합니다! 🧡

``` ts
export const hasEmptyString = (...args: string[]): boolean => args.some((it) => it === '');
```

2021-06-11 14:57 UTC, 0307kwon commented on src/components/LinesModal/LineModifyModal.tsx
> +          message={{ text: nameErrorMessage, isError: true }}
헙 확실히 message가 string 같은 느낌이 있네요!
코딩하다보면 이런 것을 느끼기가 쉽지 않은 것 같습니다ㅠㅜ
3자의 시각으로 계속 보는 연습을 해야겠군용....! 감사합니다! 😁

2021-06-11 14:57 UTC, 0307kwon commented on src/hooks/useNotificationInput/useNotificationInput.ts
> +interface OnChangeTool {
저도 이제보니 말로하기 어려운 미묘한 이상함이 느껴지네요 ㅋㅋㅋㅋㅋ
수정하였습니다! 👍

2021-06-11 14:57 UTC, 0307kwon commented on src/hooks/useNotificationInput/useNotificationInput.ts
> +const useNotificationInput = <T extends BaseInputElement = HTMLInputElement>(
이 부분은 사실 저도 처음에는 `Extends HTMLInputElement` 방식을 사용하였지만
useNotificationInput이 selectBox에도 사용되고 있기 때문에
제네릭으로 HTMLSelectElement를 넣어주어야하는 상황이 발생하여 이런 방식으로 사용하고 있습니다!

2021-06-11 14:57 UTC, 0307kwon commented on src/hooks/useNotificationInput/useNotificationInput.ts
> +  onChangeAdditionalDependencyList?: React.DependencyList | undefined
헙 옵셔널인데 왜 undefined를 넣어주었을까용... 지금은 확실히 필요 없는 코드 같습니다! 감사합니다 ㅎㅎ

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@common/Modal/Modal.tsx
> +  onClose: () => void;
이 부분에 대해서 잘 이해되지 않는 부분이 있어 질문드립니다! 🙋‍♂️
현재 저의 코드에서는 isModalOpen 상태를 통해 Page가 모달의 open, close 여부를 모두 관리하고 있습니다!

그래서 Modal 컴포넌트가 외부 이벤트에 종속되지 않으려면 isModalOpen이라는 상태를
Modal 컴포넌트 안에서 관리해야할 것 같다는 생각이 듭니다! 하지만 이렇게 하면 외부에서 모달을 열 방법이 없는 것 같습니다 ㅠㅜ 😭

그래서 이 부분에 대해서 계속 고민을 해봤지만
제 생각에 외부의 이벤트로 모달이 열리는 모달의 특성 상 모달이 외부에 어느정도 종속되는 것은 불가피하다고 생각됩니다! 그래서 저는 모달을 닫아주는 onClose 함수는 있어야한다고 생각합니다.

혹시 제가 잘못 이해한 부분이 있을까요?! 이 부분에 대해서 조금 더 자세히 말씀해주시면 감사하겠습니다!

2021-06-11 14:57 UTC, 0307kwon commented on src/constants/api.ts
> +export const API_INFO: { [key: string]: APIInfo } = {
헉 이렇게 간단하게 할 수 있었군용....! 🧡
[타입스크립트 핸드북](https://www.typescriptlang.org/docs/handbook/utility-types.html)을 보니 굉장히 다양한 유틸리티 타입이 있네요! 좀 더 공부하도록 하겠습니닷...! 🔥

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@shared/Header/Header.tsx
> +    <StyledHeader themeColor={API_INFO[apiOwner].themeColor}>
확실히 개발자 입장에서는 api owner보다는 api Info에 관심이 있을 테니 
이런 방식은 명령형 코드에 가깝다고 볼 수 있겠네요!
useCurrentAPIInfo 라는 커스텀 훅으로 한번 래핑해서 API 정보만 뽑아 사용할 수 있도록 선언적으로 변경하였습니다!
감사합니다! 😁

2021-06-11 14:57 UTC, 0307kwon commented on src/components/@shared/Navigation/Navigation.tsx
> +  navInfoList: Page[];
지금보니` navInfoList?? 네비게이션 정보 목록이 뭐지??` 라는 생각이 듭니다!
navigatingPageInfoList 정도로 바꿔 주었습니다! 감사합니다 ㅎㅎ 😁

2021-06-11 14:57 UTC, 0307kwon commented on src/hooks/useModal/useModal.ts
> +const useModal = (initModalData?: unknown): UseModal => {
Page에서 Modal을 관리하고 있어 Page와 Modal을 연결해주기 위한 훅이었습니다!
Page에서 Modal을 사용할 때마다 공통적으로 isModalOpen 상태가 있고,
Modal을 열고 닫는 메서드가 있고, 모달로 가끔 데이터를 보내야할 일이 있어
(LineAddModal에서 targetLine을 넘겨주어야할때)
이렇게 사용하고 있습니다!

앞서 피드백 주신 Modal의 onClose 문제와 같은 결으로 보입니다 
아직 저에게는 이해하기 어려운 부분인 것 같아용 ㅠㅜ 😭
이 부분에 대해 좀 더 자세히 여쭤봐도 될까요?! 🙋‍♂️

\+ unknown 부분에 대해서는 제네릭으로 처리 했습니다!

2021-06-11 14:57 UTC, 0307kwon commented on src/components/LinesModal/LineAddModal.tsx
> +  onClose: () => void;
ㅠㅜ 다른 모달 관련 피드백과 같은 맥락이군용... 다른 피드백에 질문드렸습니다! 😭

2021-06-11 14:57 UTC, 0307kwon commented on src/pages/Login/Login.tsx
> +  const onLogin: FormEventHandler<HTMLFormElement> = async (event) => {
어디서부터 어디까지 빼는 것이 좋을까 고민을 하다가 정말 최소한만 page에 남기고
모두 hooks/service 레이어로 빼주었습니다! 
이렇게 하니 페이지에서는 마크업만이 남았고 service 레이어에서는 비즈니스 로직이 모두 들어가게 되어
좀 더 명확한 분리가 이루어지는 것 같았습니다.

이러한 방식으로 시도하는 것이 좋은 방향일까요?! 궁금합니다! 🙋‍♂️

2021-06-11 14:57 UTC, 0307kwon commented on src/components/LinesModal/LineAddModal.tsx
> +  const [nameInput, nameErrorMessage, onChangeName] = useNotificationInput(
form을 컨텍스트 API로 두고 children input에서 가져다 쓰는 방식으로 활용해보았습니다!
쉽지 않네용 ㅠㅜ 어떻게하면 편하게 사용할 수 있을까 계속 고민해보았습니다!
의도하신 방향이 맞을까요?! 궁금합니닷! 🙋‍♂️

관련 커밋 : https://github.com/woowacourse/react-subway-map/pull/21/commits/b46166b010703f4ca2f00f61a1c2dc894c50c37b

2021-06-11 14:57 UTC, 0307kwon commented on src/api/lines.ts
> +export const requestGetLines = (): Promise<AxiosResponse<Line[]>> => axios.get(`/lines`);
사용하는 쪽에서 신경을 쓰지 않아도 되겠군요! 적용해보았습니다 ㅎㅎ 감사합니다! 👍👍👍

2021-06-11 17:12 UTC, Vallista commented on src/pages/Login/Login.tsx
> +  const onLogin: FormEventHandler<HTMLFormElement> = async (event) => {
넹 굿!

2021-06-11 17:13 UTC, Vallista commented on src/components/@shared/ButtonOnLine/ButtonOnLine.stories.js
> +import Add from '../../@common/Icon/Add';
아뇨... 미키님과 페어가 좋았다면, 저도 좋습니다 :)

2021-06-11 17:14 UTC, Vallista commented on src/components/LinesModal/LineAddModal.tsx
> +  const [nameInput, nameErrorMessage, onChangeName] = useNotificationInput(
조금 더 연습해보시면 좋겠습니다~

2021-06-11 17:14 UTC, Vallista commented on src/components/LinesModal/LineAddModal.tsx
> +  const [nameInput, nameErrorMessage, onChangeName] = useNotificationInput(
계속 막 빼보세요~ 그러다 어느 경지에 올 듯!

2021-06-13 07:42 UTC, Vallista commented
일단 미키, 

```
Page에서 Modal을 관리하고 있어 Page와 Modal을 연결해주기 위한 훅이었습니다!
Page에서 Modal을 사용할 때마다 공통적으로 isModalOpen 상태가 있고,
Modal을 열고 닫는 메서드가 있고, 모달로 가끔 데이터를 보내야할 일이 있어
(LineAddModal에서 targetLine을 넘겨주어야할때)
이렇게 사용하고 있습니다!

앞서 피드백 주신 Modal의 onClose 문제와 같은 결으로 보입니다
아직 저에게는 이해하기 어려운 부분인 것 같아용 ㅠㅜ 😭
이 부분에 대해 좀 더 자세히 여쭤봐도 될까요?! 🙋‍♂️

+ unknown 부분에 대해서는 제네릭으로 처리 했습니다!
```

요 답변에는 답변 안할께여! 스스로 알아보시길 권합니다... ㅋㅋ
이 것을 깨달으려면, onClose를 쓰고/안쓰고 시점에서 개발해보세요.
그리고 객체란 무엇이고 컴포넌트란 무엇인가?를 조금 더 고민해보시길 권합니다!

매일 바로 답을 줬지만, 만나서 설명했음에도 이해를 못했다는것은! 그 외적인 지식이 부족하다는 뜻입니다!!
그렇기 때문에 그 과정에서 지식을 얻을수 있을거라 생각합니다 👍 

홧팅

2021-06-15 15:44 UTC, 0307kwon commented
@Vallista 발리스타님 마지막 피드백 감사합니다!
컴포넌트는 독립적으로 실행이 가능한 모듈이고 onClose에 의해 다른 컴포넌트에 종속되면 
캡슐화에 있어서 좋지 않고 재사용성이 떨어진다는 것을 알게되었습니다!
객체 지향과 컴포넌트에 대해서 어느정도 알고 있다고 생각하고 있었는데 다시 공부를 해보니 모르는 내용이 많았습니다!
좀 더 기본에 충실할 수 있도록 하겠습니다 ㅎㅎ

또한 onClose는 없어야 된다는 것은 이해가 갔지만 어떻게 구현해야하는가에 대해 고민이 많았습니다!
그런데 최근에 form을 context api로 구현해보라고 하신 발리스타님의 피드백을 보고
모달도 context api로 만들 수 있지 않을까? 라는 생각을 하였고, 이를 context api로 만들었더니 
이제야 모달이 독립적인 컴포넌트의 모습으로 구현되었습니다. 
이전에 필요없는 isModalOpen을 각 page마다 선언하고 이 때문에 page에 모달이 종속되는 형태보다
훨씬 깔끔하고 재사용성이 높은 형태인 것 같습니다. 감사합니다! 👍👍

이번에 context api의 역할이 그저 다크모드나 언어 선택 기능 정도에 국한되는 것은 아니라는 것을 알게되었습니다.
context api의 활용에 대해 더 넓은 시야를 가지게 된 것 같습니다! ㅎㅎ 감사합니다 😁

혹시 이제 다음 단계로 넘어가도 괜찮을까용....? 😊

2021-06-19 04:03 UTC, Vallista commented
고고!

2021-06-19 04:04 UTC, merged

2021-06-21 16:29 UTC, 0307kwon commented
# 학습로그

## [테스트]{컴포넌트 테스트와 E2E 테스트의 차이점} - 4/5

### 내용

**컴포넌트 테스트와 E2E 테스트가 헷갈렸던 경험**

page 컴포넌트 단위로 테스트를 진행하면서 page 중에서도 signup 페이지를 테스트하면서
`signup 페이지도 결국에는 사용자의 input을 받고, submit 버튼을 누르면 적절한 결과를 보여주는 점에서 E2E테스트와 다른 점이 없지 않나?` 라는 생각이 들었다.

**컴포넌트 테스트 vs E2E 테스트**

컴포넌트 테스트와 E2E 테스트의 가장 큰 차이점은 `관점` 의 차이이다.
컴포넌트 테스트는 독립적인 `컴포넌트의 관점`에서 외부 요인과 관계없이 어떤 결과를 기대할 수 있는가를 테스트하는 것이고
E2E 테스트는 철저히 `사용자의 관점`에서 세워진 시나리오 하에서
어떠한 결과를 기대할 수 있는지에 대한 테스트이다. 
(따라서 여러 컴포넌트에 걸쳐 테스트하여도 상관 x)

**+컴포넌트에서의 단위 테스트와 통합 테스트**

리액트 공식 문서에서 말하는 컴포넌트 테스트는 단위 테스트와 통합 테스트의 구분이 명확하지 않다고 한다.
예를 들어 form 컴포넌트에 대한 테스트를 작성한다고 가정했을 때

form 내부의 button 컴포넌트도 같이 테스트해야하는 것인가?
아니면 button 컴포넌트에 적합한 테스트를 따로 작성해야하는 것인가?

이러한 질문에 대한 답은 팀마다 다를 수 있지만, 어떤 답을 도출하느냐에 따라서
컴포넌트 테스트가 어떤 테스트의 성격을 띄는지가 달라진다.
따라서 컴포넌트 테스트는 단위 테스트와 통합 테스트가 혼재되어 있다고 볼수 있다.

✨ 유닛 테스트

로직을 가진 단일한 함수, 클래스 또는 객체에 대한 테스트. 

✨ 통합 테스트

여러개의 유닛이 다른 유닛과 통합되는 과정에서 일어나는 일에 대한 테스트

### 링크

[https://reactjs.org/docs/testing.html](https://reactjs.org/docs/testing.html)
[https://kentcdodds.com/blog/the-testing-trophy-and-testing-classifications](https://kentcdodds.com/blog/the-testing-trophy-and-testing-classifications)

## [리액트]{객체 vs 컴포넌트} - 4/5

### 내용

객체와 컴포넌트. 같은 것이라 생각할 수 있지만 엄연히 다른 개념이다.

- 객체

    하나의 `클래스`를 통해 `실체화`된 `데이터와 메소드의 모음`이다.
    메소드를 통해 외부와 상호작용 할 수 있으며 객체 지향 프로그래밍에서
    코드를 이루는 가장 작은 단위가 된다.
    자동차로 예를 든다면 작은 나사로 예를 들 수 있다.

- 컴포넌트

    `독립적`으로 배포될 수 있고 `조립/교환`이 가능한 `응집도`가 높은 단위 모듈.
    많은 객체들로 구성되어 있다.
    많은 나사들과 엔진 등으로 이루어진 자동차를 컴포넌트의 예로 들 수 있다. 

### 링크

[https://www.geeksforgeeks.org/difference-between-component-and-object/](https://www.geeksforgeeks.org/difference-between-component-and-object/)

[https://mckdh.tistory.com/entry/객체지향의-탄생-객체와-컴포넌트-아키첵처와-아키텍트](https://mckdh.tistory.com/entry/%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5%EC%9D%98-%ED%83%84%EC%83%9D-%EA%B0%9D%EC%B2%B4%EC%99%80-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EC%95%84%ED%82%A4%EC%B2%B5%EC%B2%98%EC%99%80-%EC%95%84%ED%82%A4%ED%85%8D%ED%8A%B8)

## [js]{객체 지향 프로그래밍} - 5/5

### 내용

- 객체 지향 프로그래밍 (Object-Oriented Promgramming)
    프로그램을 단순히 코드의 나열로만 봤던 시각을 벗어나
    프로그램을 `객체` 라는 기본 단위로 나누고 객체들 간의 상호 작용으로 문제를 해결하는 방식
    독립성이 높은 객체들을 작은 단위부터 만들고, 그 작은 단위들을 재사용해가며 더 큰 객체들을
    만드는 방식으로, 상향식(Bottom-up) 방식이라고 할 수 있다.
    (Top-down 방식은 객체 지향 이전의 구조적 프로그래밍 방식이라고 볼 수 있다.)

- 객체 지향 프로그래밍의 구성 요소
    - 클래스
        같은 종류의 문제 해결을 위한 속성과 기능을 정의한 것.
        외부 요소와 독립적이고 추상적으로 만들어져야 한다.
        객체 지향 프로그래밍에서의 기본적인 설계도라고 할 수 있다.

    - 객체
        클래스라는 설계도를 통해 만들어진 실체라고 할 수 있다.
        객체는 자신 고유의 속성을 가지며 클래스로부터 만들어진 기능을 사용할 수 있다.

    - 메서드, 메시지
        클래스 내부에 정의된 함수를 메서드라고 한다.
        개발자는 클래스를 통해 객체를 생성하고 
        객체의 외부로 공개된 메서드를 통해 해당 객체에 명령을 내릴 수 있는데 이렇게 메서드를 사용하는 행위를 메시지를 보낸다고도 할 수 있다. 

- 객체 지향 프로그래밍의 특징
    1. 캡슐화
        특정 모듈의 세부 구현을 감추고 외부로의 노출을 최소화하여 
        모듈의 `응집도`를 높이고 모듈 간의 의존도를 떨어뜨려
        재사용할 수 있는 모듈으로 만드는 것.
        정보은닉과 `추상화`의 개념이 녹아있다고 생각하면 된다.

        ✨ 추상화 : 상세한 구현은 드러내지 않고 중요한 개념만 외부로 드러내는 것.

        ✨ 응집도 : 모듈의 요소들이 같이 속하는 정도를 의미한다.
        클래스의 목적을 나타낸 속성과 기능이 얼마나 서로 강하게 관계되어 있는지 측정하는 요소이다.

    2. 상속
        자식 클래스가 부모 클래스의 기능을 그대로 물려받는 것을 의미.
        자식 클래스는 부모 클래스의 기능을 물려받으며
        새로운 기능을 추가하거나
        기존에 부모 클래스가 가진 기능을 일부 수정하는 등(오버라이딩)
        캡슐화를 유지하면서 개념을 확장시킬 수 있다.

    3. 다형성
        클래스 상속 구조 내, 같은 이름의 메소드를 사용하더라도 맥락에 따라 다른 기능을 수행하는 것을 의미한다.
        예를 들어 단형성(다형성의 반대) 체계를 가진 프로그래밍 언어에서는
        다음과 같이 구현할 수 있다.

        ```jsx
        //숫자를 문자열로 바꾸는 경우
        string = StringFromNumber(number);

        //날짜를 문자열로 바꾸는 경우
        string = StringFromDate(date);
        ```

        하지만 다형성 체계를 가진 프로그래밍 언어에서는 똑같은 메소드 이름으로 구현할 수 있다.

        ```
        //숫자를 문자열로 바꾸는 경우
        string = number.StringValue();

        //날짜를 문자열로 바꾸는 경우
        string = date.StringValue();
        ```

        이렇듯 객체의 타입과 상관없이 외부에서 객체의 메소드를 사용함에 있어 추상도가 높은 형식으로 구현할 수 있다.
        자바스크립트에서는 오버라이딩만 구현되어있고 오버 로딩은 불가하나 타입스크립트로 오버 로딩을 구현할 수 있어 이를 보완할 수 있다.

## [js]{객체 지향 프로그래밍을 잘 하기 위한 5원칙 (SOLID)} - 5/5

- SOLID란?
    소프트웨어 디자인을 더 이해하기 쉽고, 유연하고, 유지보수하기 좋은 형태로 만들기 위한 5가지의 디자인 원칙들의 앞 글자를 따 기억하기 쉽도록 만든 것.

- S.O.L.I.D
    - Single-responsibility principle : 단일 책임 원칙
        클래스는 오직 하나의 액터에 대한 책임만을 가진다.

        여기서 액터는 같은 방향으로 클래스가 변화하기를 요구하는 이해관계자나 사용자 그룹을 의미한다.
        예를 들어 철수는 스마트폰을 동영상 재생을 위해 사용하고, 영희는 전화를 위해 사용한다면
        철수와 영희는 스마트폰이 각자 다른 방식으로 변하기를 바랄 것이다.
        철수는 동영상 감상을 위해 스마트폰이 더 커지길 원할 것이고
        영희는 전화 품질이 더 높아지길 원할 것이다.

        이렇게 되면 철수와 영희는 별개의 액터로 볼 수 있고,
        스마트폰이 두 액터 모두에게 책임을 가진다면 이는 단일 책임 원칙을 위반한다고 할 수 있다.
        따라서 단일 책임 원칙은 해당 클래스 내부 구현에만 관심을 가지는 것이 아니라
        해당 클래스를 사용하는 입장에서 바라보는 원칙이라고 할 수 있다. 

        [참고1]([https://www.e4developer.com/2018/10/04/single-responsibility-principle-do-you-know-the-real-one/](https://www.e4developer.com/2018/10/04/single-responsibility-principle-do-you-know-the-real-one/))

        [참고2]([https://siyoon210.tistory.com/155](https://siyoon210.tistory.com/155))

    - Open-Closed Principle : 개방-폐쇄 원칙
        클래스는 확장에 대해서는 개방적이고 수정에 대해서는 폐쇄적이어야한다는 원칙이다.
        
        예를 들어 Animal이라는 클래스를 상속받는 Cat 클래스와 Chicken 클래스가 있다.
        Cat과 Chicken은 Animal의 walk 메서드를 물려받지만
        두 동물의 걷는 방식은 다르다. 하지만 Cat이 Chicken과
        걷는 방식이 다르다고 해서 Animal 클래스의 walk 메서드를 수정할 필요는 없다. 그저 Animal 클래스를 확장하여 walk 메서드만 재정의하면 된다.

        이를 보고 확장에 의한 재정의에는 개방적이고
        수정에 대해서는 폐쇄적이라고 한다.

    - Liskov Substitution Principle : 리스코프 치환 원칙
        자식 클래스는 언제나 부모 클래스를 대체할 수 있어야한다는 원칙이다.
        
        이를 지키지 못하면 부모 클래스가 가진 메서드를 자식 클래스가 가지지 않는다는 것이므로 자식 클래스가 부모 클래스와 다르게 변질되고 객체 지향이 가지는 상속의 특징도 잃게 된다.

    - Interface segregation principle: 인터페이스 분리 원칙
        클라이언트에서 필요하지 않는 요소를 구현하도록 강요하거나 사용하지 않는 요소에 의존하도록 만들어서는 안된다는 원칙이다.
        
        ISP는 `일반적인 목적의 인터페이스 하나보다 클라이언트에 특화된 많은 인터페이스`를 만들어 하나의 클래스의 목적에 맞지 않는 요소를 없애고 응집도를 높이기 위한 목적을 가지고 있다.
        이전의 예시와 같이 Animal 클래스를 상속받는 Cat과 Chicken 클래스를 만들고 Animal에 fly() 메서드를 정의한다고 가정해보자.
        이렇게 만들면 Cat은 날 수 없으므로 fly() 메서드를 오버라이딩하여 비워주어야할 것이다.
        그런데 Cat은 fly() 메서드를 가지고는 있으므로 메서드 호출은 가능할 것이다. 이렇게 만드는 방식은 Cat이 필요없는 메서드가 내부에 정의됨으로써 응집도를 떨어뜨린다.

        따라서 fly()메서드는 Animal 클래스에서 정의하는 것이 아니라
        좀 더 fly() 메서드가 어울리는 Chicken 클래스에서 정의하여 응집도를 높여야한다.

        ✨ 클라이언트 : 클라이언트-서버 구조에서 서버에서 클라이언트로 서비스를 요청하고 클라이언트는 요청에 맞게 사용자에게 적절한 형태로 표현하는 기능을 가진 프로그램을 뜻한다.
        메시지를 받는 클래스도 클라이언트라고 할 수 있다.

        ✨ 인터페이스: 어떤 객체와 상호 작용하는 형태를 의미. 자바에서는 인터페이스를 사용하는 클래스는 해당 인터페이스에 정의된 메소드를 반드시 오버라이딩해야한다.
        상속과는 조금 다르지만 자바에서는 상속과 같은 개념으로 사용하고 있으며 이를 통해 다중 상속이 가능하다.

    - Dependency inversion principle
        상위 계층이 하위 계층(세부 사항)에 의존하는 전통적인 의존 관계를 역전시켜 상위 계층이 하위 계층의 구현으로 부터 독립되도록 하는 원칙. 이를 통해 하위 계층의 변경이 상위 계층으로 전파되는 것을 막아 유지보수 측면에서 큰 이점이 있다.

        상위 클래스일수록, 추상 클래스일수록 변하지 않을 가능성이 높기 때문에 이를 의존하라는 것이 의존 역전 원칙이다.

        예를 들어 자동차라는 클래스가 스노우 타이어라는 하위 클래스에 의존되어 있다고 가정해보자.
        만약 스노우 타이어가 아닌, 일반 타이어로 바꾸려고 한다면 자동차 클래스의 코드까지 고쳐야하는 상황이 발생할 것이다.
        여기서 자동차가 스노우 타이어 같은 구체적인 클래스에 의존하지 않고 `타이어` 라는 추상적인 클래스에 의존하고,
        스노우 타이어 같은 구체적인 클래스는 상위 클래스인 `타이어` 를 의존한다면 어떨까?

        타이어 클래스의 자식 클래스인 스노우 타이어는, 같은 자식 클래스인 일반 타이어로 바뀌어도 자동차는 정상 작동할 것이다.
        자동차가 추상 클래스인 타이어 클래스에 의존되어 있기 때문이다.
        여기서 구체적인 스노우 타이어와 자동차 사이에 추상적인 타이어 클래스를 추가적으로 두어 스노우 타이어의 의존 관계를 역전시키고 있으므로 이를 의존 역전 원칙이라고 한다.

        참고([https://server-engineer.tistory.com/228](https://server-engineer.tistory.com/228))

### 링크

[https://velog.io/@thms200/SOLID-원칙w.OOP](https://velog.io/@thms200/SOLID-%EC%9B%90%EC%B9%99w.OOP)

[https://ko.wikipedia.org/wiki/SOLID_(객체_지향_설계)](https://ko.wikipedia.org/wiki/SOLID_(%EA%B0%9D%EC%B2%B4_%EC%A7%80%ED%96%A5_%EC%84%A4%EA%B3%84))

[https://hckcksrl.medium.com/solid-원칙-182f04d0d2b](https://hckcksrl.medium.com/solid-%EC%9B%90%EC%B9%99-182f04d0d2b)

[https://ko.wikipedia.org/wiki/객체_지향_프로그래밍](https://ko.wikipedia.org/wiki/%EA%B0%9D%EC%B2%B4_%EC%A7%80%ED%96%A5_%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D)