[1단계 - 지하철 노선도 미션] 서니(박선희) 미션 제출합니다.
woowacourse/react-subway-map pull request #23
Opened 2021-06-02 04:08 UTC by sunhpark42

안녕하세요! 이번에 브콜, 피터와 함께 지하철 노선도 앱을 제작했습니다. 

마지막 과제가 되니 규모가 많이 커졌네요😂😂
리뷰 잘 부탁 드립니다!

[🚇데모페이지](!https://ww-sunny-subway.netlify.app/stations)

- 6/2일 현재 NABOM 서버에 CORS가 발생하여 수정을 요청해 두었습니다. 데모는 다른 분들의 서버를 이용해서 확인해 주세요. 🙏🙏 감사합니다!

### 작동 영상 (역, 노선, 구간 관리 페이지)
#### 역 관리
![manage_station](https://user-images.githubusercontent.com/67677561/120422401-20a98c00-c3a3-11eb-882d-2eebb9dd9358.gif)

#### 노선 관리
![manage_line](https://user-images.githubusercontent.com/67677561/120422589-8ac23100-c3a3-11eb-933b-907f9f0960d4.gif)

#### 구간 관리
![manage_section](https://user-images.githubusercontent.com/67677561/120422607-944b9900-c3a3-11eb-920f-862020c66e97.gif)

### 미션 요구사항
* 협업 요구사항

  - 백엔드 페어와 협업을 위해 필요한 사항들을 논의합니다.
  - step1에서 사용할 API의 배포 일정, 이후 step2에서의 추가 개발을 위한 설계 논의, 그 외 필요한 사항들 있는 지.   확인
  - 배포한 API 4개 중 하나를 무작위로 연결하더라도 어플리케이션이 정상 동작해야 합니다.
  - 무작위 연결을 확인해볼 수 있는 방법은 페어와 자율적으로 결정합니다.

* 구현 요구사항

  - 요구사항 명세를 먼저 작성합니다.
  - 상태 관리 방법을 스스로 선택합니다. 선택한 상태 관리 방법이 적절하다고 생각한 이유를 명시해주세요.
  - 레벨 1에서 구현했던 기능들을 React로 다시 구현해보는 작업입니다. 레벨 1에서 개발했던 어플리케이션을 다시 확인해보세요.

* 테스트 요구사항

  - 각 기능별로 테스트 코드를 반드시 포함합니다.

### 이 번 미션에서 사용한 상태관리 방법 및 이유
- 이번 미션에서는 contextAPI를 이용하여 현재 API, theme, user의 로그인 정보를 관리했습니다.
- 여러명의 관리자가 하나의 노선도를 변경할 수 있는 앱이기 때문에, 자주 지하철 정보에 대한 갱신이 필요하다고 생각되었습니다. 지역적으로(한 로컬에서) 상태관리를 할 때 'A관리자'가 변경한 사항을 'B관리자'가 제 때 알아차릴 수 없고, 그로인한 오류가 많아질 것으로 예상하였고, 따라서 지하철 정보에 대한 상태관리는 하지 않았습니다.
- 이후 상태관리가 필요한 것들을 추려봤을 때, 별도의 라이브러리 없이 contextAPI만 이용해도 될 것 같다는 판단이 들어, 현재 API, theme, user의 로그인 정보를 전역으로 관리하고, 그 외의 정보는 page내에서 관리하도록 구현하였습니다.

### 이번 미션에서 시도해 본 것
1. 타입스크립트를 처음 사용해 보았습니다. 혹시나 잘못 사용된 부분이 있는지 봐주시면 감사하겠습니다!
2. 기존 모달을 이용하여 노선과 구간을 추가하는 것이 사용자 입장에서 보았을 때, 추가를 위해 거쳐야 하는 단계가 많다고 느껴졌습니다. 그래서 모달, 페이지 이동 없이 역을 추가할 수 있도록 추가 양식을 열고, 닫는 UIf를 구현해 보았습니다. 

### 궁금한 점
1. 이번 미션에서의 지하철 노선도는 하나의 지하철 노선도를 여러명의 관리자가 동시에 관리할 수 있는 형태로 제작되었습니다. 이에 따라 실시간으로 데이터가 변동되는 것이 자연스러워 지하철과 관련된 정보를 전역적으로 관리하지 않고, 필요할 때 마다 호출하는 방식으로 구현했습니다. 그러다보니 API 요청이 많아진 것 같은데, 실시간으로 정보가 업데이트 되어야 하는 앱의 경우 API요청을 많이 보내는 것이 자연스러운건지, 이와 비슷한 앱의 경우 어떻게 데이터를 관리하는 지 궁금합니다.

2. 커스텀 훅을 만드는 기준이 무엇인 지 궁금합니다. 이번에는 요청과 관련된 것들을 커스텀 훅으로 제작해 보았는데, 언제 커스텀훅이 필요한 것인지, 언제 필요가 없는지에 대한 감이 잘 오지않아서, 리뷰어님은 언제 커스텀 훅을 만들어 쓰시는지 궁금합니다.

2021-06-08 13:35 UTC, Vallista requested changes
안녕하세요 서니!
이번에 코드량이 많아서 꼼꼼히 보는데 정말 오래걸리네요 ㅠㅠ

## UX 피드백

코드에 집중하는 편이 더 좋을거라 생각하여 과감히 생략합니다!  (부분적으로 코드에 UX 관련해서 피드백을 드렸습니다!)

## 전반적인 코드 리뷰

1. 먼저, 프로젝트에 타당한 형태의 기술과 구조를 구현한 걸로 보입니다 👍  상세는 사용해보면서 디테일하게 알아가야 하겠지만, 전체적으로 보았을 때 나쁜 구조와 기술선택은 아니여보입니다. 특히, 수많은 상태를 관리하는 부분을 Page에서 처리가능하다라고 생각하시고, Context API로는 정말 필요한 기술만, 비즈니스 로직은 페이지 내에서 처리를 하는 방법은 인상깊었습니다. 

2. API 로직은 hooks 뿐만 아니라, 추후 redux 등의 기술적 선택으로 인해 변경되면 충분히 재사용 가능한 로직이기 때문에 레이어를 추가하셔서 재사용할 수 있게 분리하는게 좋겠습니다. 또한 API 로직 및 hooks에서의 에러 처리가 미흡합니다. 어떤 에러코드에 따라 레이아웃에서 더 쉽게 핸들링할 수 있을지를 고민해보는게 좋겠습니다. 지금은 아에 HTTP Response Code를 고려하지 않고 있는 코드라 아쉽네용 ㅠ

3. 그 외에는 디테일하게 코드라인에 남겨두었으니! (약 80개의 코멘트입니다 ㅠㅠ 홧팅) 확인해보시면 좋겠습니다!

## 질문 답변

### 첫 번째 질문

```
궁금한 점
이번 미션에서의 지하철 노선도는 하나의 지하철 노선도를 여러명의 관리자가 동시에 관리할 수 있는 형태로 제작되었습니다. 이에 따라 실시간으로 데이터가 변동되는 것이 자연스러워 지하철과 관련된 정보를 전역적으로 관리하지 않고, 필요할 때 마다 호출하는 방식으로 구현했습니다. 그러다보니 API 요청이 많아진 것 같은데, 실시간으로 정보가 업데이트 되어야 하는 앱의 경우 API요청을 많이 보내는 것이 자연스러운건지, 이와 비슷한 앱의 경우 어떻게 데이터를 관리하는 지 궁금합니다.
```

보통 실시간 데이터가 필요하면 socket.io 를 사용해서 패킷을 받아 반영하는 방법을 많이 사용합니다. 다만, 업비트는 실시간으로 REST API를 사용해 통신하더라구여. 다만, 데이터가 많아지고 컴포넌트가 증가하면 Page에서 해결할 수 있는 한계가 명확하기 때문에 추후에는 Redux-Redux Saga등을 이용해 전역상태 및 페이지 모듈 단위의 상태 관리를 해주는 무언가 중간점이 필요해보입니다.

지금 프로그램 규모도 사실은 API 요청이 그리 빈번한 편은 아니기 때문에 지금 수준으로 구현하신 것은 괜찮은 구현이라고 생각됩니다.

### 두 번째 질문

```
커스텀 훅을 만드는 기준이 무엇인 지 궁금합니다. 이번에는 요청과 관련된 것들을 커스텀 훅으로 제작해 보았는데, 언제 커스텀훅이 필요한 것인지, 언제 필요가 없는지에 대한 감이 잘 오지않아서, 발리스타님은 언제 커스텀 훅을 만들어 쓰시는지 궁금합니다.
```

커스텀 훅을 잘 만들어 쓰신걸로 보입니다~ 다만 조금 아쉬운 점은 context api와 hooks를 연계해서 더 많은 훅을 만들 수 있었을 텐데 라는 것 하나와, 조금 더 적극적으로 1회성 훅을 만들더라도 도전해보는 과감함이 없던 것 하나입니다. 다른 분들께도 피드백을 드렸었는데요!  공통으로 사용될 부분들만 뽑는게 아닌, 비즈니스 로직을 더 적극적으로 넣어봐서 (예시로는 노선도 페이지 당 비즈니스 레이어를 분리하기위한 훅을 만들던..) 넣어본 것에 결과를 비교해보는 것도 좋겠습니다. 

저는 커스텀 훅은 기능이면서, 레이어라고 생각합니다. 공통으로 쓰일 수 있는 훅들이 있다면 그 안에는 비즈니스를 공통적으로 담고있는 훅도 있겠고, 로직의 분리를 위해 만든 훅일수도 있겠죠. 그렇기 때문에 전체적인 프로젝트 설계에서 레이어를 어떻게 만들지 상상해보시고 훅스를 해당 방향성을 갖고 써보시는 걸 추천드립니다!

2021-06-08 13:35 UTC, Vallista commented on .prettierrc
> +  "trailingComma": "es5",
trailingComma es5는 무엇인가용?

2021-06-08 13:35 UTC, Vallista commented on package.json
> +    "web-vitals": "^1.0.1"
web-vitals 쓰고 있나용?

2021-06-08 13:35 UTC, Vallista commented on public/ww-subway-logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 47.67"><g id="레이어_2" data-name="레이어 2"><g id="레이어_1-2" data-name="레이어 1"><circle cx="18" cy="18" r="11" transform="translate(-6.55 11.28) rotat
eof~~

2021-06-08 13:35 UTC, Vallista commented on src/App.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
`useState(false)`만 해도, useState가 타입추론으로 boolean을 가질텐데 따로 추가한 이유가 있나용?

2021-06-08 13:35 UTC, Vallista commented on src/App.tsx
> +    addMessage?.(SUCCESS_MESSAGE.LOGOUT);
굿드~

2021-06-08 13:35 UTC, Vallista commented on src/App.tsx
> +              onClick={() => {
저는 인라인으로 함수 추가하는 것을 비추합니다!
왜 그러냐면, 마크업은 마크업 뎁스나 어떤 컴포넌트가 있는지를 중점으로 보아야 하고, 실질적인 로직은 분리가 되어 있을수록 쉽게 이해할 수 있거든요!

2021-06-08 13:35 UTC, Vallista commented on src/App.tsx
> +              onClick={() => {
아니면 이 로직은 이렇게 넣을 수 있겠네요!

```tsx
<button onClick={onLogout}>로그아웃</button>
```

2021-06-08 13:35 UTC, Vallista commented on src/App.tsx
> +          <Route exact path={PATH.LOGIN} render={() => <LoginPage setIsLoading={setIsLoading} />} />
Route가 반복되니

```tsx
const ObjectLiteral = [
  {
    path: ?,
    component: ?
  }
]
```

형태로 만들어서 for-loop 혹은 map으로 한 번에 렌더링 시킬 수 있겠어용~

2021-06-08 13:35 UTC, Vallista commented on src/GlobalStyle.ts
> +    box-sizing: border-box;
죄다 `box-sizing: border-box`를 주기보다, inherit을 줘서 상속하게 하는건 어떨까유?

2021-06-08 13:35 UTC, Vallista commented on src/assets/images/ww-subway-logo-text.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 294.5 53.42"><defs><style>.cls-1{fill:#fff;}</style></defs><g id="레이어_2" data-name="레이어 2"><g id="레이어_2-2" data-name="레이어 2"><path class="cls-1" d
eof~

2021-06-08 13:35 UTC, Vallista commented on src/components/ApiSwitch/ApiSwitch.style.ts
> +  display: grid;
오홋 그리드!

2021-06-08 13:35 UTC, Vallista commented on src/components/ApiSwitch/ApiSwitch.style.ts
> +  background-color: ${PALETTE.WHITE};
PALETTE가 너무 한정적이에요!
white도 255, 255, 255 가 있을 수 있지만,
233, 233, 233도 화이트 계열이거든요~

그렇기 때문에 레벨을 주는게 어떨까요?
(하위 BAEMIN도 동일합니다.)

보니까 GRAY로 중간 레이어를 잘게 _700~ 형태로 해두신 것 같은데요!
이러한 포멧은 일관성이 있으면 좋겠습니다!

GRAY_700
WHITE
BAEMIN

... BAEMIN은 일단 닉네임도 좀 그렇네요. MINT_100 정도로 하는게 어떨까 싶네요
WHITE_100
이런식

2021-06-08 13:35 UTC, Vallista commented on src/components/ApiSwitch/ApiSwitch.style.ts
> +    text-shadow: 1px 1px 0px 1px ${PALETTE.GRAY_700};
`0px => 0`!

2021-06-08 13:35 UTC, Vallista commented on src/components/ApiSwitch/ApiSwitch.tsx
> +            onChange={() => {
인라인으로 넣는 것 보다 위로 로직을 빼는게 더 쉽게 볼 수 있지 않을까요?

2021-06-08 13:35 UTC, Vallista commented on src/components/ApiSwitch/ApiSwitch.tsx
> +            onChange={() => {
추후에 공통 로직이 생겼을 때도, 공통 로직을 쉽게 뽑을수도 있겠구요!

2021-06-08 13:35 UTC, Vallista commented on src/components/Header/Header.styles.ts
> +interface ContainerProps extends Properties {
React.CSSProperties 와 Properties가 다른점이 무엇인가요?

2021-06-08 13:35 UTC, Vallista commented on src/components/Header/Header.styles.ts
> +  animation: ${({ isAppear }) =>
요런 로직을 어떻게 공통화 시킬 수는 없을까나...

```tsx
${{{ isAppear }) =>
  isAppear ? (
    css`
      animation: ${slideIn} 0.2s;
      transform: 'translateY(0);
    `
  ) : (
    css`
      animation: ${slideOut} 0.2s;
      transform: 'translateY(-105%);
    `
  )
```

요게 더 깰끔쓰 한 것 같기도 하네요

2021-06-08 13:35 UTC, Vallista commented on src/components/Header/Header.tsx
> +      document.removeEventListener('wheel', onScroll);
이 친구 혹시 iOS 모바일에서 해제 되는지 확인해보셨나요? 아마 onScroll 해제가 안될껀데

2021-06-08 13:35 UTC, Vallista commented on src/components/Header/Header.tsx
> +      document.removeEventListener('wheel', onScroll);
어플리케이션 종료시에 알아서 메모리 해제는 하겠으나..

2021-06-08 13:35 UTC, Vallista commented on src/components/Header/Header.tsx
> +        setIsAppear(false);
false여도 0보다 크면 계속 false로 state change를 하겠군요? 뭐,,, shallow eqaul로 내부에서 상태값을 바꾸진 않겠지만여

2021-06-08 13:35 UTC, Vallista commented on src/components/Header/Header.tsx
> +        setIsAppear(false);
개인적으로, 틱마다 연산하면 오버헤드가 생기니, 디바운스 등을 주어서 30ms 에 1연산을 주던 하는게 좋지 않을까용?

2021-06-08 13:35 UTC, Vallista commented on src/components/NavBar/NavBar.stories.tsx
> +      <a href="#">역</a>
`['역', '노선', '구간', '전체'].map(it => <a href="#">{it}</a>)`

2021-06-08 13:35 UTC, Vallista commented on src/components/Palette/Palette.tsx
> +        <ColorOption backgroundColor={PALETTE[name]}></ColorOption>
ColorOption이 무얼하는 친구인지 정확하게 모르겠어용

2021-06-08 13:35 UTC, Vallista commented on src/components/Palette/Palette.tsx
> +        <ColorOption backgroundColor={PALETTE[name]}></ColorOption>
조금 더 명칭을 자세히 적으면 좋겠습니다!

2021-06-08 13:35 UTC, Vallista commented on src/components/Palette/Palette.tsx
> +        <ColorOption backgroundColor={PALETTE[name]}></ColorOption>
보아하니 프리뷰 같은데,,, 컬러 옵션..?

2021-06-08 13:35 UTC, Vallista commented on src/components/shared/Box/Box.style.ts
> +  height: fit-content;
css를 잘 다루시는 것 같아 좋네요

2021-06-08 13:35 UTC, Vallista commented on src/components/shared/Box/Box.style.ts
> +  height: fit-content;
IE 지원은 안할 예정으로 생각해도 되겠죵??

2021-06-08 13:35 UTC, Vallista commented on src/components/shared/Box/Box.style.ts
> +    hatColor
차라리 삼항 연산자의 false로 공백을 주기보다 && 컨디션으로 주는건 어떨까요?

2021-06-08 13:35 UTC, Vallista commented on src/components/shared/Box/Box.tsx
> +  <Container hatColor={hatColor} backgroundColor={backgroundColor}>
```tsx
const Box = (props: BoxProps) => (
  <Container {...props}>{children}</Container>
)
```

2021-06-08 13:35 UTC, Vallista commented on src/components/shared/Button/Button.stories.tsx
> +const Template: Story<Omit<ButtonProps, 'translate'>> = (args) => <Button {...args}>Click</Button>;
Utility Type을 inline에 넣으면 가독성이 너무 안좋아지기 때문에, 위에 별도로 빼는게 어떨까요?

2021-06-08 13:35 UTC, Vallista commented on src/components/shared/Button/Button.tsx
> +  ${({ width }) => (width ? `width: ${width};` : '')}
`${({ width }) => width && `width: ${width}`)}` 는 안되나요?
전반적으로 &&를 안쓰시능??

2021-06-08 13:35 UTC, Vallista commented on src/components/shared/Button/Button.tsx
> +  ${({ width }) => (width ? `width: ${width};` : '')}
안되기 때문에 안쓰는건가... 안되던가...

2021-06-08 13:35 UTC, Vallista commented on src/components/shared/Select/Select.style.ts
> +    width: 0px;
```
width: 0;
height: 0;
```

2021-06-08 13:35 UTC, Vallista commented on src/components/shared/Spinner/Spinner.style.ts
> +    z-index: 19;
z-index는 어딘가 한 곳에서 모아놓고 사용하면 좋겠습니다 :0

2021-06-08 13:35 UTC, Vallista commented on src/constants/palette.ts
> +const PALETTE: { [key: string]: string } = {
COLOR는 일관적이었으면 좋겠네요.

2021-06-08 13:35 UTC, Vallista commented on src/constants/statusCode.ts
> +  STATION_IN_SECTION: '400',
오잉? 다른애들이 같네요?

2021-06-08 13:35 UTC, Vallista commented on src/contexts/SnackBarProvider.tsx
> +import { createContext, ReactNode, useEffect, useState } from 'react';
contexts/SnackBarProvider.tsx 는 Snacbar의 수퍼셋으로 인식하고 사용하는게 더 나을것으로 보입니다 👍 
Snackbar
  ㄴ context.tsx
  ㄴ index.tsx
  ㄴ style.ts

2021-06-08 13:35 UTC, Vallista commented on src/contexts/SnackBarProvider.tsx
> +import { createContext, ReactNode, useEffect, useState } from 'react';
어차피 Context를 쓰면 지역적으로 사용하니까여

2021-06-08 13:35 UTC, Vallista commented on src/contexts/UserContextProvider.tsx
> +    const checkLoginStatus = async () => {
```ts
(async () => {
  try {
    const userInfo = await apiRequest.getUserInfo()

    if (userInfo) setIsLoggedIn(true)
  } catch (err) {
    console.error(error)
  }
)()
```

Immediately Invoked Function Expressions (IIFE) 으로 할 수 있겠습니다 👍

2021-06-08 13:35 UTC, Vallista commented on src/contexts/UserContextProvider.tsx
> +  setIsLoggedIn: Dispatch<SetStateAction<boolean>>;
단순히 `setIsLoggedIn` 만을 패스하기보다, 어떤 특정한 동작을 유도하는게 선언적 프로그래밍에서 좀 더 의미가 와닿지 않을까요?

`login={}` 이러던가.. 특정한 행위로..

2021-06-08 13:35 UTC, Vallista commented on src/contexts/UserContextProvider.tsx
> +  setIsLoggedIn: Dispatch<SetStateAction<boolean>>;
다만, 타입 자체가 `useState` 긴 하네요. 바이패스를 생각하셨다면 충분하기도 하네용!

2021-06-08 13:35 UTC, Vallista commented on src/contexts/SnackBarProvider.tsx
> +  addMessage: (message: string) => void;
addMessage를 한다고 바로 발동되는게 아닌, reactive 성향을 띄니, pushMessage 로 네이밍을 명명하는게 어떨까요?

이벤트를 푸쉬한다는 의미에서 push.

2021-06-08 13:35 UTC, Vallista commented on src/contexts/SnackBarProvider.tsx
> +        <SnackBar key={message.id} order={arr.length - index}>
스낵바를 미리 생성해놓고 쓰는것도 좋겠습니다 👍 
지속적으로 생성하고 map에서 빠지고 하면 결국 메모리 공간 할당, 삭제가 반복되니까요!

2021-06-08 13:35 UTC, Vallista commented on src/contexts/SnackBarProvider.tsx
> +        <SnackBar key={message.id} order={arr.length - index}>
한 10개? 정도를 미리 만들어놓고 돌리는 건 어떨까요?

2021-06-08 13:35 UTC, Vallista commented on src/contexts/SnackBarProvider.tsx
> +        <SnackBar key={message.id} order={arr.length - index}>
이 패턴을 [Object Pool Pattern](https://creatordev.tistory.com/73) 이라고 합니다. 👍 

이렇게 되면 장점은, 기존에는 삭제될 때 리스트에서 삭제되므로 액션을 주기 어려우나, 리스트에서 유지되므로 eventListener로 animationEnd 등으로 이벤트를 주어, 취소시에도 애니메이션으로 제어할 수 있죠~

2021-06-08 13:35 UTC, Vallista commented on src/contexts/SnackBarProvider.tsx
> +      const timer = setTimeout(() => {
setTimeout보다는 css animation 으로 이벤트를 제어하는게 어떨까요?

2021-06-08 13:35 UTC, Vallista commented on src/contexts/SnackBarProvider.tsx
> +      const timer = setTimeout(() => {
내부에서 스넥바의 상태를 3가지로 두고 (IDLE, START, END) 
IDLE일 때는 애니메이션 안주고, START일때 올라오는, END일 때 내려가는.

상태가 끝나면 삭제

2021-06-08 13:35 UTC, Vallista commented on src/contexts/ThemeContextProvider.tsx
> +  themeColor: string;
[emotion의 theme provider](https://emotion.sh/docs/theming#themeprovider-reactcomponenttype)를 써보는 것도 좋겠습니다 👍  물론 직접 구현해도 좋지만요~

2021-06-08 13:35 UTC, Vallista commented on src/contexts/ThemeContextProvider.tsx
> +  themeColor: string;
시간이 촉박하다면 써드파티의 도움을 빌려도 좋겠어요~

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useDebounce.ts
> +const useDebounce = (callback: Function, delay: number) => {
훅으로 디바운스 만든거 좋네요~ 👍 

다만 쓰로틀이 필요할 때는 이벤트 전역으로 걸어줄 수 있게 무언가 처리를 해주는 것도 좋겠습니다 👍

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useInput.ts
> +const useInput = (
중복 로직을 줄여주는 훅을 구현했군요~ 좋습니다!

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useLines.ts
> +  getOne: async (lineId: number): Promise<APIReturnTypeLine> => {
getOne..? 이름이 조금 모호해보입니다~

getLine 이 어떨까요?

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useLines.ts
> +  getOne: async (lineId: number): Promise<APIReturnTypeLine> => {
Lines의 get은 전체고,
getLine은 단일 라인!

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useLines.ts
> +const API = {
저는 hooks에 API 로직이 있으면 안된다고 생각해요~
hooks는 controller와 같이, 다양한 로직이 엮이는 부분이지

다른 비즈니스를 통으로 갖고있는 부분은 아니거든요!
요 친구들은 `/apis/line.ts` 정도로 분리해서 import 후 사용하는게 좋지 않을까요?

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useLines.ts
> +  post: async (data: LineData, accessToken: string): Promise<void> => {
또한, API를 실패했을 때의 처리가 없네요, 이렇게 되면 비즈니스 로직에서 에러 바인딩 처리가 들어가겠군요..?

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useLines.ts
> +  post: async (data: LineData, accessToken: string): Promise<void> => {
1차적으로 에러를 API 레이어 쪽에서 가공해주고, 해당 에러 상태에 따라 페이지 및 훅에서 뷰를 컨트롤 할 수 있게 제공해야합니다!

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useLines.ts
> +  const fetchLine = async (lineId: number): Promise<void> => {
ㅠㅠ 아무곳에도 에러처리는 없군요..
너무 취약한 코드에요

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useLines.ts
> +  const fetchLine = async (lineId: number): Promise<void> => {
400, 500 과 같은 에러에 대응하는 처리가 필요해보여요~

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useLines.ts
> +  const fetchLine = async (lineId: number): Promise<void> => {
여기서 에러 처리를 안하게 되면 (hooks에서) 그럼 훅을 쓰는 모든 레이아웃에서 에러처리를 해줘야 하는 상황이 나오고, 동일한 코드가 많이 반복되겠죠?

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useSections.ts
> +import { request, REQUEST_URL } from '../request';
위와 동일한 피드백입니다 👍

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useSections.ts
> +  post: async (lineId: number, data: SectionData, accessToken: string) => {
API 구조를 보니 어느 동일한 포맷은 유지하나 보군요.
그렇다면, 동일한 포맷을 공통화를 어떻게 시킬 지 고민해봅시당

```ts
type ApiResponseCodeType = 200 | 300 | 400 | 500 | ...

interface APIResponse<T> {
  code: `${ApiResponseCodeType}`,
  result: T
  // 그 외 포맷들..
}
```

등으로 1차 래핑을 해준 후, 해당 Response에 해당하는 값을 넣어주면 Result에 모두 포맷팅이 되어, navigating이 되겠쥬..?

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useStations.ts
> +    return await response.json();
response.json()으로 보내면 get을 사용하는 곳에서는 어떤 값이 있는지, response가 정상적으로 왔는지 테스트 코드를 작성하는 것도 어렵겠네요 ㅠㅠ;

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useStations.ts
> +    return await response.json();
올바른 걸까요?

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useStations.ts
> +  () => Promise<void>,
Promise<void>를 넘기는 것보다, 사용처에서는 제대로 실행이 되었는지 아닌지를 판별하기 위해 최소 `boolean` 형태로 넘겨주는게 어떨까요?

2021-06-08 13:35 UTC, Vallista commented on src/hooks/useStations.ts
> +  () => Promise<void>,
실행 결과에 따라 레이아웃 상태를 조절해주어야 하니까요~

2021-06-08 13:35 UTC, Vallista commented on src/pages/LinePage/LinePage.style.ts
> +const TitleBox = styled<any>(Box)`
any는 되도록 쓰지 말아주세요~ 정확하게 `styled<{ isOpen }>(Box)`를 써주는게 좋겠습니다. 아니라면 어떤 문제가 있나요?

2021-06-08 13:35 UTC, Vallista commented on src/pages/LinePage/LinePage.style.ts
> +    z-index: 10;
z-index는 한 곳에 모아서 코드를 작성해주는게 좋겠습니다 👍

2021-06-08 13:35 UTC, Vallista commented on src/pages/LinePage/LinePage.style.ts
> +  transition: all 1s ease-out;
all을 주는 것보다 어떤 특정한 애니메이션인지 알려주는게 좋지 않을까요? 왜냐하면, Form의 스타일만 보고는 어떤 트랜지션이 일어나야 하는지, 모두 일어나도 좋은지 이런게 체크하기 어려워요~

2021-06-08 13:35 UTC, Vallista commented on src/pages/LinePage/LinePage.test.tsx
> +  it('지하철 노선 삭제가 가능하다.', async () => {
삭제가 가능한데, 삭제가 안되었을 때의 테스트가 더 중요합니다.
테스트는 잘 되네? 를 보기위한게 아니라, 잘 안되네를 보기 위함 입니다!

TDD가 진행되고 있지 않은 상황에서, 성공적인 테스트를 작성하는 것보다 오히려, 예외처리에 대한 테스트는 개발 후에 작성하는게 더 효율적입니다 👍

2021-06-08 13:35 UTC, Vallista commented on src/pages/LinePage/LinePage.tsx
> +  Heading1,
Heading1..5 이렇게 만드는 것보다, Heading 내부에 레벨을 조정할 수 있게 구현하면 더 좋겠습니다 👍

2021-06-08 13:35 UTC, Vallista commented on src/pages/LinePage/LinePage.tsx
> +  const [formOpen, setFormOpen] = useState<boolean>(false);
어딘가에서는 boolean에 is를 쓰고, 여기서는 안쓰는데 차이가 무엇일까요?

2021-06-08 13:35 UTC, Vallista commented on src/pages/LoginPage/LoginPage.style.ts
> +  width: fit-content;
IE는 버리는걸로 보아도 되겠죵?

2021-06-08 13:35 UTC, Vallista commented on src/pages/LoginPage/LoginPage.test.tsx
> +const EMAIL = 'test@test.com';
test 로직에 계정와 비밀번호는 노출되면 안됩니다~ 그렇기 때문에 이러한 정보는 실행시에 생성되고 이후에 삭제될 수 있게 무언가 실행 전 공정이 필요해보여요~

2021-06-08 13:35 UTC, Vallista commented on src/pages/LoginPage/LoginPage.test.tsx
> +  it('이메일 혹은 패스워드가 입력되지 않으면 에러메시지를 보여준다.', async () => {
굿, 사용자 관점에서 이러한 테스트가 중요합니다~

2021-06-08 13:35 UTC, Vallista commented on src/pages/LoginPage/LoginPage.tsx
> +    try {
여기서 try-catch 처리를 하지말고, API 및 hooks에서 해당 처리를 해주도록 합시다~
그래서 해당 에러 포멧에 따라 레이아웃에서는 해당 처리만 해주는걸로

2021-06-08 13:35 UTC, Vallista commented on src/pages/SectionPage/SectionPage.style.ts
> +const FormBox = styled<any>(Box)`
무언가 이 친구는 반복되는군요.
Form도 하나의 컴포넌트로 때면 좋겠어용

2021-06-08 13:35 UTC, Vallista commented on src/pages/SectionPage/SectionPage.tsx
> +const NO_SELECTED_LINE: number = -1;
-1만 해도 number 형으로 타입 추론 해주지 않나요?

2021-06-08 13:35 UTC, Vallista commented on src/pages/SectionPage/SectionPage.tsx
> +    return <></>;
무언가 로딩중이라는 메시지가 있어야 하지 않을까요?
그리고 실행중에 로딩을 다시 걸면 레이아웃이 다 날라가고 새로 보이겠군요?!

그러면 깜빡임이 발생할 것이고, 과연 좋은 레이아웃일까요?
overlay 형태로 보여주는게 더 좋지 않을까요?

2021-06-08 13:35 UTC, Vallista commented on src/utils/validator.ts
> +const isValidLength = (value: string, minLength: number = 0, maxLength: number) => {
default parameter가 minLength에만 있는데, 요게 의미가 있는 구문인가요..? default parameter를 쓰는 이유는 디폴트 값을 넣어서 안써도 쓸 수 있게 하기 위함인데 위의 코드는 중간에만 들어가므로, maxLength는 무조껀 넣어줘야 하니, default parameter의 의미가 없어보여용~

2021-06-08 13:35 UTC, Vallista commented on src/pages/StationPage/StationPage.test.tsx
> +      'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjIyMDMzMjkxLCJleHAiOjE2MjIwMzY4OTF9.-M7TyMMvXk-y5-kIoPP4crTt6Nnvv8ubREKKZjO5d7A'
이런 값은 mock으로 만들어서 공통으로 쓰면 좋겠습니다~

2021-06-10 05:20 UTC, sunhpark42 commented on .prettierrc
> +  "trailingComma": "es5",
object, arrays등에서 마지막 요소에 comma를 찍어주는 옵션입니다. all 로 하면 함수의 파라미터에도 comma가 생겨서, es5로 설정해두었습니다! defualt가 none인줄 알아서 설정해 두었는데, none에서 es5로 바뀌어 있었네요!

2021-06-10 05:21 UTC, sunhpark42 commented on package.json
> +    "web-vitals": "^1.0.1"
안쓰고있습니다. Remove하는 것을 잊은 것 같습니다. 삭제하겠습니다~

2021-06-10 05:25 UTC, sunhpark42 commented on src/App.tsx
> +  const [isLoading, setIsLoading] = useState<boolean>(false);
타입스크립트를 처음 사용해봐서, 타입추론까지 고려를 못했습니다. 초기값으로 boolean을 넣으면 타입 추론이 될 텐데 코드를 짤 당시에는 생각을 못했습니다.😂

2021-06-10 05:30 UTC, sunhpark42 commented on src/App.tsx
> +              onClick={() => {
아무래도 원래 들어있던 인라인 함수를 따로 분리하는과정에서 잘못 작성한 부분 같습니다. 인라인으로 함수를 추가하는 것과, 로직을 따로 분리해서 보는 것에 어떤 차이점이 있는지 이해할 수 없었는데, 분리해서 볼 수 있다는 장점이 있네용!😲😲

2021-06-10 05:31 UTC, sunhpark42 commented on src/App.tsx
> +          <Route exact path={PATH.LOGIN} render={() => <LoginPage setIsLoading={setIsLoading} />} />
Route도 한번에 렌더링 시키는게 가능하겠네요! 생각하지 못했습니다 ㅎㅎ..👍👍

2021-06-10 05:40 UTC, sunhpark42 commented on src/components/ApiSwitch/ApiSwitch.style.ts
> +  background-color: ${PALETTE.WHITE};
당장 사용할 것이 아니더라도, 잘게 쪼개놓는 것이 추후 변경에도 유용하겠네요. ㅎㅎ BAEMIN, NAVER 등의 닉네임은 서버변경에 따른 메인 색상 변경을 위해 그렇게 해둔 거였는데(저희끼리의 재미요소 정도), 그 경우가 아닐때에는 MINT로 작성하는게 나았을 것 같다는 생각이 드네요. 수정하겠습니다~

2021-06-10 05:45 UTC, sunhpark42 commented on src/components/shared/Box/Box.style.ts
> +  height: fit-content;
넵. IE는 지원하지 않는것으로 여기고 작성했습니다.

2021-06-10 05:57 UTC, sunhpark42 commented on src/components/shared/Box/Box.style.ts
> +    hatColor
&& condition으로 주게되면 css 에 undefined로 들어가게 된다고 생각해서 전체적으로 && 를 사용하지 않았습니다. 생각해보니 `color: ${({color}) => color }` 와 같이 주는 경우에만 color: undefined와 같이 작동을 하네요 ㅎㅎ. 통으로 css의 속성이 존재하거나 하지 않거나 하는 경우에는 && 연산자를 사용하는 것이 더 깔끔하겠네요~ 예를 든 경우만 생각해서, 전반적으로 삼항연산자로 작성했습니다!

2021-06-10 05:59 UTC, sunhpark42 commented on src/components/shared/Button/Button.tsx
> +  ${({ width }) => (width ? `width: ${width};` : '')}
[https://github.com/woowacourse/react-subway-map/pull/23#discussion_r648871324](https://github.com/woowacourse/react-subway-map/pull/23#discussion_r648871324)

와 같은 이유로 다음과 같이 작성했습니다. 지금 보니 color와 size, width에서 다루는 것이 제각각이네요.😂 통일하겠습니다.

2021-06-10 06:00 UTC, sunhpark42 commented on src/components/shared/Spinner/Spinner.style.ts
> +    z-index: 19;
모아두고 선택하는 방법이 있네요! 개인적으로도 코드를 작성하면서 z-index가 헷갈렸는데 좋은 인사이트 감사합니다👍👍

2021-06-10 08:08 UTC, sunhpark42 commented on src/components/Header/Header.styles.ts
> +  animation: ${({ isAppear }) =>
이부분은 한번에 처리할 수 있었겠네요!

2021-06-10 08:11 UTC, sunhpark42 commented on src/components/Palette/Palette.tsx
> +        <ColorOption backgroundColor={PALETTE[name]}></ColorOption>
원래 input을 숨기고, 라벨을 이용하여 input과 같이 보이는 엘리먼트를 만들어서 사용한 것이라서 이런 이름을 지었습니다! 여러개의 Radio button이 있을 때 하나하나가 option이라고 생각해서 이렇게 이름을 붙였는데, 더 정확하게 작성해 보도록 하겠습니다~

2021-06-10 08:12 UTC, sunhpark42 commented on src/components/shared/Box/Box.tsx
> +  <Container hatColor={hatColor} backgroundColor={backgroundColor}>
오... 이렇게도 쓸 수 있네요..😲😲

2021-06-10 08:28 UTC, sunhpark42 commented on src/hooks/useLines.ts
> +const API = {
아하 안그래도 같이 있는 것이 어색해서 어떻게 분리하면 좋을까 생각하고 있었는데, 간단히 분리한 후 Import 를 해서 사용할 수 있었겠네요~

2021-06-10 08:29 UTC, sunhpark42 commented on src/hooks/useLines.ts
> +  post: async (data: LineData, accessToken: string): Promise<void> => {
늘 API에 대한 에러를 어디에서 처리해주어야 하는지에 대한 고민이 있었는데, 비즈니스 로직과 분리해주는게 더 좋겠네요

2021-06-10 08:37 UTC, sunhpark42 commented on src/pages/LinePage/LinePage.tsx
> +  const [formOpen, setFormOpen] = useState<boolean>(false);
boolean의 경우 모두 Is 를 줬는데, 미처 수정하지 못한 부분같습니다. 수정하겠습니다. 감사합니다~

2021-06-10 08:50 UTC, sunhpark42 commented on src/pages/SectionPage/SectionPage.tsx
> +    return <></>;
로딩중이라는 Overlay 의 경우 최상단에서 보였다, 사라졌다 하는 방식으로 구현했습니다. 첫 렌더링 시 데이터가 불러와 지기 전, "지하철이 없습니다" 와 같은 메시지가 표현되는 것을 막고자 첫 렌더시에 데이터 요청이 완료될 때까지 아무것도 보이지 않게끔 하기 위해 다음과 같은 코드를 작성했습니다.

2021-06-10 09:34 UTC, sunhpark42 commented on src/hooks/useStations.ts
> +  () => Promise<void>,
아하 생각해보니, setStation으로 station값을 변경하고 있지만, 실행이 되었는지 아닌지에 대한 판별 결과가 없네요! 잘 고쳐보겠습니다!

2021-06-11 03:31 UTC, sunhpark42 commented on src/pages/LinePage/LinePage.style.ts
> +const TitleBox = styled<any>(Box)`
Box를 확장해서 오는과정에서 타입에러가 자꾸 나는데, 해결할 수가 없어서 any 로 두었습니다. `styled(Box)<{ isOpen : boolean }>`\`으로 수정했습니다!

2021-06-11 03:37 UTC, sunhpark42 commented on src/components/Header/Header.tsx
> +      document.removeEventListener('wheel', onScroll);
iOS 모바일에서 확인해보지않았습니다. 모바일 기기에 따라 해제가 안되는 경우도 있나보네요 😂😂

2021-06-11 03:42 UTC, sunhpark42 commented on src/pages/LoginPage/LoginPage.test.tsx
> +const EMAIL = 'test@test.com';
아하 혹시, 실제로 존재하는 계정이 아닌, 포맷만 확인하기 위해 작성할 때에도 이렇게 사용하면 안되는걸까요??

2021-06-11 04:30 UTC, sunhpark42 commented
안녕하세요! 발리스타님. 1단계 리뷰 반영해보았습니다. 마지막 미션까지도 리뷰 꼼꼼히 해주셔서 감사합니다! 덕분에 의문이었던 점들과, 해결하지 못했던 부분들이 많이 해결되었습니다. :) 👍👍 제대로 반영이 되었는지는 모르겠네요😂 항상 리뷰 감사드립니다!

(시간 상 스낵바 관련 피드백 [https://github.com/woowacourse/react-subway-map/pull/23#discussion_r647395639](https://github.com/woowacourse/react-subway-map/pull/23#discussion_r647395639) 은 반영하지 못했습니다. 😭😭)

2021-06-11 16:41 UTC, Vallista commented on src/components/shared/Box/Box.style.ts
> +    hatColor
근데 undefined 되면 styled-component든 emotion이든 알아서 적용 안해주더라구여~ ㅋㅋ

2021-06-11 16:42 UTC, Vallista commented on src/pages/LoginPage/LoginPage.test.tsx
> +const EMAIL = 'test@test.com';
그럼 이름이 BASE_URL이면 안될 것같아요... ㅠ EMAIL두여...

2021-06-11 16:42 UTC, Vallista commented on src/pages/LoginPage/LoginPage.test.tsx
> +const EMAIL = 'test@test.com';
mock 파일로 분리해서 관리하는게 좋겠네여..

2021-06-11 16:43 UTC, Vallista commented on src/pages/SectionPage/SectionPage.tsx
> +    return <></>;
좋은 UX는 아니어보여요! 그리고 CSR과 SPA의 장점에 대해 다시 생각해보면 좋겠어요~

2021-06-11 17:01 UTC, Vallista requested changes
안녕하세요 서니!
1단계 지하철 노선도 미션 반영하여 PR 주셔서 감사합니다~

다만! 아직 완벽하게 처리가 안된 부분들이 있기 때문에 다시 RC 요청 드립니다~
또한, API 쪽에 추가로 설명이 들어간 부분이 있기 때문에 한 번 살펴보아주셨으면 감사하겠습니다~

2021-06-11 17:01 UTC, Vallista commented on src/apis/line.ts
> +      const response = await request(`${REQUEST_URL}/lines`, {
try-catch 절이 반복되고 그 안에서의 에러 처리도 반복되고 있는데요~ 이 부분도 래핑을 좀 하면 좋겠어요!

인간의 욕심은 끝이 없고... 반복된다...

```tsx
interface APISuccessShape<T> {
  ok: true
  data: T
}

interface APIFailureShape<T extends string> {
  ok: false
  error: {
    type: `${number}`,
    message: T
  }
}

const ApiFetcher = <
  S, 
  F, 
  SW extends APISuccessShape<S>,
  FW extends APIFailureShape<F>
>(
  uri: string,
  method: 'GET' | 'POST' | 'PATCH' | 'DELETE' | 'PUT',
  ...args: (string | number)[]
): Promise<SW | FW> => {
  try {
     const response = await request(`${uri}, { method })
     const json = await response.json()

    return {
      ok: true,
      data: json
    }
  } catch (err) {
    const code = err.code
    return {
      ok: false,
      error: {
        code,
        message: ErrorMessage[`ERROR${code}` as keyof typeof ErrorMessage]
      }
    }
  }
}
```

대충 이랬으면 좋겠다.. 하고 뇌내속 망상코딩 한 것이지 정상 동작 하는지는 모릅니다.. 대충 요런 느낌?

2021-06-11 17:01 UTC, Vallista commented on src/apis/line.ts
> +      const response = await request(`${REQUEST_URL}/lines`, {
사용처에서는

```tsx
const API = {
  get: async () => {
    return ( await ApiFetcher<APIReturnTypeLine, ErrorMessage>(`${REQUEST_URL}/lines`, 'GET') )
  }
}
```

2021-06-11 17:01 UTC, Vallista commented on src/apis/line.ts
> +      const response = await request(`${REQUEST_URL}/lines`, {
`: Promise.. `없는 이유는 타입추론이 되기 때문

2021-06-11 17:01 UTC, Vallista commented on src/components/Header/Header.styles.ts
> +interface ContainerProps extends Properties {
답..변...해주세여..

2021-07-02 10:22 UTC, sunhpark42 commented on src/apis/line.ts
> +      const response = await request(`${REQUEST_URL}/lines`, {
리퀘스트 관련 처리를 하다보니 타입스크립트를 사용함에 있어서 에러도 나고, 어떻게 처리해야 하나 하다보니 시간이 꽤 오래 걸렸네요 ㅠㅠ 많이 늦어서 죄송합니다. 🙏🙏 이렇게 리퀘스트 관련한 로직을 분리하다보니 확실히 사용처에서 훨씬 깔끔하게 처리 할 수 있다는 것이 많이 와닿았습니다. 신기한(?) 경험이었어요!

타입스크립트를 사용하면서 타입추론이 무엇인지 모르고 첫 미션을 진행했었는데, 한 번 겪고보니 제네릭을 어떻게 사용하는지, 타입추론이 무엇인지 작게나마 느낄 수 있었던 것 같습니다. 아직 많이 부족한 실력이지만, 덕분에 한 층 더 성장할 수 있던 것 같습니다. 감사합니다:)

2021-07-02 10:25 UTC, sunhpark42 commented on src/components/Header/Header.styles.ts
> +interface ContainerProps extends Properties {
앗, 리뷰가 많아서 답변을 달다가 놓친 것 같습니다 ㅠㅠ 확인해본 결과 다른 점은 없습니다. CSS의 타입정의를 편하게 이용하기 위해서 csstype에서 Properties를 가져와서 사용했는데, React 내부의 Type definitions을 열어보니 csstype에서 import를 해온 후 export를 하고 있는 것을 확인 할 수 있었습니다. React.CSSProperties가 있다는 것을 인지하지 못하고 있었는데 csstype을 설치하지 않아도 됐었네요..😲😲

2021-07-02 11:04 UTC, sunhpark42 commented
리뷰 반영해 보았습니다. 리뷰 부탁드립니다. 감사합니다!

2021-07-03 01:58 UTC, woowapark commented
1차적인 수정은 완료한 것으로 보고,     
이후 단계까지 마무리를 위해 추가 수정사항에 대한 리뷰는 머지된 후에 진행되어도 좋을 것 같아 머지하겠습니다.        
고생하셨습니다 🙏

2021-07-03 01:58 UTC, merged