[2단계 - 지하철 노선도 미션] 피터(안현철) 미션 제출합니다.
woowacourse/react-subway-map pull request #43
Opened 2021-06-09 20:19 UTC by iborymagic

### [지하철 노선도 2단계 데모 사이트](https://iborymagic-react-subway.netlify.app)

1단계에서 말씀해주신 Submit 함수나, 아니면 Delete 함수같은 경우는
change validation은 이미 분리해놨고, 함수 내부에서 실행되는 validation은 전부
submit이나 delete 요청이 갈 때 실행되어야 하는 validation이라 분리하기가 좀 애매한 것 같다고 생각했습니다.
그래서 일단은 그대로 둔 상태입니다.
우선 PR을 제출하고, 여유를 가지고 차근차근 리팩토링을 해보도록 하겠습니다.

마지막 피드백이라서 상당히 아쉽습니다..😭
그동안 고생 많으셨고, 좋은 리뷰 해주셔서 정말 감사드립니다.

## 🚇 2단계 추가 기능
- 지하철 전체 보기 기능

## 🧐 궁금한 점
1. 1단계 피드백에서 말씀해주신 타입 추론을 하기 위해서는, 
tuple임을 명시해주기 위해 as const를 써줘야 하는 듯 합니다.
그러지 않으면, 배열로 추론되기 때문에 배열의 모든 요소들이 
string | ChangeEventHandler<HTMLInputElement> | Dispatch<SetStateAction<string>> 으로 추론돼서, 
사용하는 곳에서 에러가 났습니다. 혹시, as const를 적어서 tuple로 만들어주는 것이 의도하신 바가 맞나요?

2. forwardRef를 사용하는 데에 있어서, 'ref as MutableRefObject<HTMLInputElement>' 라고
타입을 뒤에 정해주지 않으면 에러가 발생합니다. 
ref의 타입을 살펴보니 RefObject와 MutableRefObject 등이 존재하는데,
뒤에 as를 붙여주지 않으면 RefObject로 인식되어 readonly 속성이 붙는 것 같습니다.
아직까지 해결 방법을 찾지 못해서 일단은 as를 붙여주긴 했습니다만..
타입스크립트에서 as의 사용이 전체적으로 권장되지 않는 분위기인 것 같은데,
이런 특수한 상황에서의 as 사용에 관해서는 어떻게 생각하시는지 궁금합니다.

3. 테스트 코드 리뷰도 해주실 수 있으면 부탁드리겠습니다!

2021-06-10 14:17 UTC, ysm0622 requested changes
1단계 피드백에서 말씀해주신 타입 추론을 하기 위해서는,
tuple임을 명시해주기 위해 as const를 써줘야 하는 듯 합니다.
그러지 않으면, 배열로 추론되기 때문에 배열의 모든 요소들이
string | ChangeEventHandler | Dispatch<SetStateAction> 으로 추론돼서,
사용하는 곳에서 에러가 났습니다. 혹시, as const를 적어서 tuple로 만들어주는 것이 의도하신 바가 맞나요?

- 넵! 맞습니다.

forwardRef를 사용하는 데에 있어서, 'ref as MutableRefObject' 라고
타입을 뒤에 정해주지 않으면 에러가 발생합니다.
ref의 타입을 살펴보니 RefObject와 MutableRefObject 등이 존재하는데,
뒤에 as를 붙여주지 않으면 RefObject로 인식되어 readonly 속성이 붙는 것 같습니다.
아직까지 해결 방법을 찾지 못해서 일단은 as를 붙여주긴 했습니다만..
타입스크립트에서 as의 사용이 전체적으로 권장되지 않는 분위기인 것 같은데,
이런 특수한 상황에서의 as 사용에 관해서는 어떻게 생각하시는지 궁금합니다.

- 말씀해주신 `ref as MutableRefObject` 부분을 코드 변경사항에서 찾지못했습니다.

테스트 코드 리뷰도 해주실 수 있으면 부탁드리겠습니다!

- 테스트코드도 안올라왔는데 코드를 제대로 푸시하신게 맞나요? 🤔

2021-06-10 14:17 UTC, ysm0622 commented on src/hooks/useInput.ts
> +  const [value, setValue] = useState<string>(defaultValue);
여기 <string> 제네릭을 꼭 넣어줘야할까요? 👀

2021-06-10 14:17 UTC, ysm0622 commented on src/pages/LinePage/LinePage.tsx
> +  const [formOpen, setFormOpen] = useState<boolean>(false);
여기도 <boolean>을 반드시 넣어줘야할까요? 👀

2021-06-10 14:17 UTC, ysm0622 commented on src/pages/MapPage/MapPage.tsx
> +const LINE_BEFORE_FETCH: APIReturnTypeLine[] = [];
이 빈 배열은 왜 필요한가요?

2021-06-10 14:17 UTC, ysm0622 commented on src/pages/MapPage/MapPage.tsx
> +    const timer = setTimeout(() => setIsLoading(true), 500);
왜 setTimeout을 걸어주셨나요?

2021-06-10 14:17 UTC, ysm0622 commented on src/pages/MapPage/MapPage.tsx
> +                          {includedLines?.map(
분리할수있는 부분은 잘라서 컴포넌트로 분리해보면어떨까요?

2021-06-10 18:29 UTC, iborymagic commented on src/hooks/useInput.ts
> +  const [value, setValue] = useState<string>(defaultValue);
앗.. defaultValue가 들어가면서 타입 추론이 되는군요!

2021-06-10 18:54 UTC, iborymagic commented on src/pages/LinePage/LinePage.tsx
> +  const [formOpen, setFormOpen] = useState<boolean>(false);
초기값으로 타입 추론이 가능한 경우에는 전부 제네릭을 삭제해줬습니다!

2021-06-10 19:20 UTC, iborymagic commented on src/pages/MapPage/MapPage.tsx
> +    const timer = setTimeout(() => setIsLoading(true), 500);
데이터 fetch가 너무 빨리 되는 경우에, 스피너가 번쩍 하고 나오는 것보다는 
그냥 아무것도 나오지 않는 게 더 깔끔한 것 같다고 생각했습니다.
그래서 데이터 fetching이 500ms보다 오래 걸리는 경우에만 스피너를 보여주고 싶었습니다.

2021-06-10 19:28 UTC, iborymagic commented on src/pages/MapPage/MapPage.tsx
> +const LINE_BEFORE_FETCH: APIReturnTypeLine[] = [];
데이터를 fetch하기 전의 초기값인 빈 배열과, fetch 해온 데이터가 텅 비어있는 경우의 빈 배열을 구분해주기 위함입니다.
데이터가 없는 경우에 '텅' 이라고 적힌 이미지를 표시해주고 싶었는데, 
처음에 초기값으로 빈 배열을 가지고 있기 때문에 번쩍 하고 이미지가 나타났다가 사라지는 현상이 발생했습니다.
그래서 이미지가 아주 잠깐 번쩍였다가 사라지는 현상을 없애기 위해 저 배열을 사용한 것인데,
아직 MapPage에는 fetch해 온 데이터가 텅 비어있는 경우에 보여줄 이미지를 제작하지 않은 상태입니다.

2021-06-10 19:51 UTC, iborymagic commented
앗.. 테스트 코드 파일 추가했고, ref as MutableRefObject 부분에 주석 추가해서 push 해놨습니당

2021-06-11 09:01 UTC, ysm0622 commented on src/pages/MapPage/MapPage.tsx
> +const LINE_BEFORE_FETCH: APIReturnTypeLine[] = [];
초기값이 없을때는 다른 타입을 사용하는게 맞는것같아요.
"배열 자체가 아직 없다", "배열이 있지만 그 배열이 비어있다", "배열이 있고, 그 배열 안에 데이터가있다."
라는 세가지 상태를 각각 다른값으로 구분해줄필요가있습니다.
일반적으로 데이터가없을땐 "배열 데이터 자체가 아직 없다" 는 null혹은 undefined로 구분합니다.

2021-06-11 09:03 UTC, ysm0622 commented on src/pages/MapPage/MapPage.tsx
> +    const timer = setTimeout(() => setIsLoading(true), 500);
UX를 개선하기 위한 좋은 시도입니다! 👍 
다만 말씀하신 "너무빨리"라는 정성적인 측정값은 우리 로컬 개발환경에서만일 뿐입니다.
네트워크속도가 느리다면, 스피너가 0.5초 후에 보일것이고, 그것은 또 그것대로 안좋은 UX가 될것같아요.

- 네트워크 속도가 느리던 빠르던, 좋은 경험을 주려면 어떻게해야할까요?
- 혹은 네트워크속도를 안다면 더 각 유저에게 더 좋은 경험을 줄 수있지 않을까요?
- 네트워크 속도를 알아낼 수 있을까요?

등등을 고민해보시면 좋을것같습니다! 👍

2021-06-11 09:37 UTC, ysm0622 commented
테스트를 작성하는 과정이 어땠는지, 어떤 목표로 테스트코드를 작성했는지 함께 공유해주시면 리뷰하기 더 수월할것같아요! 👍

2021-06-11 19:03 UTC, iborymagic commented
이번 미션에서는 백엔드 API가 무조건 정상적으로 날아온다는 가정하에 UI 테스트만 진행했습니다!
그래서 API 요청을 보내는 특정 메소드를 실행했을 때 날아올 데이터들을 전부 mock 해두고,
UI와 (API 요청이 필요한)상호작용을 했을 때 요청이 정상적으로 수행되는지를 위주로 테스트했습니다.

사실 처음에는 msw를 활용해서 올바른 주소로 요청이 가는지까지 확인을 해보고 싶었지만,
msw를 처음 사용해봤기 때문에 이리저리 헤매면서 시간이 너무 많이 지체되었습니다..😭
그러던 중에 jest의 mock 기능을 발견하게 되면서 mocking으로만 테스트를 해도 
UI가 정상적으로 동작하는지 테스트하는 데에는 무리가 없겠다고 생각했습니다.
그래서 response 데이터를 mocking해서 테스트를 수행하게 되었습니당

2021-06-11 19:36 UTC, iborymagic commented on src/pages/MapPage/MapPage.tsx
> +const LINE_BEFORE_FETCH: APIReturnTypeLine[] = [];
말씀을 듣고 보니, 처음에 데이터를 fetch 해오기 전에는 아예 데이터가 없는 상태이므로 
null이나 undefined를 쓰는 게 좀 더 적절한 것 같네요.
피드백 반영하였습니다!

2021-06-13 14:30 UTC, ysm0622 commented
대체로 잘 작성해주신것같습니다!
APi 요청이후에 UI가 잘변경되는지까지 함께 테스트해주시면 좋을것같아요! 👍

2021-06-13 14:30 UTC, ysm0622 approved these changes

2021-06-13 14:30 UTC, merged