[1단계 - 지하철 노선도 미션] 곤이(김기융) 미션 제출합니다.
woowacourse/react-subway-map pull request #8
Opened 2021-05-29 10:22 UTC by yungo1846

안녕하세요 Vallista님 😊
매번 Vallista님이 다른 크루들에게 남겨주신 리뷰만을 보며 부러워하다 드디어 첫 리뷰를 받게 되었습니다. 정말 영광입니다 ㅎㅎ
처음 사용해보는 라이브러리들이 많아 우여곡절이 있었습니다...!
리뷰 잘 부탁드립니다 👍

## [🌎 데모 사이트](https://yungo1846-react-subway-map.netlify.app/)

## 🤦‍♂️ 신경쓴 점
1. Saga Test Plan을 사용하여 Action에 따른 Saga의 동작과 리듀서의 상태를 테스트하였습니다.
2. 아직 TS가 낯설지만 최대한 Type을 깔끔하게 작성해보려고 노력했습니다.

## 🙋‍♂️ 궁금한 점
1. 반복되는 컴포넌트 안에서 useDispatch와 useSelector 같은 훅을 사용해도 괜찮을까요? 반복되는 컴포넌트 안에서 훅을 반복적으로 부르는 것도 일종의 비용이라고 느껴집니다. 물론, 이를 막기 위해 컨테이너 컴포넌트에서 Props를 내려주면 되지만 이런 경우 리덕스로 전역상태를 관리하는 장점을 크게 느끼지 못할 것 같습니다. Vallista님의 의견이 궁금합니다!

2. 이제 와서 여쭙기 적절하지 않은 질문일 수 있지만 상수화를 어디까지 해야할지 다시금 의문이 생겼습니다. 매직넘버를 직접 작성하는 것은 개발자가 이 숫자가 무엇을 의미하는지 알 수 없게 만듭니다. 따라서 의미를 부여하고 쉽게 변경하지 못하게 하기위해 상수화가 필요하다고 생각합니다. 반면 에러 메세지나 HTML tag안에 들어가는 텍스트의 경우 상수화를 하지않아도 의미가 명확하다고 생각됩니다. 물론, 내용이 실수로라도 쉽게 변경될 수 있기 때문에 휴먼에러를 막기 위해서는 상수화가 필요하다고 생각됩니다. 하지만 동시에 재사용성 될 가능성이 낮은 문자열의 경우에도 과연 상수화가 필요할까 하는 의문이 들었습니다.

3. Validation 함수 파일 위치에 대해 질문드리고 싶습니다. 현재는 컴포넌트 폴더 안에 '컴포넌트이름'.validation.tsx로 파일을 만들어 검증 로직을 분리하였습니다. 이렇게 한 이유는 해당 검증 로직을 사용하는 컴포넌트와 검증 로직의 위치를 최대한 가깝게 만들기 위함이였습니다. 하지만 컴포넌트 폴더 안에 이러한 방식으로 검증로직이 들어가는 것이 적절한지에 대한 의문이 들었습니다.

2021-05-30 08:12 UTC, Vallista commented
안녕하세요~ 내일 오전에 리뷰해서 올리겠습니당~

2021-06-03 15:17 UTC, Vallista requested changes
안녕하세요 곤이!
코드가 많아서 코드리뷰하는데 오래걸렸네요 후...
그래도 전반적으로 코드는 깔끔하지만 바빠서 급히 처리한 부분? 이 조금 보였어요!
그러한 부분을 코드 라인 전반적으로 피드백 드렸습니다!

# UX 피드백

UX 피드백은 코드 리뷰에 집중하시라고 따로 진행하지 않겠습니다!

# 전반적인 코드 피드백

1. 열거형 타입이 거의 없고, 왜 const를 주로 쓰셨을까요? 적어도 type alias로 string 타입을 정의할 수 있어 보이는데, 타입스크립트의 이점을 못쓰고 계신 것 같아요 ㅠㅠ 최대한 그러한 문법으로 사용하는게 좋겠어요!

2. 문자열로 비교를 하거나 문자열로 모든 상황을 구별하고 있는데요! 프로젝트 상에서 다양한 상황을 문자열로만 해결하려 하지말고, 다양한 프리미티브 타입(혹은 type alias, enum 등) 넣어서 해결할 수 있는 부분이 충분히 있어보여요! 그리고 이러한 부분을 사전에 체크하도록 구현을 하지 않아서 그거에따른 예외처리가 더 생기고... 요 부분은 코드 라인에 적어두었으니 해결해보시면 좋겠습니다!

3. 애니메이션을 주실 때, top, left 등과 같은 reflow, repaint에 영향이 있는 것보다 transform 등으로 줘보는게 어떨까요?

4. 나머지는 코드 라인에 상세히 피드백을 드셨습니다!!

# 질문 답변

## 첫 번째 질문

```
반복되는 컴포넌트 안에서 useDispatch와 useSelector 같은 훅을 사용해도 괜찮을까요? 반복되는 컴포넌트 안에서 훅을 반복적으로 부르는 것도 일종의 비용이라고 느껴집니다. 물론, 이를 막기 위해 컨테이너 컴포넌트에서 Props를 내려주면 되지만 이런 경우 리덕스로 전역상태를 관리하는 장점을 크게 느끼지 못할 것 같습니다. Vallista님의 의견이 궁금합니다! (현재 코드는 Page 컴포넌트에서 Props를 내려주는 방식을 채택하고 있습니다 :)

{stations.map(({ id, name }) => (
  <StationListItem key={id} name={name} id={id} deleteStation={deleteStation} />
))}
```

useDispatch와 useSelector는 오히려 수많은 컴포넌트에서 사용하라고 만든 친구라고 생각해요. EventBus등의 상황에도 쓰이지만, 상태를 파편화하고 관리는 Redux로 하면서, 모듈 단위로 상태를 나누어 전파하는 용도로 사용될 수 있다고 생각하거든요. [성능에 대한 이야기는 여기에 있어요. useDispatch는 성능과 무관하고, useSelector는 적용되는 Component와 하위 Prop이 어떤 관계가 있는지에 따라 성능이 달라지겠네요.](https://stackoverflow.com/questions/62459084/does-it-hurt-performance-to-use-the-react-redux-hooks-in-a-list)

리덕스에서 상태를 잘게 쪼개서, 지하철 노선도의 경우에는 노선도 부분, 노선도의 상태가 출력되는 부분 등, 각각의 모듈을 파편화하여 모듈 단위로 상태를 useSelector로 내려서 사용할 수 있게 해도 좋겠습니다. 이렇게 되면 비단 페이지에서 일렬로 드릴링해서 사용하는 방법 말고, 다양한 영역의 컴포넌트에서 사용될 수 있도록 모듈화 할 수 있겠죠.

다만, 지하철 노선도가 선택이 되었는지 안되었는지 여부를 각 노선이 모두 알아야 한다면, 이 부분은 각 노선에서 useSelector를 참조하는게 아닌, 상위 컴포넌트에서 useSelector를 해서 렌더링할 때 함께 뿌려주는게 더 좋은 판단일 것 같습니다. Prop Drilling이든, redux를 사용해서 useSelector를 사용하던, 모든 부분은 단 하나만 사용한다기보다, 적정 기술을 해당 상황에 맞춰서 사용하면 되겠습니다.

현재 프로젝트에서는 Prop Drilling에 의존하다보니 Modal 과 같은 상태를 2depth 넘게 props를 넘기고 있어요. 이런 부분은 확실히 redux의 상태로 만들어 다양한 곳에서 dispatch를 통해 redux 상태를 변경하고, 해당 redux 상태를 modal에서 useSelector를 통해 subscribe해서 작업하도록 하면 좋겠네요.

## 두 번째 질문

```
미션을 진행하면서 상수화를 어디까지 해야할지 다시금 의문이 생겼습니다. 매직넘버를 직접 작성하는 것은 개발자가 이 숫자가 무엇을 의미하는지 알 수 없게 만듭니다. 따라서 매직넘버는 숫자에 의미를 부여하고 사람이 쉽게 변경하지 못 하도록 하기위해 상수화가 필요하다고 생각합니다. 반면 에러 메세지나 HTML tag안에 들어가는 텍스트의 경우 상수화를 하지 않아도 충분히 의미가 명확하다고 생각됩니다. 물론, 내용이 사람의 실수로 인해 쉽게 변경될 수 있기 때문에 휴먼에러를 막기 위해서는 상수화가 필요하다고 생각됩니다. 하지만 동시에 재사용성 될 가능성이 낮은 문자열의 경우에도 많은 수고를 들여가면서까지 상수화 작업이 필요할까 하는 의문이 들었습니다.
```

상수화를 많은 수고를 들여가면서까지 해야할 필요는 없지만, 적어도 도메인 분리 관점에서 코드를 쉽게 볼 수 있게 어딘가로 격리는 해주어야겠죠!
그러한 격리의 레이어가 utils/constants/index.ts 등이겠죠?
최소한 그 정도는 필요해보입니다. 인라인으로 매직넘버를 넣는 행위까지는 어느정도 이해가 되어요!

## 세 번째 질문

```
Validation 함수 파일 위치와 네이밍에 대해 질문드리고 싶습니다. 현재는 컴포넌트 폴더 안에 '컴포넌트이름'.validation.tsx로 파일을 만들어 검증 로직을 분리하였습니다. 이렇게 한 이유는 해당 검증 로직을 사용하는 컴포넌트와 검증 로직의 위치를 최대한 가깝게 만들기 위함이였습니다. 하지만 컴포넌트 폴더 안에 이러한 방식으로 검증로직이 들어가는 것이 적절한지에 대한 의문이 들었습니다.
```

왜 적절한지 의문이 드셨을까요? 이 세상에 완벽한 코딩이란 없습니다. 그런게 있으면 모든 개발자가 그 방식으로 작성을 했을꺼라 생각해요~ 다만, 이게 안좋을 것이다 라고 생각은 할 수 있는데요! 현재 방식이 크게 문제가 있다고 생각하진 않습니다. 레이아웃마다 예외에 대한 메시지 처리는 필요하고, 그게 어떤 컴포넌트 레이어에 필요하다고 하면 요렇게 작성해도 괜찮아보입니다 👍 

하지만 조금 아쉬운 점은, validation이 들어가는 컴포넌트에 대한 레이어 설정이 없다는 점입니다. 해당 컴포넌트는 form이 들어가는 컴포넌트 들인데, 이러한 form 컴포넌트는 일반적인 레이아웃과는 다르게 서버와 1:1 매칭이 되거나 데이터 패칭이 redux와 빈번하게 이뤄지는등의 행동이 필요하죠. 그래서 이러한 컴포넌트를 특정한 레이어로 스코핑을 해두고, 그 레이어에 대한 양식으로 .validation.ts를 가져가던지, 조금 더 구조상으로 명확하게 볼 수 있으면 좋겠습니다! 👍 

p.s. 코드 라인 리뷰 수가 거의 70개에 육박합니다... 홧팅...

2021-06-03 15:17 UTC, Vallista commented on REQUIREMENTS.md
> +# 🚇 지하철 노선도 미션 - 기능 요구 사항
음.. REQUIREMENT와 README가 거의 다른게 없는데 굳이 요거 맹글어야할까요?

2021-06-03 15:17 UTC, Vallista commented on TEST_REQUIREMENTS.md
> +##### 리덕스 상태 관리: 유저 정보, 서버, 역 정보, 노선 정보
header의 목적으로 안쓰여도 되어 보여요!

> 리덕스 상태 관리: 유저 정보, 서버, 역 정보, 노선 정보

정도로도 괜찮지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on public/assets/arrow.svg
> +<g>
<g></g> 얘네는 없어도 되어요!
보아하니 웹에서 긁어온 것 같군요.... 흑

2021-06-03 15:17 UTC, Vallista commented on public/assets/arrow.svg
> +<g>
(어디 페이지에서 긁어왔는지도 흐흐 알지유)

그런데 이 arrow는 css 의 `:after`, `:before` 속성으로도 충분히 구현할 수 있는데 굳이 svg 써야하나요?

2021-06-03 15:17 UTC, Vallista commented on .storybook/main.js
> +}
eof

2021-06-03 15:17 UTC, Vallista commented on src/App.tsx
> +  useEffect(() => {
custom hooks로 뺄 수 있지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on src/App.tsx
> +  useEffect(() => {
App에서만 쓰이니까 상관없을지도..

2021-06-03 15:17 UTC, Vallista commented on src/App.tsx
> +          <Route exact path={ROUTE.HOME} component={Home} />
map<ROUTE.BLAH - Component> 형태가 반복되는데, 테이블로 맹글어서 map으로 만들어 로직을 줄일수도 있겠습니다

2021-06-03 15:17 UTC, Vallista commented on src/api/auth.ts
> +interface SignInResponse {
I~ prefix를 붙여서 Type과 구별이 가능하도록 하는 건 어떨까요?
Type은 Union적 성격을 띌수도 있고, string을 가질 수도 있으니!

2021-06-03 15:17 UTC, Vallista commented on src/api/auth.ts
> +      if (response.status > 400) {
요런 400~ >400 처리는 다른 API도 쓸테니까 API.ts 같은거 만들어서 에러를 만들어주는 뭔가의 틀을 만드는건 어떨까요?

2021-06-03 15:17 UTC, Vallista commented on src/api/auth.ts
> +import axios from 'axios';
여유가 있으시면 API 들은 테스트코드가 있으면 좋겠어요

2021-06-03 15:17 UTC, Vallista commented on src/api/auth.ts
> +      return { error: error.message ?? RESPONSE.FAILURE };
음? 뭐를 위한 ?? 일까요..? `error?.message ?? ` 요거 테스트 해보셨나유..?

2021-06-03 15:17 UTC, Vallista commented on src/api/section.ts
> +    try {
전반적으로

```
 try {

      return { lines: response.data };
    } catch (error) {
      return { error: error.message ?? RESPONSE.FAILURE };
    }
```

패턴이 반복되네요~ 줄일수 있을 것 같아요~

2021-06-03 15:17 UTC, Vallista commented on src/assets/svg/edit.svg
> +</g>
여기도 날려주셔야 할 듯!

2021-06-03 15:17 UTC, Vallista commented on src/assets/svg/mail.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="envelope" class="svg-inline--fa fa-envelope fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path f
eof

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Button/Button.styles.tsx
> +  box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px;
0px은 삭제!

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Button/Button.tsx
> +  onClick?: (event: React.MouseEvent) => void;
onClick은 optional이면 안될 것 같아요!

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Button/Button.tsx
> +  onClick?: (event: React.MouseEvent) => void;
onClick을 안넣으면 Button의 의미가 없지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/ContentContainer/ContentContainer.styles.tsx
> +  box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px;
여기도 0px!

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Button/Button.tsx
> +const Button = ({ type, children, bgColor, fontColor, isDisabled, shape, onClick }: Props) => {
default로 type은 'button'을 넣어도 될 듯요!

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Input/Input.tsx
> +  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
onChange가 없으면 Input을 사용하는 목적이,..!

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Input/Input.tsx
> +const Input = ({ type = 'text', emoji, label, placeholder, borderColor, name, onChange, required, value }: Props) => {
그리고 이렇게 bypass만 할 것이라면 forwardref를 사용해서 uncontrolled component로 맹그는게 좋겠네요.

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Modal/Modal.styles.tsx
> +  background: rgba(0, 0, 0, 0.5);
`(#000, 0.5)`도 되겠슴다!

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Modal/Modal.styles.tsx
> +  transition: top 0.25s ease;
top animation을 주기보다는 transform: translate...로 주는게 더 좋지 않을까요?

https://developers.google.com/web/fundamentals/design-and-ux/animations/animations-and-performance?hl=ko

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Modal/Modal.styles.tsx
> +  transition: top 0.25s ease;
reflow, repaint 측면에서,,

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Modal/Modal.tsx
> +  onCloseModal: () => void;
`<Modal onClose={} />` 만 해도 선언적으로 뭔지 잘 알수 있지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/Navigation/Navigation.styles.tsx
> +  z-index: 100;
z-index를 어디 한 군데에서 관리하는게 좋지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/SelectInput/SelectInput.styles.tsx
> +  background-color: white;
Color pallate 사용을 지향합시다!

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/SelectInput/SelectInput.tsx
> +  onChange?: (event: React.ChangeEvent<HTMLSelectElement>) => void;
onChange가 옵셔널이면 안될 것 같습니다!

2021-06-03 15:17 UTC, Vallista commented on src/components/@commons/SelectInput/SelectInput.tsx
> +  value?: string | number;
얘도 옵셔널이면 안될 것 같아유..

2021-06-03 15:17 UTC, Vallista commented on src/components/LinePage/AddLineForm.tsx
> +    if (value.slice(-1)[0] === ' ') {
요 구문은 상대적으로 안전하지 않아 보이네요!

1. 왜 ' ' 를 비교해야하는지?
2. value가 undefined (그럴일은 없겠지만) 숫자가 들어오면..?

2021-06-03 15:17 UTC, Vallista commented on src/components/LinePage/AddLineForm.tsx
> +          name='name'
name..?

2021-06-03 15:17 UTC, Vallista commented on src/components/LinePage/LineListItem.tsx
> +  deleteLine: (id: number) => void;
선언적 프로그래밍에서, deleteLine을 딱 보면 무엇인지 파악할 수 있을까요..?

`onDeleteLine: (id: number) => void;`
로 해야할 듯요!

2021-06-03 15:17 UTC, Vallista commented on src/components/LinePage/LineModalForm.styles.tsx
> +  box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px;
0px!

2021-06-03 15:17 UTC, Vallista commented on src/components/LinePage/LineModalForm.validation.tsx
> +  return '';
빈 문자열로 하기보다 null 정도로 하는게 좋지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on src/components/LinePage/LineModalForm.validation.tsx
> +  return '';
그럼 사용처에서 if(??? !== null) return 하고 아래에 안전하게 사용할 수 있겠어요

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/AddSectionForm.tsx
> +  const handleSelectLine = (e: React.ChangeEvent<HTMLSelectElement>) => {
음 요 친구는 함수가 handle의 성격은 아닌걸로 보여요!
onSelectLIne 정도가 나아 보이네요!

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/AddSectionForm.tsx
> +  const handleModalClose = () => {
얘도 handle 인가요!?
두 군데 이상 유틸로 쓰이는 부분은 아니고 on- 이벤트를 분리하는 성격정도로만 보여요!

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/SectionListItem.tsx
> +  lineColor?: string;
COLOR 를 enum으로 만들었으면 enum 타입으로 지정해도 괜찮지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/SectionListItem.tsx
> +    if (lineSection.stations.length <= 2) {
< 3

해도 괜찮겠네요

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/SectionListItem.tsx
> +        {distance >= 0 && (
distance가 -1 이하로 떨어질수도 있나요?

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/SectionModalForm.styles.tsx
> +
고오오옹백..?

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/SectionModalForm.styles.tsx
> +`;
띄워주세용..

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/SectionModalForm.tsx
> +    Number(sectionInfo.distance)
distance가 ''면.... NaN이 되겠네요..? 위험하지 않을까요? 초기화 값을 0을 주는게 더 나을듯?

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/SectionModalForm.validation.tsx
> +  if (!lineId) {
'' 을 걸러내기 위함인가용?

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/SectionModalForm.validation.tsx
> +export const getStationsErrorMessage = (lineSection: LineSection, upStationId: string, downStationId: string) => {
근데 전반적으로 ID가 number 프리미티브 타입인게 더 낫지 않을까요?
문자열 단위로 비교보다는 id니까 유니크 벨류..

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/SectionModalForm.validation.tsx
> +  if (isNaN(distance)) {
distance가 문자열인 상황 자체를 막아버리는게 좋지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on src/components/SectionPage/SectionModalForm.validation.tsx
> +  if (distance < 1) {
if (distance === 0)

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +import React, { useState } from 'react';
import 순서를 제어하는게 좋지 않을까요?

react
react-redux
react-router-dom

...

이렇게 해야 좀 더 잘 알 수 있지 않을지!

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +    SERVER.URL = e.target.value;
`SERVER.URL = e.target.value` ?!?!?!?
constants/constant인데요!?

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +import { BASE_URL, ROUTE, SERVER } from '../../constants/constant';
constants/constant 좀 이상하지 않나요!?

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +  const isServerSelected = Boolean(serverName);
serverName은 string 처럼 보이고,,, Boolean..? 그러면 '' 으로 체크하나요? 음... 확실히 null 형태로 나타내는게..?

2021-06-03 15:17 UTC, Vallista commented on src/modules/station/station.test.ts
> +it('지하철 역 목록을 성공적으로 불러온다.', async () => {
오 사가테스트!

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +    dispatch(selectServer({ serverName: e.target[e.target.selectedIndex].innerText, baseURL: e.target.value }));
e.target.selectedIndex가 없을 확률은 없을까요??

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +    dispatch(selectServer({ serverName: e.target[e.target.selectedIndex].innerText, baseURL: e.target.value }));
e.target[e.target.selectedIndex].innerText

가 없는 경우에는 에러가 안나도록 수정을 해야할 것 같아요!

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +    dispatch(loginAsync({ email, password }));
`dispatch(loginAsync(loginInfo))`

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +    if (!isValidForm) return;
isValidForm 선언을 밑에 했긴 했는데, 코드상으로 읽을 때 위에서 아래로 절차형으로 읽기 때문에 변수는 위로 올리는게 더 낫지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +        <Button isDisabled={isValidForm ? false : true}>로그인</Button>
!isValidForm

하면 되지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +        <S.Message>{loginInfo.password && passwordErrorMessage}</S.Message>
`{ loginInfo.password && <S.Message>{passwordErrorMessage}</S.Message> }`

이게 맞지 않을까요..?

2021-06-03 15:17 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +        <S.Message>{loginInfo.password && passwordErrorMessage}</S.Message>
메시지 레이아웃을 보아야 하나요??

2021-06-03 15:17 UTC, Vallista commented on src/constants/api.ts
> +export const RESPONSE = {
enum이 낫지 않을까요?

2021-06-03 15:17 UTC, Vallista commented on src/constants/constant.ts
> +  URL: '',
왜 SERVER는 constant인데 URL이 공백인가유 ㅠㅠ

2021-06-03 15:17 UTC, Vallista commented on src/constants/styleConstant.ts
> +export const COLOR = {
enum으로 해도..?

2021-06-03 15:17 UTC, Vallista commented on src/constants/styleConstant.ts
> +export const PALETTE = {
여기도 enum..

2021-06-03 15:17 UTC, Vallista commented on src/constants/styleConstant.ts
> +export const PALETTE = {
근데 COLOR랑 분리할 이유가 없어요

2021-06-03 15:17 UTC, Vallista commented on src/constants/styleConstant.ts
> +export const SIZE = {
enum..

2021-06-03 15:17 UTC, Vallista commented on src/modules/index.ts
> +    state = undefined;
왜 Undefined 일까요?

2021-06-03 15:28 UTC, Vallista commented on src/api/auth.ts
> +interface SignInResponse {
https://github.com/woowacourse/react-subway-map/pull/9#discussion_r642064700

재엽님이 좋은 피드백을 주셨는데요! I~ prefix로 주는 형태는 코드 컨벤션의 일관성을 해치니, 다른 구분 방법을 생각해보아도 좋을 것 같아요!

2021-06-03 15:35 UTC, bigsaigon333 commented on src/App.tsx
> +          <Route exact path={ROUTE.HOME} component={Home} />
와... 무릎을 탁치고 갑니다... :+1: :+1: :+1:

2021-06-03 15:39 UTC, bigsaigon333 commented on src/components/@commons/Button/Button.tsx
> +  onClick?: (event: React.MouseEvent) => void;
TS 1도 모르지만.... Button type이 submit 일 때는 onClick 이 불필요하지 않을까요...? 👀👀

2021-06-03 17:29 UTC, Vallista commented on src/components/@commons/Button/Button.tsx
> +  onClick?: (event: React.MouseEvent) => void;
아하 그렇네요!

2021-06-03 23:41 UTC, yungo1846 commented on REQUIREMENTS.md
> +# 🚇 지하철 노선도 미션 - 기능 요구 사항
최초에는 README 안에 미션 안내에 대한 내용이 있어 분리를 했습니다. 하지만 READEME를 정리하면서 REQUIREMENT 내용이 중복됐네요 😂 REQUIREMENT를 삭제하고 README만 남겼습니다 👍

2021-06-03 23:43 UTC, yungo1846 commented on TEST_REQUIREMENTS.md
> +##### 리덕스 상태 관리: 유저 정보, 서버, 역 정보, 노선 정보
bold처리 하기 위해 `#`을 붙였습니다... ㅎㅎ
목적에 맞게 `#` 대신 `**`로 bold 처리하였습니다!

2021-06-04 00:03 UTC, yungo1846 commented on public/assets/arrow.svg
> +<g>
하핳 역시 바로 알아보시는 군요 👍
`arrow`는 현재 `select` 태그에서 옵션을 선택을 안내하는 화살표로 사용되고 있습니다. 이 때문에 background-url 속성을 사용했습니다. after와 before 속성으로도 도전해봤는데 select 박스 내에서는 정상적으로 보이지 않는 것 같습니다 😂

2021-06-04 00:07 UTC, yungo1846 commented on src/App.tsx
> +  useEffect(() => {
user 정보와 관련된 email과 accesstoken 등을 custom hooks(useUser)로 빼두었습니다 👍

2021-06-04 00:32 UTC, yungo1846 commented on src/App.tsx
> +          <Route exact path={ROUTE.HOME} component={Home} />
``` jsx
const routes = [
  { path: ROUTE.HOME, component: Home },
  { path: ROUTE.SIGN_IN, component: SignIn },
  { path: ROUTE.SIGN_UP, component: SignUp },
  { path: ROUTE.STATION, component: Station },
  { path: ROUTE.LINE, component: Line },
  { path: ROUTE.SECTION, component: Section },
];
```
위와 같이 변경했습니다. 이런 방법은 생각지도 못햇는데 감사합니다 👍👍👍

2021-06-04 04:38 UTC, yungo1846 commented on src/assets/svg/edit.svg
> +</g>
넵 수정했습니다!

2021-06-04 04:39 UTC, yungo1846 commented on src/assets/svg/mail.svg
> +<svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="envelope" class="svg-inline--fa fa-envelope fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path f
svg는 신경을 못 썼네요 감사합니다 👍

2021-06-04 04:41 UTC, yungo1846 commented on src/components/@commons/Button/Button.styles.tsx
> +  box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px;
반영했습니다 👍

2021-06-04 04:42 UTC, yungo1846 commented on src/components/@commons/ContentContainer/ContentContainer.styles.tsx
> +  box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px;
반영했습니다 👍

2021-06-04 04:51 UTC, yungo1846 commented on src/components/@commons/Button/Button.tsx
> +const Button = ({ type, children, bgColor, fontColor, isDisabled, shape, onClick }: Props) => {
음.. button tag가 기본으로 'submit' type이라 default type을 'button'으로 하지 않았습니다!
이 부분은 웹 표준을 따라가는 것이 맞다고 생각했는데 발리스타님은 어떻게 생각하시나요? 🤔

2021-06-04 04:53 UTC, yungo1846 commented on src/components/@commons/Input/Input.tsx
> +  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
맞습니다 ㅎㅎ;; onChange를 필수로 받도록 변경했습니다 👍

2021-06-04 05:14 UTC, yungo1846 commented on src/components/@commons/Modal/Modal.styles.tsx
> +  background: rgba(0, 0, 0, 0.5);
오 color hex도 opacity 적용이 되는군요
``` css
background: #000, 0.5;
background: (#000, 0.5);
background: rgba(#000, 0.5);
```
위와 같은 방법으로 시도해봤지만 background color가 정상적으로 나오지 않았습니다!
MDN에서도 opacity를 변경할 때는 rgba만을 사용하는 것 같습니다..!
어떤 방식으로 color hex에 opacity를 적용할 수 있을까요..? 🤔

2021-06-04 07:05 UTC, yungo1846 commented on src/components/@commons/Modal/Modal.tsx
> +  onCloseModal: () => void;
충분히 의미가 전달될 것 같습니다 👍

2021-06-04 07:08 UTC, yungo1846 commented on src/components/@commons/Navigation/Navigation.styles.tsx
> +  z-index: 100;
한 곳에서 관리하는 편이 훨씬 좋을 것 같습니다!
지금처럼 산발적으로 사용하면 z-index가 많이 등장하게 되면 어떤 것이 더 우선순위가 높은지 헷갈릴 것 같습니다 👍

2021-06-04 07:09 UTC, yungo1846 commented on src/components/@commons/SelectInput/SelectInput.styles.tsx
> +  background-color: white;
변경했습니다!

2021-06-04 07:10 UTC, yungo1846 commented on src/components/@commons/SelectInput/SelectInput.tsx
> +  onChange?: (event: React.ChangeEvent<HTMLSelectElement>) => void;
필수로 받도록 변경했습니다 👍

2021-06-04 07:12 UTC, yungo1846 commented on src/components/@commons/SelectInput/SelectInput.tsx
> +  value?: string | number;
스토리북으로 컴포넌트를 먼저 만들다 보니 옵셔널 조건을 너무 남발했네요 😂

2021-06-04 07:28 UTC, yungo1846 commented on src/components/LinePage/AddLineForm.tsx
> +    if (value.slice(-1)[0] === ' ') {
1. 공백(스페이스바)을 입력받지 않기 위함입니다. 하지만 ' '로 쓰면 의미가 명확하지 않아 'VALIDATION.EMPTY_INPUT'으로 상수화 하였습니다 😊
2. 라인이름에는 숫자를 쓸 수 있어서 value에 숫자가 들어오는 것은 자연스럽다고 생각합니다!

2021-06-04 07:36 UTC, yungo1846 commented on src/components/LinePage/AddLineForm.tsx
> +          name='name'
addLineForm 안에서 name은 충분히 line name을 의미할 수 있다고 판단하여 name으로 작성하였습니다 🤔

2021-06-04 07:37 UTC, yungo1846 commented on src/components/LinePage/LineModalForm.styles.tsx
> +  box-shadow: rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px;
오우오우 여러 곳에 있네요 ㅜㅜ

2021-06-04 07:51 UTC, yungo1846 commented on src/components/LinePage/LineListItem.tsx
> +  deleteLine: (id: number) => void;
``` jsx
export interface Props {
  name: string;
  id: number;
  color: string;
  deleteLine: (id: number) => void;
}

const LineListItem = ({ name, id, color, deleteLine }: Props) => {
  const handleDeleteLine = () => {
    if (!window.confirm(`${name}을 삭제하시겠습니까?`)) return;
    deleteLine(id); // onDeleteLine?
  };

  return (
    <S.LineListItem>
      <S.Name>{name}</S.Name>
      <S.ButtonContainer>
        <S.ButtonWrapper>
          <S.Button src={editSVG} />
        </S.ButtonWrapper>
        <S.ButtonWrapper>
          <S.Button src={trashCanSVG} onClick={handleDeleteLine} />
        </S.ButtonWrapper>
      </S.ButtonContainer>
    </S.LineListItem>
  );
};

export default LineListItem;
```
`deleteLine`이 이벤트 핸들러로서 쓰이지 않는 상황에서도 `on-`prefix를 붙이는 것이 자연스러울지 약간 고민이 됩니다 🤔 발리스타님의 의견이 궁금합니다 🙏

2021-06-04 08:03 UTC, yungo1846 commented on src/components/LinePage/LineModalForm.validation.tsx
> +  return '';
빈 문자열보다 null이 더 적절할 것 같습니다. 감사합니다 👍👍👍

2021-06-04 08:19 UTC, yungo1846 commented on src/components/SectionPage/AddSectionForm.tsx
> +  const handleSelectLine = (e: React.ChangeEvent<HTMLSelectElement>) => {
발리스타님이 생각하시는 `handle`과 `on` prefix의 차이점이 무엇인지 궁금합니다 😊

저는 이벤트 핸들러 관련 함수를 만들 때, on 접두사가 붙은 경우, Prop에 실제 이벤트가 연결되어 있다는 걸 뜻하고, handle 접두사가 붙은 경우, 이벤트가 발생했을 때 호출되는 실제 Function을 의미하도록 작성였습니다.
``` jsx
<SectionModalForm onSelectLine={handleSelectLine}/>
```

2021-06-04 08:19 UTC, yungo1846 commented on src/components/SectionPage/AddSectionForm.tsx
> +  const handleModalClose = () => {
위에 코멘트에 질문 남겼습니다 👍

2021-06-04 08:48 UTC, yungo1846 commented on src/components/SectionPage/SectionListItem.tsx
> +        {distance >= 0 && (
마지막 역은 distance가 없지만 데이터 구조 통일을 위해 distance를 -1로 하였습니다!

2021-06-04 08:49 UTC, yungo1846 commented on src/components/SectionPage/SectionModalForm.styles.tsx
> +
🤣

2021-06-04 08:50 UTC, yungo1846 commented on src/components/SectionPage/SectionModalForm.styles.tsx
> +`;
제가 봐도 불-편하네요 😂 좀 더 꼼꼼하게 살피겠습니다 👍

2021-06-04 09:38 UTC, yungo1846 commented on src/components/SectionPage/SectionModalForm.validation.tsx
> +  if (!lineId) {
맞습니다!

2021-06-04 09:38 UTC, yungo1846 commented on src/components/SectionPage/SectionModalForm.tsx
> +    Number(sectionInfo.distance)
distance와 id type을 number로 하고 싶었으나 초기값으로 0을 주게 되면 아무 입력이 없어도 input에 placeholder 대신 0이 출력되는 문제가 있었습니다. 이 때문에 type을 string으로 하고 빈 문자열을 초기값으로 주었습니다 😂 혹시 좋은 해결책이 있을까요?

2021-06-04 09:39 UTC, yungo1846 commented on src/components/SectionPage/SectionModalForm.validation.tsx
> +export const getStationsErrorMessage = (lineSection: LineSection, upStationId: string, downStationId: string) => {
[위에 달아주신 코멘트에 답글로 질문 남겼습니다!](https://github.com/woowacourse/react-subway-map/pull/8#discussion_r645436376)

2021-06-04 09:40 UTC, yungo1846 commented on src/components/SectionPage/SectionModalForm.validation.tsx
> +  if (distance < 1) {
distance가 문자열 타입이다 보니 소수점 입력이 들어올 수 있어서 위와같이 처리했습니다!

2021-06-04 09:42 UTC, yungo1846 commented on src/components/SignInPage/SignInForm.tsx
> +import React, { useState } from 'react';
바쁘다는 핑계로 import 순서를 정리하지 못했네요 ㅠㅠ
1. 리액트 내장 라이브러리
2. 리액트 서드파티 라이브러리
3. 커스텀 훅
4. 상수, 유틸 함수 등
5. 스타일

위 순서대로 import를 정리했습니다 👍👍👍

2021-06-04 11:41 UTC, yungo1846 commented on src/components/SignInPage/SignInForm.tsx
> +    SERVER.URL = e.target.value;
나중으로 미루겠다는 말은 영영하지 않겠다는 말과 같다는 격언이 떠오르네요 😥
정말 말도 안되는 코드라고 생각합니다.... 서버가 변경될 때 리덕스에 있는 baseURL이 변하도록 변경하였습니다 👍👍👍

2021-06-04 11:52 UTC, yungo1846 commented on src/components/SignInPage/SignInForm.tsx
> +import { BASE_URL, ROUTE, SERVER } from '../../constants/constant';
constant 안에 있던 상수들을 다른 파일들로 분리하였습니다 👍

2021-06-04 12:18 UTC, yungo1846 commented on src/components/SignInPage/SignInForm.tsx
> +  const isServerSelected = Boolean(serverName);
넵 현재는 ''로 falsy 값을 체크하고 있습니다. null을 쓰게 되면 select 태그의 value 값으로 serverURL을 넘길 수 없는 문제가 발생했습니다 😂 null 병합 연산자 사용을 고려했지만 null 병합 연산자를 사용하게 되면 결국 `value={serverURL ?? ''}`의 형태가 되어 useState의 초기값으로 ''을 준 것과 크게 다르지 않다고 판단하여 변경을 보류했습니다 🤔

2021-06-04 12:39 UTC, yungo1846 commented on src/components/SignInPage/SignInForm.tsx
> +    dispatch(selectServer({ serverName: e.target[e.target.selectedIndex].innerText, baseURL: e.target.value }));
``` jsx
serverName: e.target[e.target.selectedIndex]?.innerText ?? ''
```
옵셔널 체이닝과 null 병합 연산자를 사용하여 에러가 발생하지 않도록 수정했습니다!
감사합니다 ㅎㅎ

2021-06-04 12:44 UTC, yungo1846 commented on src/components/SignInPage/SignInForm.tsx
> +    dispatch(loginAsync({ email, password }));
디테일한 부분까지 봐주셔서 정말 감사합니다 🙏

2021-06-04 12:45 UTC, yungo1846 commented on src/components/SignInPage/SignInForm.tsx
> +    if (!isValidForm) return;
맞습니다. 변수가 위쪽에 있는 것이 읽는 사람으로 하여금 훨씬 더 자연스러울 것 같습니다. 감사합니다 😊

2021-06-04 13:13 UTC, yungo1846 commented on src/components/SignInPage/SignInForm.tsx
> +        <S.Message>{loginInfo.password && passwordErrorMessage}</S.Message>
말씀해주신대로 유효하지 않은 입력으로 메세지가 출력될 때 전체적인 레이아웃이 변경되지 않도록 하기 위해 위와 같이 코드를 작성했습니다!

2021-06-04 13:23 UTC, yungo1846 commented on src/constants/constant.ts
> +  URL: '',
SERVER URL을 리덕스에서 관리하도록 변경했습니다~

2021-06-04 13:32 UTC, yungo1846 commented on src/constants/api.ts
> +export const RESPONSE = {
enum으로 변경했습니다 👍

2021-06-04 13:34 UTC, yungo1846 commented on src/constants/styleConstant.ts
> +export const COLOR = {
변경했습니다! enum을 사용하니 타이핑에도 사용할 수 있어 편리한 것 같습니다 👍

2021-06-04 13:35 UTC, yungo1846 commented on src/constants/styleConstant.ts
> +export const PALETTE = {
네이밍이 다소 모호했던것 같습니다. LINE_COLOR로 이름을 변경하고 enum을 사용했습니다 👍

2021-06-04 13:57 UTC, yungo1846 commented on src/modules/index.ts
> +    state = undefined;
`LOG_OUT` action이 실행됐을 때 리덕스의 모든 스토어를 초기화하기 위해 사용했습니다!
[How to reset the state of a Redux store?](https://stackoverflow.com/a/35641992/15589083)

2021-06-04 13:59 UTC, yungo1846 commented on src/api/auth.ts
> +interface SignInResponse {
이 부분은 좀 더 고민해보도록 하겠습니다 😂

2021-06-05 00:40 UTC, yungo1846 commented on src/api/auth.ts
> +import axios from 'axios';
백엔드 크루들이 만든 서버가 곧 내려갈 예정이라 테스트를 추가하기에는 시간이 촉박할 것 같습니다 😂
API 테스트 코드는 별도로 학습해보겠습니다 👍👍👍

2021-06-05 05:07 UTC, yungo1846 commented on src/api/section.ts
> +    try {
axios interceptor를 사용하여 try catch 구문을 사용하지 않고 status 별로 분기를 나눠 에러를 리턴하도록 변경했습니다!

2021-06-05 05:08 UTC, yungo1846 commented on src/api/auth.ts
> +      return { error: error.message ?? RESPONSE.FAILURE };
저희가 예상한 axios 외의 메서드에서 에러가 발생한 경우를 위해 저런 식으로 처리했는데 불필요한 것 같습니다 😂
삭제했습니다 👍

2021-06-05 05:11 UTC, yungo1846 commented on src/api/auth.ts
> +      if (response.status > 400) {
status가 400 이상일 때의 분기를 재사용 가능하게 만드는 방법이 아직 떠오르지 않네요... 혹시 힌트를 조금 주실 수 있을까요..? 🤔

2021-06-05 05:30 UTC, yungo1846 commented
안녕하세요 발리스타님!
코드를 정말 꼼꼼하게 봐주셔서 감사드립니다 👍👍👍
앞으로는 조금 더 코드를 깔끔하게 작성할 수 있도록 노력하겠습니다 😂

### 남겨주신 리뷰 중 추가적인 피드백이 필요한 부분들
- [status 400 이상 처리](https://github.com/woowacourse/react-subway-map/pull/8#discussion_r645943413)
- [color hex에 opacity 적용하기](https://github.com/woowacourse/react-subway-map/pull/8#discussion_r645293734)
- ['handle', 'on' prefix의 차이](https://github.com/woowacourse/react-subway-map/pull/8#discussion_r645384294)
- [input의 value type이 number인 경우에도 placeholder를 보이게 할 수 있는지?](https://github.com/woowacourse/react-subway-map/pull/8#discussion_r645436376)
- [""과 null](https://github.com/woowacourse/react-subway-map/pull/8#discussion_r645525228)
- [메세지 레이아웃을 꼭 보여줄 필요가 있을까?](https://github.com/woowacourse/react-subway-map/pull/8#discussion_r645559952)

2021-06-05 05:41 UTC, yungo1846 commented on src/components/@commons/Input/Input.tsx
> +const Input = ({ type = 'text', emoji, label, placeholder, borderColor, name, onChange, required, value }: Props) => {
input값에 따라 즉각적인 validation을 하기 위해 controlled component를 사용했습니다 👍
forwardRef를 쓰더라도 value를 제외한 나머지 Props들은 기존과 마찬가지로 전달해야할 것 같습니다 🤔 그렇다면 Input을 uncontrolled component로 만드는 메리트가 크지 않아 보입니다...! 발리스타님께서는 어떠한 점에서 uncontrolled component 쓰는 것이 더 좋다고 생각하셨는지 궁금합니다 🙏

2021-06-05 05:48 UTC, yungo1846 commented on src/api/auth.ts
> +      if (response.status > 400) {
``` jsx
export const sectionAPI = {
  getSection: async (id: LineSection['id']): Promise<HttpResponse<LineSection>> => {
    const response = await axios.get(API.SECTION(id));

    if (response.status >= 400) {
      return { data: response.data, error: '노선 정보를 불러오는데 실패했습니다.' };
    }

    return { data: response.data, error: null };
  }
}
```
추가적으로 api 코드 전반을 위와 같이 변경했습니다!
리턴타입으로 HttpResponse를 추가하여 모든 api 코드가 동일한 리턴타입을 가지도록 변경했습니다.
기존에 비해 리턴 되는 타입이 통일되고 api를 호출하는 쪽에서 제네릭을 통해 data가 어떤 타입인지 알 수 있다는 장점이 있는 것 같습니다 👍
부족한 부분이 있다면 편하게 피드백 해주시면 감사하겠습니다! [해당 커밋입니다.](https://github.com/woowacourse/react-subway-map/pull/8/commits/6989a8a6fd5e5034e1beaf12da36f7ef7fa104c1)

2021-06-06 07:52 UTC, Vallista commented on public/assets/arrow.svg
> +<g>
음 어떻게 구현하셨는지는 모르겠지만 충분히 될 거라 생각하는데요 ㅠㅠ 뭐가 문제일까요... 뭐 쩃든 문제가 있다고 하시니 패스..

2021-06-06 07:55 UTC, Vallista commented on src/api/auth.ts
> +      if (response.status > 400) {
직접 코드를 좀 적어보려고 했는데 넘 길어져서 링크로 대체합니다용

https://github.com/Bearer/Pizzly

요기서는 체이닝 방식으로 제공하는데, 이러한 형태도 좋고 쉽게 사용할 수 있는 형태, 그 안의 바운더리에서 에러를 쉽게 처리할 수 있도록 하면 좋겠습니다 👍

2021-06-06 07:55 UTC, Vallista commented on src/components/@commons/Button/Button.tsx
> +const Button = ({ type, children, bgColor, fontColor, isDisabled, shape, onClick }: Props) => {
네 좋은데요~ 그렇다면 type에는 `type = 'submit'`이 있어야 하지 않을까요?

2021-06-06 07:59 UTC, Vallista commented on src/components/@commons/Input/Input.tsx
> +const Input = ({ type = 'text', emoji, label, placeholder, borderColor, name, onChange, required, value }: Props) => {
음, Input 컴포넌트에서 validation 처리를 하는게 좋을까요? validation이 필요한 Input 컴포넌트는 따로 있어야 로직 레이어가 잘 구별이 될 것 같은데요~ 또한 지금 validation 코드가 없어보이는데요..? 흠 제 눈에만 안보이는 걸까요? validation 로직이라는게 무엇일까요???

해봐야 label 컨디션이랑 name 컨디션 등으로 보이는데,,, 해당 부분은 어차피 input 뿐만 아니라 Radio button, checkbox 등 컴포넌트 많아지면 충분히 핵심 컴포넌트는 uncontrolled 로 만들고, 그 친구들을 조합해서 사용하는 무언가 래퍼가 더 중요해보여요~

2021-06-06 08:00 UTC, Vallista commented on src/components/@commons/Modal/Modal.styles.tsx
> +  background: rgba(0, 0, 0, 0.5);
이모션이랑 sass등지에서는 되는데, styled-component는 안되나보군요... (실망)

2021-06-06 08:03 UTC, Vallista commented on src/components/LinePage/AddLineForm.tsx
> +    if (value.slice(-1)[0] === ' ') {
일단 기본적으로, 

1. 배열에 직접 접근하는 로직은 좋지 않습니다. 만에하나 제대로 된 결과값이 안들어오는 상황을 가정 했을 때 (대다수는 그럴일이 없겠지만, 비즈니스적으로 value의 타입이 다양하게 변경되어야 하는 경우?) slice 가 제대로 slice 되어 배열 1개 이상을 만들 수 있는 상황이 완벽히 보장될까요?
2. 또한, 로직 자체도 안정적이지 않지만, 적어도 해당 로직을 쓰려고 했다면 예외처리가 있어야 했습니다. `value.slice(-1)?.[0] === ' '`을 하던, value.slice(-1)의 상황에 대한 예외와 배열 0개 조차 없을 경우를요!

2021-06-06 08:26 UTC, Vallista approved these changes
잘 적용해주셨고, 피드백 하였읍니다!

감사합니다~

2021-06-06 08:26 UTC, Vallista commented on src/components/LinePage/AddLineForm.tsx
> +    if (value.slice(-1)[0] === ' ') {
또한 저렇게 로직을 구현한다면 문제점은, 협업을 하는 곳에서 저 로직을 위해 협업자가 고민을 해야할 상황을 야기합니다.
또한 로직이 복잡하기 때문에 왜 저렇게 짯는지 도메인 지식이 있어야 하죠.

협업자가 저 코드가 안전하다는 걸 파악하려면 어떠한 것들을 고려해야할까요? 고려할 필요없이 깔끔하게 만드는게 더 좋지 않을까요..?

2021-06-06 08:26 UTC, Vallista commented on src/components/LinePage/LineListItem.tsx
> +  deleteLine: (id: number) => void;
on- 이 붙는 이유는 `특정한 상황이 발생할 때 해당 이벤트를 실행하겠다` 인데요! 결국 LineListItem 사용처에서는 `onDeleteLine: 라인이 삭제되는 이벤트 때 실행하겠다` 로 해석이 되는데요! 이게 더 자연스럽지 않을까요?

LineListItem을 사용하는 입장에서는 내부에서 어떻게 쓰던 handle이던 생각할 필요가 없죠! 그렇기 때문에 아~ 얘가 onDeleteLine 즉, 라인 삭제될 때 실행되는 이벤트 핸들러를 넣으라는 것이구나로 이해하기 쉬워보여요

2021-06-06 08:26 UTC, Vallista commented on src/components/SectionPage/AddSectionForm.tsx
> +  const handleSelectLine = (e: React.ChangeEvent<HTMLSelectElement>) => {
의미가 있었군요! 의미가 없는 줄 알고 썼는데, 명확하게 의미를 이해하고 있으므로 좋습니다!

2021-06-06 08:26 UTC, Vallista commented on src/components/SectionPage/SectionListItem.tsx
> +        {distance >= 0 && (
그러면 반대로

`distance !== -1` 로 표현할 수 있겠습니다!

2021-06-06 08:26 UTC, Vallista commented on src/components/SectionPage/SectionModalForm.tsx
> +    Number(sectionInfo.distance)
음,, 오히려 그러한 처리를 해주기위해서 다양한 로직이 더 붙을 수 있겠네요 요것은 컴포넌트 설계할 때 구조를 작업하면 되긴 하는데, 귀찮으므로 패스!

2021-06-06 08:26 UTC, Vallista commented on src/components/SignInPage/SignInForm.tsx
> +  const isServerSelected = Boolean(serverName);
사실, Null 형태든 undefined 형태든, 받는 컴포넌트 쪽에서 처리해줘야합니다. 왜냐면 사용하는 쪽에서는 어떤 데이터를 넣던 컴포넌트가 처리해줄 것을 믿고 사용하는 것이거든요, 데이터 무결성은 컴포넌트 내에서 처리해주어야 합니다!

그렇기에 아래와 같은 상황에서 이야기를 하자면, 사용처의 내부 소스에서 컨트롤을 해야한다는 이야기입니다!

2021-06-06 08:26 UTC, Vallista commented on src/constants/styleConstant.ts
> +export enum LINE_COLOR {
사실 COLOR와 LINE_COLOR는 합쳐도 되는...

2021-06-06 08:27 UTC, Vallista commented
나머지는 슬슬 고치시면서 2~3단계 하시면 되겠어용

2021-06-06 08:27 UTC, merged

2021-06-09 06:44 UTC, yungo1846 commented on src/components/@commons/Button/Button.tsx
> +const Button = ({ type, children, bgColor, fontColor, isDisabled, shape, onClick }: Props) => {
앗 그렇겠군요 🤣 감사합니다!

2021-06-09 07:10 UTC, goni-ssi commented on src/components/SectionPage/SectionListItem.tsx
> +        {distance >= 0 && (
`distance !== VALIDATION.LAST_STATION_DISTANCE` 로 변경하였습니다 👍
부등호보다 `!==`이 훨씬 더 직관적이고 좋네요. 추가적으로 Vallista님께서 `-1` 의미를 여쭤보신 것처럼 다른 협업자가 보더라도 충분히 이해할 수 있도록 상수화하였습니다.

2021-06-09 07:23 UTC, yungo1846 commented on src/components/SignInPage/SignInForm.tsx
> +  const isServerSelected = Boolean(serverName);
그렇군요 발리스타님 덕에 '데이터 무결성'이라는 새로운 개념을 하나 알게 되었네요 👍
말씀해주신대로 컴포넌트 내에서 value가 null 타입이 들어와도 정상적으로 코드가 동작하도록 변경하였습니다 😊

2021-06-09 07:26 UTC, yungo1846 commented on src/components/LinePage/AddLineForm.tsx
> +    if (value.slice(-1)[0] === ' ') {
말씀해주신대로 해당 코드는 협업하는 사람들이 보기에 무엇을 의미하는지 바로 파악하기 어려울 수 있다고 생각됩니다 😂
``` javascript
const lastInput = value?.slice(-1)[0];

if (lastInput === VALIDATION.EMPTY_INPUT) return;
```
위와 같이 옵셔널 체이닝을 추가하여 방어코드를 작성하고 변수명을 달아주어 의미를 명확하게 하였습니다!

2021-06-09 07:26 UTC, yungo1846 commented on src/components/@commons/Input/Input.tsx
> +const Input = ({ type = 'text', emoji, label, placeholder, borderColor, name, onChange, required, value }: Props) => {
이 부분은 조금 더 고민해보도록 하겠습니다 😂